### ISSUE TITLE
Booking form user experience 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#10]
https://www.jomres.net/forum/Feature-requests/25347-booking-form-user-experience

One important end user difficulty when booking is that once a room is selected there is no indication of what to do next. The selected room goes to the top of page and this is often out of sight if the chosen room is down the list. See picture.To complete the user must scroll down to see "Your details" - but this is not obvious.

The user needs to be presented with a floating text of some sort with a "complete your booking" button or similar with an anchor to the bottom of page in my opinion.

pic below shows page after I selected a room. The selected room is out of view at the top of the page. For the user, what next?

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Closed due to lack of support.
