### ISSUE TITLE
Bootstrap fonts not found

### ISSUE THREAD

**Issue by Mistermay** [WoollyinWalesIT/jomres#103]
When enabling the label editing mode and try to edit the text we see these errors and the icons are not shown:

<img width="289" alt="screen shot 2017-01-11 at 16 03 47" src="https://cloud.githubusercontent.com/assets/25034354/21853537/c9fd45f2-d817-11e6-8e1c-c5a71fee073f.png">

`jquery.min.js:3 GET https://XXXX.com/plugins/system/t3/plugins/system/t3/base-bs3/bootstrap/fonts/glyphicons-halflings-regular.woff 
Sa @ jquery.min.js:3
css @ jquery.min.js:3
W @ jquery.min.js:3
cb @ jquery.min.js:3
show @ jquery.min.js:4
n.fn.(anonymous function) @ jquery.min.js:4
$.fn.extend.show @ jquery-ui.js?v=1484063180:15380
showForm @ bootstrap-editable_bs3.min.js?v=1484063180:5
(anonymous) @ bootstrap-editable_bs3.min.js?v=1484063180:5
d @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
add @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
a.Deferred @ jquery-migrate.min.js:2
then @ jquery.min.js:2
render @ bootstrap-editable_bs3.min.js?v=1484063180:5
(anonymous) @ bootstrap-editable_bs3.min.js?v=1484063180:5
each @ jquery.min.js:2
each @ jquery.min.js:2
a.fn.editableform @ bootstrap-editable_bs3.min.js?v=1484063180:5
renderForm @ bootstrap-editable_bs3.min.js?v=1484063180:5
show @ bootstrap-editable_bs3.min.js?v=1484063180:5
show @ bootstrap-editable_bs3.min.js?v=1484063180:5
toggle @ bootstrap-editable_bs3.min.js?v=1484063180:5
(anonymous) @ bootstrap-editable_bs3.min.js?v=1484063180:5
d @ jquery.min.js:2
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
plugins/system/t3/plugins/system/t3/base-bs3/bootstrap/fonts/glyphicons-halflings-regular.ttf:1 GET https://XXXX.com/plugins/system/t3/plugins/system/t3/base-bs3/bootstrap/fonts/glyphicons-halflings-regular.ttf `

If you do fullscreen view they work.

**Comment by jomres** [comment]
Please raise a support ticket including your url, login details and the exact page you see this on.
