### ISSUE TITLE
Fixed packeges 

### ISSUE THREAD

**Issue by Mistermay** [WoollyinWalesIT/jomres#104]
Hi,

Is there a possibility to create fixed packages?

Example:

Room 1 available on thursdays stay = 4 days. And already showing without the calendar. But jut as a standard package that you can book instantly?

//

**Comment by jomres** [comment]
This is not the support forum, it's purely for bugs and feature requests. 

If  you'd like support from fellow Jomres users, please visit our forum here https://www.jomres.net/support/forum or if you'd like support from the developers please raise a ticket at https://tickets.jomres.net
