### ISSUE TITLE
Stripe Connect Commission

### ISSUE THREAD

**Issue by Mistermay** [WoollyinWalesIT/jomres#105]
When installing the stripe plugin. We see the following text:

Leave this blank if you don't want to charge commission. 

But if you leave this blank. then this error is thrown in:

Application fee (Stripe Connect Commission) not set. Please set this in Administrator -> Jomres -> Payment methods -> Gateways -> Stripe

File: jomres/core-plugins/core_gateway_stripe/j00605stripe.class.php

Line: 61

Is this known?

**Comment by Mistermay** [comment]
Just got an email back from stripe and they told me that the following:

Hi there,
Hopefully I can help clear up your confusion.

As you can see in your Stripe API logs for the request that returned this error ({
  "amount": "0",
  "currency": "EUR",
  "card": "tok_XXXXXXXXXX",
  "description": "XXXXXX@XXXXXX.com"
}), you attempted to pass the value "0" for the `amount` parameter.

As you can read in our docs, the value for this parameter must be at least "50" which corresponds to $0.50.

I hope that this clears up any confusion that you had, and if not, please feel free to reach back out to me.

Seems that the system is not sending any amounts

**Comment by jomres** [comment]
Yes, it's known, the text in the language file is wrong. You MUST enter an application fee.
