### ISSUE TITLE
Tour settings

### ISSUE THREAD

**Issue by Mistermay** [WoollyinWalesIT/jomres#106]
Hi,

The tour settings does not contain superior for example. Besides this the overall tour settings are less then the other types. Is this something thats on the roadmap to make more advance settings also for the tour option? Would love to see that most settings are also applicable for this feature :)

**Comment by jomres** [comment]
The superior option is specific to hotels because it's a classification system ( https://en.wikipedia.org/wiki/Hotel_rating ) and therefore it's not relevant to Tours.
