### ISSUE TITLE
Room capacity according to adults and children number

### ISSUE THREAD

**Issue by Nikos-c** [WoollyinWalesIT/jomres#108]
Room capacity should be calculated according to adults and children, and not only adults.
The way room creation works right now, you can not have a room that hosts, for example, 2 adults and 1 child. Your search is limited to 2 adults. If you create a room that can host 3 persons, it is possible that you end up with 3 adults in a room that can only hosts 2.

**Comment by natanzi** [comment]
but in this state price dos not change ?
and also whats is different ? when we are 2 person with 1 child , we should be got triple room

**Comment by Nikos-c** [comment]
There are rooms that, for example, have two large beds (for adults) and a small one (for a child). In this case you can not offer this room as a triple one.
That is the reason that most booking engines have this option: number of adults and number of children

**Comment by natanzi** [comment]
got it,

**Comment by joniale** [comment]
The age of the children is also needed to be sure what is the required room or bed.
