### ISSUE TITLE
API plugins tab in Jomres Plugin Manager

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#109]
When installing from the "Core API plugins” tab, upon refresh you are returned to the “Core Plugins” tab. It would be better, if possible, to remain on the "Core API plugins” tab and have the immediate visual confirmation that the plugin has been installed.

Lesser issue: would be nice to have an “Install All / Uninstall All” option for both the "Core API plugins” and the “Webhooks plugins” tabs.

**Comment by wordskill** [comment]
First issue also affects the "Webhooks plugins” tab.

**Comment by jomres** [comment]
Not really important
