### ISSUE TITLE
[WP] Jomres' instance of phpmailer stops the one in wordpress core from working

### ISSUE THREAD

**Issue by webcrab** [WoollyinWalesIT/jomres#110]
Steps to reproduce:
1) Take a quickstart Wordpress package or install jomres yourself
2) Make sure jomres is on the latest version (9.8.25)
3) Try (for instance) registering or resetting the password.
4) Result: 
`Fatal error: Cannot redeclare class SMTP in C:\xampp\htdocs\booking\wp-includes\class-smtp.php on line 27`
and no email sent

**Comment by alibarthi** [comment]
Solved by this change: https://github.com/WoollyinWalesIT/jomres/commit/1f0b2fc4e7a7c245eb109eba6f7ea46dcce9ac6d
