### ISSUE TITLE
Taxe de séjour - Local day taxe 

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#112]
For French user, we need to charge a city special day tax. This one is charged per day and per adult, because  some city do not charged children under XX years old.

It will be nice to be able to charge it as an extra charged calculated  Xday * Xadults in the booking module or input in back end ---> property configuration.

Jérôme

**Comment by gavaudun** [comment]
I confirm this is an issue for all French users.

Solution : in the Guest Type, if "Is percentage" is set to "No", the fixed Variance should be defined as "per stay" or "per night". 
"Per stay" is the current system, "Per night" is the one required for France.  
I mean of course per night per person.

This will allow to define several guest types (e.g. Adults and Teenagers where the tourist tax is applicable and Small Children and Babies where it is not).

Eric

**Comment by jomres** [comment]
Whilst I'd like to add this feature there isn't enough support for it therefore closing this feature request.
