### ISSUE TITLE
Reply email is incorrect. Showing admin when it should be guest.

### ISSUE THREAD

**Issue by picturesque** [WoollyinWalesIT/jomres#114]
Regardling the booking enquiries plugin. When the admin receives an email message regarding an enquiry and hits reply, the reply is set to go to the admin's own email address rather than the guest. The guest's name is showing but with the admin email.

Example:
From: Guest Name [admin@admin-email.com]
Sent: Tuesday, January 24, 2017 11:29 AM
To: admin@admin-email.com
Subject: The Lodge at Silver Lake - 16460837

In the body of the message, the guest email address is correct. It's just the header information that's wrong so hitting reply will email the admin/prop owner. Great if you like talking to yourself but not helpful in communicating to the guest.

**Comment by alibarthi** [comment]
You may have "Emails sent from which address?" set to your email in site config->email settings tab, so this will override the  "from" email.
