### ISSUE TITLE
use the right call for booking object in j02990add_tourist_tax

### ISSUE THREAD

**Issue by JadMakhlouta** [WoollyinWalesIT/jomres#119]
in j02990add_tourist_tax, you wrote "$bkg = new booking();" which spoiled my custom features for the booking object. This should be as follows:
$bkg = $MiniComponents->triggerEvent('05000'); // Create the booking object

**Comment by alibarthi** [comment]
But the 05000 event also does $bkg = new booking(); so i don`t really understand this.. yet..

**Comment by JadMakhlouta** [comment]
Yes sure,

but the presence of the event 05000 allows for overriding the booking
object. So that we can extend the booking object and call our extended
booking object, without copying all the booking object file and perform the
needed changes.

Notice the note in the comments at the start of booking.class.php:

It is not designed to be implemented or called directly. Instead it is
> called by the j05000bookingobject.class.php file which inherits from this
> file.


So I had plugins that added functionality to the booking class through
changing the booking object being called by overriding 05000
mini-component; but after tourist code was added, my custom implementation
was cancelled during last step of confirming booking, because you called
"new booking()" instead of the general 05000 event. This will hinder making
the booking engine easily extendable according to your philosophy.

There is also one core-plugin that overrides 05000 event. It is
minimum_occupancies, but it is not affected by the tourist call. But in
general, according to the way you designed the code, calls must be to 05000
instead of directly calling new booking().

Check your documentation at
https://www.jomres.net/manual/developers-guide/56-other-discussions/285-the-booking-engine
which reads partially:

"This class isn't called directly, rather it is called and extended by the
booking class which can be found in j05000bookingobject.class.php. The
reason we don't call the file directly is fairly straightforward: by
creating a new object booking and putting it into a minicomponent of it's
own, it's simple enough to override the basic workings of the booking
engine without actually editing any of the core Jomres files."

That's exactly what I am explaining.

**Comment by alibarthi** [comment]
We`ve made the suggested change a while back, it`s included in more recent versions
