### ISSUE TITLE
allow some fields to be empty while saving account

### ISSUE THREAD

**Issue by JadMakhlouta** [WoollyinWalesIT/jomres#120]
In j06005save_my_account, you don't allow some fields to be empty similar to the choices of the booking form in the property configuration. It is possible in single property configuration to support for some empty fields in a manner corresponding to the booking form configuration for the property configuration.  Here are the relevant lines:

if ( $firstname == "" || $surname == "" || $house == "" || $street == "" || $town == "" || $country == "" || $postcode == "" || $email == "" ) 
return;

**Comment by jomres** [comment]
Hi Jad,

For that sort of thing, we'd expect you to  modify the form and scripts if you don't need to validate them.
