### ISSUE TITLE
Ical feed improvement

### ISSUE THREAD

**Issue by gavaudun** [WoollyinWalesIT/jomres#121]
Hi Vince,
The current Ical plugin is giving a link per Property / Room Class but the planning is per Property / Room (+Room Class ?).
We should be able to retrieve (e.g. with Google Calendar) the planning by Room to reflect the Jomres planning (dashboard).
The description should not only include the Property name, but also the Room name or number (and I guess also the Room Class).
Kind regards,
Eric

**Comment by alibarthi** [comment]
This change is ready for the 9.9.9 Jomres version, please update once they`re released.
