### ISSUE TITLE
Room type name translation Issue

### ISSUE THREAD

**Issue by pipo0206** [WoollyinWalesIT/jomres#122]
Hi,
I've created a new room type and tried to trranslate it using the Label Editing feature but it seems I'm not able to make it.
As you may see in the following video (2 minutes) it doesn't work or I'm doing something wrong.
I'm having this problem only with Room type name translation. Translation of other labels works fine 
Any clue?
Thanks

Video link: https://youtu.be/bNhT1bzCJkU

![1](https://cloud.githubusercontent.com/assets/26068778/23372513/399dd448-fd1c-11e6-9e98-687399fac382.JPG)

![2](https://cloud.githubusercontent.com/assets/26068778/23372519/3ce8c518-fd1c-11e6-828b-07adb1e96cb5.JPG)

![3](https://cloud.githubusercontent.com/assets/26068778/23372522/3f1df68c-fd1c-11e6-966c-b865dd422546.JPG)

![4](https://cloud.githubusercontent.com/assets/26068778/23372526/41007b50-fd1c-11e6-9809-43f8854c4d6c.JPG)

**Comment by alibarthi** [comment]
Room types show up in 2 places in Label translations, please make sure you`re translating in both.
