### ISSUE TITLE
Discounted price percentage icons on main property photo

### ISSUE THREAD

**Issue by ebayzoev** [WoollyinWalesIT/jomres#124]
To implement the discounted price icons (like -10%, -20%) in the main property photo. 

Please see the attached file. I think Jomres needs the functionality to apply seasonal (short-term) discounts to apply to all property rooms, without entering the coupon details. It's very convenient when you have lots of properties. Instead of creating a lot of coupons on the site, visitors should be able to see the discounted price and book with the new prices without having entering coupons.

At least when a discount coupon period has enough days in the future, there should be a feature with a discount icon attracting customers to this specific property. It should just recalculate the proce on the booking form if the discount period expires on the departure date specified.

What I really want is that it shows the discount percetage icon and the strikethrough format of the old price and the new price in the "Prices from NNN per night" label. And no requirement to enter coupons.

Eraj
![3](https://cloud.githubusercontent.com/assets/814003/23467732/a45a77c8-fec0-11e6-922d-af808f450fce.png)

**Comment by aadz1** [comment]
+1

**Comment by ReneCB** [comment]
+1

**Comment by jomres** [comment]
This is the best solution I can currently arrive at right now.

https://github.com/WoollyinWalesIT/jomres/commit/583153385ea339e73417f22e5f86b64e1f24a012

You'll probably need to copy the changes in https://github.com/WoollyinWalesIT/jomres/commit/695e1cb1d60ffbe1759f0657676dcea291bd6d33 to your version of the same file in the html/com_jomres directory in the Leohtian template. 

I've left it as broad as possible, using existing functionality to show the wiseprice/last minute text output but you will probably want to modify that in the label editing page in the admin area. Alternatively, add your own markup to the new template file.

**Comment by jomres** [comment]
Right now it looks like https://snippets.jomres.net/2019-04-23-e2lf1.png
