### ISSUE TITLE
Customizing mail templates

### ISSUE THREAD

**Issue by JuanGarciaG** [WoollyinWalesIT/jomres#125]
When customizing the mail templates and assigning them to property 0, that customization applies to all properties in the chosen language.
It seems that if you want to apply a customization to a particular property and there is already a global customization for that language, the customization of the particular property does not apply. Only global customization applies.

At least in my case I do not apply the customizations of a property, and I think it is because I have customizations type "0" (Global).

If this is so, I think it would be convenient to establish a hierarchy of customizations.

**Now** -> Jomres looks for a personalization type "0" (Global) and if it is the one that always applies.

**Suggested change** **-> Jomres starts looking for a personalization for that property, if it finds it applies, if it does not exist it will look for a global personalization and if it does not exist it will apply the default one.**

**Comment by alibarthi** [comment]
Global text should override text for all properties, not just some. Same will work for emails. That`s the purpose of the global text.

**Comment by JuanGarciaG** [comment]
Hello Aladar, indeed that is the problem. If we use "Global Text" for example the text of an email, we can no longer add any personalization to any individual property, always use the "Global Text". The customizations of each property lose its usefulness.

I think the logical thing is that Jomres first check that there is a customization for that property, and if there is not apply the "Global Text".

I think this is set in the "gather_data" function of the "custom_text_class" file.

Currently this function is:

```
                    If ($ text-> property_uid == 0) {// it`s a global custom text
                        $ This-> global_custom_text [$ theConstant] = stripslashes ($ text-> customtext);
                    } Else {// it`s a property specific custom text
                        $ This-> properties_custom_text [$ text-> property_uid] [$ theConstant] = stripslashes ($ text-> customtext);
                    }
```

Could be:

```
                    If ($ text-> property_uid == **"Current Property"**) {// it`s a property custom text
                        $ This-> properties_custom_text [$ text-> property_uid] [$ theConstant] = stripslashes ($ text-> customtext);
                    }
                    Elseif ($ text-> property_uid == 0) {// it`s a global custom text
                        $ This-> global_custom_text [$ theConstant] = stripslashes ($ text-> customtext);
                    } Else {// it`s a property specific custom text
                        $ This-> properties_custom_text [$ text-> property_uid] [$ theConstant] = stripslashes ($ text-> customtext);
                    }
```

If you do not see fit to apply this change. Could you tell me which variable can be used to know the **"Current Property"**? And I can apply the change.

Thank you Aladar.

**Comment by alibarthi** [comment]
Yes, that`s the exact purpose of global things, to override property specific stuff. That`s not going to change, or at least not in the near future. 
You can get the current property uid by using the getDefaultProperty() function.

**Comment by JuanGarciaG** [comment]
Thanks Aladar

**Comment by jomres** [comment]
getDefaultProperty() will only work if the user logged in is a manager, therefore any customisations they write won't be reflected when viewed by a guest.

**Comment by alibarthi** [comment]
You can use detect_property_uid() function that handles both logged in and logged out users.
