### ISSUE TITLE
addition City name in define property Step

### ISSUE THREAD

**Issue by natanzi** [WoollyinWalesIT/jomres#126]
I have many property in small city and village ,when I want to define it , I can not define name of city that property located in,
So this would be very helpful, please consider adding these options.
and also I think when the property located in small village or Sub-city , Wikipedia Tab can not refer to it , because wikipedia refer to region only.
https://www.jomres.net/forum/How-do-I/24651-how-to-addition-city-name-to-define-property#45206

**Comment by alibarthi** [comment]
Please open a ticket and i`ll show you how to use the town instead of the region in the wikipedia region tab plugin.

**Comment by natanzi** [comment]
Dear Vince,
As you know maybe the property located in sub-city or village so its better add sub-city filed in property define process, I think this very useful and necessary.
Example:
Country: U.S.A.
State: California
Region: Orange County
City: Anaheim, Costa Mesa, Orange (Many Hotels in surrounding Cities serve Disneyland)
BR
Ntz
