### ISSUE TITLE
Jomres 9.8.26 - Fatal Error when installing locally from a backup

### ISSUE THREAD

**Issue by Gitjk** [WoollyinWalesIT/jomres#128]
Hi,
when I try to install a backup of the live site with Jomres 9.8.26 made with Akeeba on my local PC, I can't access the Jomres frontend and backend. Joomla backend works. After Akeeba says that it restored the site successfully, I always end up with the following Fatal Errors:

![jomres-9826-fatal-error](https://cloud.githubusercontent.com/assets/10586468/23579689/b5f6881c-00f2-11e7-9435-ffd4307d08cf.png)

First (small) screenshot happens when I try to access Jomres from Joomla Administration, second image happens when I try to access the frontend.

I'm not sure if that's actually a Jomres bug. Does it eventually fail to link to the Jomres FAQ?

**Comment by Gitjk** [comment]
Update: I got access again by using the Jomres webinstaller, but have no idea what actually triggered the above fatal errors.

**Comment by jomres** [comment]
It was caused by the registry being wrong, if you move from one server to another you need to delete /jomres/temp/registry.php

**Comment by Gitjk** [comment]
> It was caused by the registry being wrong, if you move from one server to another you need to delete /jomres/temp/registry.php

Never had to do that in the past when I installed a copy of the live site on my local PC in order to test updates or other changes. But nice to know. Thanks for your reply!
