### ISSUE TITLE
Problems with 9.8.26

### ISSUE THREAD

**Issue by gavaudun** [WoollyinWalesIT/jomres#132]
Hi Vince,

I found the following problems with 9.8.26 (may date back to earlier versions).

1. Caching tab disappeared from Jomres Site Config.  Caching becomes automatic or is using Joomla caching ?

2. Module at bottom of Dashboard does not show properly (trash box moved towards the right side  and the information boxes come over the trash box and are pushed even further to the right, out of the screen).  See pictures attached.
![jomres 9 8 26 a](https://cloud.githubusercontent.com/assets/26024200/23798709/17ed6808-05a6-11e7-9f50-1e4eec8d4065.jpg)
![jomres 9 8 26 b](https://cloud.githubusercontent.com/assets/26024200/23798710/17f6a382-05a6-11e7-8451-d8c846acd5c1.jpg)

3. Impossible to upgrade to 9.8.27 : no update found by joomla even when I search manually for updates !

Kind regards,
Eric

**Comment by alibarthi** [comment]
This is solved in more recent versions.
