### ISSUE TITLE
Subscription Package commission - Feature request

### ISSUE THREAD

**Issue by pipo0206** [WoollyinWalesIT/jomres#135]
Site administrator would have the possibility to create two kind of subscriptions packages.
One payment package with a rate but no commissions when booking are performed.
An another free subscriptions packages with a comission when booking is performed.

At this moment you can make the first one if you set "Activate commissions to No" or have commissions if you set it to YES. But those commissions would be for all properties.
I think it would be great if we can combine those things. #

**Comment by aadz1** [comment]
Sounds like a nice feature.

**Comment by JeromePayan** [comment]
Hi vince !
This option  could be great  : 
Be able to charged commission on ALL bookings made in jomres AND made through Other OTA (booking.com, airbnb...)
the calculation should be based on accommodation. Without taking into account housekeeping costs and local taxes for example
Or 
to be able to open and edit invoices in INVOICES back-end.
