### ISSUE TITLE
4.8.28 bug report

### ISSUE THREAD

**Issue by gavaudun** [WoollyinWalesIT/jomres#136]
Description field does not show any more in Property Settings / Information in Full Screen View.
It does work correctly in Normal View.

Eric

**Comment by jomres** [comment]
Super property manager or normal manager, Eric?

**Comment by gavaudun** [comment]
Hi Vince,
Sorry for not answering earlier.
It is the same for Property Managers and Super Property Managers.
In Full screen view, the title "Description" appears, but not the field itself.

**Comment by alibarthi** [comment]
This change will solve it https://github.com/WoollyinWalesIT/jomres/commit/99202b574b0763edc28842018135906037869792
