### ISSUE TITLE
Fatal Error : "gateway passed either doesn't exist, or is not active" 

### ISSUE THREAD

**Issue by EcoWebber** [WoollyinWalesIT/jomres#137]
Dear Sir 

I am using latest Joomla 3.6.5 with Helix 3 framework for my adventure travel website. 

As I needed an efficient booking system for my website, so 4 days back I downloaded Jomres v9.8.28 (core - free version) via "install by url" method" - Everything went fine & I landed on Jomres Dashboard

After doing initial settings & adding a property, I tried to check out the booking form after logging out -

On submitting the form it shows **"This system is temporarily unavailable . . "**

When I checked the Available Logs (Developer tools) it shows the following errors -

Error # 1

**Fatal Error: Error, gateway passed either doesn't exist, or is not active, probable hack attempt (# 256).Error in line 1257 of file '/home/ecowebber/public_html/myweblink/jomres/libraries/jomres/functions/functions.php'.Script: '/index.php'**

Error # 2 

**Error logged Error: Cms user id not set**

Kindly help me on this issue . . 

Thanks !

**Comment by jomres** [comment]
This should be resolved in the latest version, please upgrade your installation.

**Comment by jomres** [comment]
Then please raise a ticket at https://tickets.jomres.net and we'll look into it for you.

**Comment by EcoWebber** [comment]
Sure . . will do it right away 

Thanks again for quick response :)
