### ISSUE TITLE
Rounding errors with invoices when adding extra services

### ISSUE THREAD

**Issue by PaulJBis** [WoollyinWalesIT/jomres#147]
When adding extra services to a bill, specially with a quantity bigger than one (for example: "3 cups of tea, 2,25 EUR each") and when prices include tax, Jomres often shows rounding errors in the invoice.

To see this behavior:

- Configure Jomres so that prices include tax. Thus, in an extra like "a cup of coffee, 2,5 EUR", the nett price (without 10 % VAT) would be 2.04545454545.
- Add an extra service to the bill with more than one unit: "3 cups of coffee, 2,25 EUR each".
- The invoice shows as the total amount 6,77 EUR, instead of 6,75.

**Comment by alibarthi** [comment]
This change should solve it: https://github.com/WoollyinWalesIT/jomres/commit/f894bd603bf122dac700c70703784ecf0aebcc2a
