### ISSUE TITLE
Beds24 v2 testing

### ISSUE THREAD

**Issue by gavaudun** [WoollyinWalesIT/jomres#151]
Hi Vince,
In order to test Beds24 v2 on an existing configuration, I uninstalled Beds24 plugin and installed API, Webhook and Beds24v2 on my development site, but I didn't get very far : clicking on Settings -> Channel Management, I got this message ::
Sorry! An error occured while trying to process this function. It has been reported for you and we will look into it.
I am using Protostar (Bootstrap2) ; would that be the reason ?
Eric

**Comment by jomres** [comment]
Hi,

> I am using Protostar (Bootstrap2) ; would that be the reason ?

Yes,  that's probably it.

https://www.jomres.net/support/blog/47-new-beds24-v2-plugin-alpha-testing

> This plugin only offers Bootstrap 3 template files, so you will need to be running an installation that supports them. You can use one of the Jomres Quickstarts if you aren't already doing so.

However, to be sure check the error logs, this tutorial shows you how to view the log files.

http://www.jomres.net/manual/site-managers-guide/346-red-screen-reported-administrator

**Comment by gavaudun** [comment]
Hi Vince,

I suggest you have a look at the log files yourself on dev.domaine-de-gavaudun.com (Aladar has all access codes): the problem does not seem to be related to Bootstrap2.

In the core.application.log, I see some errors linked to Beds24 appearing on April 7, date at which Aladar first tested my development site (Error logged Requested room variable is empty after apparent successful insertion, likely the Jomres Rooms and Beds24 Room types association is wrong ...).  
But they may just be due to the fact that some Jomres properties are not defined in my Beds24 test environment.  These error messages stop at the time I loaded the Beds24v2 plugin and there is nothing in the Beds24 log after that time.

According to the Log Channel, I removed Beds24 plugin at 2017-04-14 18:04:59 and I subsequently added api_core, webhooks_core, api_feature_beds24 and beds24v2 plugins.  All was done by 2017-04-14 18:07:32 

From there, I have other error messages linked to Beds24v2, when I tried to access Settings->Channel Management : Error logged map_jomres_properties_to_beds24_properties Manager has no properties <a href="http://dev.domaine-de-gavaudun.com/index.php?option=com_jomres&Itemid=107%E2%8C%A9=fr&tmpl=jomres&task=show_logfile&logfile=sONDRyhcAvzXbfmudpigTYGHOqAIWk.html"> ...

I would suspect it comes from the fact I am trying to install Beds24v2 over a previously existing Beds24 installation (which really was the purpose of the test).

The html logfiles have the following content :

http://dev.domaine-de-gavaudun.com:80/fr/village-gites?tmpl=jomres&task=beds24v2
2017-04-14 18:25:54 109.13.181.181 Message: map_jomres_properties_to_beds24_properties Manager has no properties
File: /homepages/43/d221936205/htdocs/_joomla_dev/jomres/core-plugins/beds24v2/beds24v2_properties.class.php

Line: 156
jomres.php on line 825
jomres.php on line 58

Trace: #0 /homepages/43/d221936205/htdocs/_joomla_dev/jomres/core-plugins/beds24v2/j06002beds24v2_display_properties.class.php(53): beds24v2_properties->map_jomres_properties_to_beds24_properties()
#1 /homepages/43/d221936205/htdocs/_joomla_dev/jomres/libraries/jomres/classes/mcHandler.class.php(195): j06002beds24v2_display_properties->__construct(NULL)
#2 /homepages/43/d221936205/htdocs/_joomla_dev/jomres/core-plugins/beds24v2/j06002beds24v2.class.php(58): mcHandler->specificEvent('06002', 'beds24v2_displa...')
#3 /homepages/43/d221936205/htdocs/_joomla_dev/jomres/libraries/jomres/classes/mcHandler.class.php(195): j06002beds24v2->__construct(NULL)
#4 /homepages/43/d221936205/htdocs/_joomla_dev/jomres/jomres.php(720): mcHandler->specificEvent('06002', 'beds24v2')
#5 /homepages/43/d221936205/htdocs/_joomla_dev/components/com_jomres/jomres.php(58): require_once('/homepages/43/d...')
#6 /homepages/43/d221936205/htdocs/_joomla_dev/libraries/cms/component/helper.php(405): require_once('/homepages/43/d...')
#7 /homepages/43/d221936205/htdocs/_joomla_dev/libraries/cms/component/helper.php(380): JComponentHelper::executeComponent('/homepages/43/d...')
#8 /homepages/43/d221936205/htdocs/_joomla_dev/libraries/cms/application/site.php(191): JComponentHelper::renderComponent('com_jomres')
#9 /homepages/43/d221936205/htdocs/_joomla_dev/libraries/cms/application/site.php(230): JApplicationSite->dispatch()
#10 /homepages/43/d221936205/htdocs/_joomla_dev/libraries/cms/application/cms.php(261): JApplicationSite->doExecute()
#11 /homepages/43/d221936205/htdocs/_joomla_dev/index.php(49): JApplicationCms->execute()
#12 {main}

**Comment by jomres** [comment]
> 2017-04-14 18:25:54 109.13.181.181 Message: map_jomres_properties_to_beds24_properties Manager has no properties

The implication here is that Jomres hasn't been able to find any properties in the beds24 > Jomres table. Can you confirm that you've visited the Settings > Channel Management (Beds24) page  and linked some properties?

**Comment by gavaudun** [comment]
Well, I cannot re-link Beds24 properties to Jomres Properties since I cannot access Settings -> Channel Management ...
Tables _jomres_beds24_property_uid_api_key_xref and _jomres_beds24_room_type_xref are populated with the xrefs that were defined with the original Beds24 plugin.
Tables _jomres_beds24_property_uid_xref and _jomres_beds24_rest_api_key_xref are empty.

**Comment by jomres** [comment]
What happens when you try to do that? Can't you see the menu item?

**Comment by gavaudun** [comment]
clicking on Settings -> Channel Management, I just got this message (nothing else is displayed) ::
Sorry! An error occured while trying to process this function. It has been reported for you and we will look into it.
Hence your idea to look at the log files.
Please note this brings us back to my original post (we are cycling).

**Comment by jomres** [comment]
Did you first resolve the fact that you're running on a BS2 template? As said before, the V2 plugin only supplies BS3 templates, so that could be the cause. You didn't confirm if you'd done that. Without them, there's no way to output anything.

**Comment by JuanGarciaG** [comment]
Vince, the problem that Gavaudun says, I think it's the same problem that I mentioned in the plugin analysis ticket. You can link the property through the Superproperty Manager but you get error reading the rooms. However if you try to link the property through the Property Manager (which is the correct thing) it is impossible.

It is urgent to correct this error, since the current Beds24 plugin gives too many synchronization problems and until the problem of Beds24 V2 is not solved, the new plugin can not be tested.

**Comment by jomres** [comment]
Ok, I have a nice stack of v2 feedback to work through this week, so that'll be the first thing I look at, then.

**Comment by gavaudun** [comment]
Hi Vince,
I am using Protostar (using Bootstrap2), so if Beds24 plugin only supports Bootstrap 3, I will not be able to do any testing, sorry for that, but it is not the error reported in the log files ...
Eric
