### ISSUE TITLE
Feature request: Variation of Jomres REST API method for adding booking to facilitate legacy migration

### ISSUE THREAD

**Issue by catalansurfer** [WoollyinWalesIT/jomres#152]
The following variations to Jomres REST API method for adding new booking  would simplify a lot the migration from legacy booking system ->Jomres

> 1)accepting room type instead of room number, Jomres already works in that way in a frontend reception booking, so you must have some function/method already doing it, that you could cut and paste.

> 2)set username in booking to be created as the username passed as parameter in POST

**Comment by natanzi** [comment]
interested for this feature request...
booking api

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/feature-requests/p/variation-of-jomres-rest-api-method-for-adding-booking
