### ISSUE TITLE
Beds24 - Jomres Channel

### ISSUE THREAD

**Issue by iurirosa** [WoollyinWalesIT/jomres#155]
Just an idea, please consider.

How about making Beds24 update/create rates on Jomres, Jomres could be treated as a "channel", this would be handy when you have multiple jomres sites, you could update them all using sub accounts on Beds24.

**Comment by jomres** [comment]
One thing that I will work on, now that we have tariff classes (this is in the next version), is the ability to update tariffs through the REST API ( it's on my Todo list on Trello ) they, or any other REST API client that is authorised, will be able to update tariffs remotely. 

With that feature, then Beds24 will be able to update multiple Jomres installations, which would require some changes at their end, both in how they update Jomres, and how they store multiple endpoints in their Jomres settings page ( which I believe Mark is planning to do).


Be warned, we're holding off the next version as, whilst it's currently  marked as 9.8.30, there are a significant number of changes internally to Jomres and this version is likely to be bumped to 9.9.x. This will allow us to make sure that Jomres is Joomla 3.7 ready, and test these changes. I tested 3.7 when it was Release Candidate and it all worked fine, but we've seen in the past that there can be big changes between RC and Stable releases which can cause problems.
