### ISSUE TITLE
import Hotel Logo in jomres

### ISSUE THREAD

**Issue by natanzi** [WoollyinWalesIT/jomres#157]
Dear Vince ,
please provide a section for import Hotel logo and hotel signature in jomres/
for using in Email Template or bill (PDF) and...
Now we should put in Host and make fix link in email template or PDF Bill

BR

**Comment by alibarthi** [comment]
So basically we should add some separate header and footer email templates that can be edited in any way owners want, then we`ll wrap all sent emails automatically with these header/footer templates. Does this sound about right?

**Comment by natanzi** [comment]
Yes aladar,
I thin this is Good idea

**Comment by natanzi** [comment]
Dear Vince,
would you please  add this in next version? for example in Property define process.

**Comment by JuanGarciaG** [comment]
This idea sounds really good

**Comment by mreza9** [comment]
+1

**Comment by natanzi** [comment]
Dear Vince,
Would you please write your idea

**Comment by jomres** [comment]
9.9.18 will have a logo uploader plugin.
