### ISSUE TITLE
Featured listing in search results like google adds

### ISSUE THREAD

**Issue by cakipoduka** [WoollyinWalesIT/jomres#158]
Hello
It would be great if we could have option to charge property owners ads  that can appear above search results on All listing page. 
There are some sites that have 100 or 1000's of property's and property owners would like to pay for top postion in search results, something like
![adds](https://cloud.githubusercontent.com/assets/28188940/25555342/282d0d58-2ce4-11e7-9a2c-4d0003710ebe.png)

Any chance to see this in jomres?

**Comment by Nikos-c** [comment]
Plugin is already there

**"Featured Listings"**
