### ISSUE TITLE
Email Admin when Jomres has a New Update 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#16]
https://www.jomres.net/forum/Feature-requests/25368-email-admin-when-jomres-has-a-new-update

I think it would be nice if Jomres could send the Admin an email when a new update for Jomres is ready instead of finding a new update each time you login to Jomres.

I think Joomla now sends an email to the Admin when a new update is ready.

**Comment by paul2011** [comment]
Thank You!
