### ISSUE TITLE
Selection of only one date for daily tours - feature request

### ISSUE THREAD

**Issue by zheeka** [WoollyinWalesIT/jomres#162]
Hello,
it would be great if you modified the search and booking engine for daily tours in a way that only one date can be selected. Daily tours begin and end on the same date, so a check-in/check-out date picker is actually incorrect and can confuse people.
Thnx!

**Comment by jomres** [comment]
IMO this is a property specific setting, and in Property Configuration you can choose to disable the Departure date. Some properties may require both pickers, therefore it makes sense for this to be something that's done at the property level, not the site or automatic code level.
