### ISSUE TITLE
Problem with update from 9.8.27 to 9.9

### ISSUE THREAD

**Issue by jparas1966** [WoollyinWalesIT/jomres#164]
Hello
I have multilanguage joomla site en and gr.
When I update to 9.9, greek bookings name, surname etc. shows ?????
thanks
John

**Comment by jomres** [comment]
Check your database collation please. What is yours set to?

**Comment by jparas1966** [comment]
utf8_general_ci 
With jomres 9.8.27 works ok

**Comment by jparas1966** [comment]
I change collation utf8mb4_general_ci and working 
thanks
