### ISSUE TITLE
9.9.1  Hide jrportal but List Properties - Set as current allows (limited) access

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#166]
joomla 3.7.2, jormres 9.9.1

Using Access Control I have disabled the cpanel (= Nobody)

If I select Properties-List Properties and select to Set as current a different property, I am shown a white screen with the new *Select widgets box visible.

There are ticks in Timeline and Percentage Rooms Booked but the page content is not displayed.

Therefore if I wish to hide the cpanel and only show the dashboard, I would expect to be landing on the dashboard.

Ally

**Comment by alibarthi** [comment]
I`ve added the cpanel task to excluded tasks in access control: https://github.com/WoollyinWalesIT/jomres/commit/e822e753edb4d62a5f13dbde59c989635752c19f

if you want to change the default landing page in the frontend cpanel, edit jomres.php at the bottom, search for 'cpanel', approx line 373, change that to 'dashboard' if you want.
