### ISSUE TITLE
Problem 9.9.3 with "confirmbooking"

### ISSUE THREAD

**Issue by JuanGarciaG** [WoollyinWalesIT/jomres#170]
When the client clicks on the link of the email confirming the reservation request, there is a link to confirm or make the payment of the booking request approved by the establishment. This link does not work.

It gives an error:

"Error: Property uid not set."
"File: ... / libraries / jomres / classes / basic_room_details.class.php
Line: 42

Does anyone else think of it?

**Comment by jomres** [comment]
Please raise a support ticket Juan. Nobody else is reporting this, but I need to ask questions that are not appropriate for a public forum.
