### ISSUE TITLE
Timeline should remember selection

### ISSUE THREAD

**Issue by HDelfs** [WoollyinWalesIT/jomres#171]
Hi Vince,

would be great to have the selection of the time to be rembered by the timeline. ( Day / Week / 2 weeks / Month / Year )
e.g. if I select 'Month' as as timeline view and I return to the timeline after f.e. editing a booking it still should be 'Month' selected. Timeline shows always it's defaults when opened.
Another solution could be a setting in the options.

**Comment by jomres** [comment]
There doesn't seem to be much demand for this.
