### ISSUE TITLE
Feature request: mail notifications, send copy to administrator

### ISSUE THREAD

**Issue by contactovisual** [WoollyinWalesIT/jomres#173]
In multiple properties websites, the administrator might want to track every reservation. A simple solution wold be to have the option in the Jomres settings for email sending to/from property with something like this:

- Send copy to administrator:  Yes/No

And than, if Yes, put the administrator email address in CC

Nelson / Contacto Visual

**Comment by ReneCB** [comment]
I would also appreciate this function. Even nicer would be a configuration matrix for all email template types where you could check who should receive the respective email (guest, hotel, admin). This way the sent email copy settings would also be "update proof".

**Comment by jomres** [comment]
This feature has been in Jomres for a while. Booking emails can be copied to admins.
