### ISSUE TITLE
Problem with Paypal - Commissions and Subscriptions

### ISSUE THREAD

**Issue by JuanGarciaG** [WoollyinWalesIT/jomres#178]
When you try to pay Commission or Subscription invoices through Paypal the System gives the error:

"Error, no gateways have been configured."

I have tested the payment with normal reservations through Paypal and there are no problems.

**Comment by jomres** [comment]
Has site admin configured his pp details in the admin area?

**Comment by JuanGarciaG** [comment]
If pp means Paypal, yes, it is set up. I guess it should also work with Wire Transfer, it is also configured but still giving the same error.

**Comment by JuanGarciaG** [comment]
I updated to version 9.9.5

He still gives the same error.

"Error, no gateways have been configured."

I've tried uninstalling the "je overview" plugin for if it was the culprit but it has not been fixed either.

**Comment by jomres** [comment]
Juan,

Please raise a support ticket, I can't recreate this locally so it must be specific to your site so we'll pursue it there.
