### ISSUE TITLE
Possibility of improvement in edition micromanage rates

### ISSUE THREAD

**Issue by JuanGarciaG** [WoollyinWalesIT/jomres#179]
You can now add prices in three different ways in Micromanage.

1.- Manually
2.- By date range
3.- By day of the week

My suggestion is to use a mixed method that allows to set prices per day of the week but indicating the time interval on which we want to work.

Eg "Set € 100 for Mondays between 12/05/2017 and 08/30/2017"

Taking into account the price difference between seasons, I think this would make it much easier to create and modify rates.

**Comment by jomres** [comment]
Im not convinced that many people would want this, so will wait to see if anybody else mentions it

**Comment by JuanGarciaG** [comment]
Okay, Vince. I hope there are people who see it interesting. Now when you use the option of Days of the Week you change all the time covered by the rate (a full year, two or the ones you have configured), there are always holidays, high and low seasons, etc.

At least in my case I do not usually use because of that reason.

**Comment by natanzi** [comment]
I read this topic
One thing that more important is convert this plugin to Api mode after that Vince can develop more option for this huge plugin

**Comment by picturesque** [comment]
I'd use this. Certain weekends are higher rates and doing it manually for a range of dates for multiple properties is time consuming.

**Comment by jomres** [comment]
I hate you lot.

**Comment by jomres** [comment]
Folks, advanced micromanage plugin has been updated, update it through the plugin manager as normal.

http://snippets.jomres.net/2017-07-23_i7z3x.png

Works for both prices and minimum days settings ( made sense to make that work too as the inputs are so closely linked)

Layout isn't perfect, but in my tests it seems functional in large viewports. I don't know if you even use small screens for setting tariffs, so for now this is only available in large viewports and Bootstrap 3 templates.

Juan, thanks for your contribution, I wasn't able to use it in the end but it helped to confirm that what I had in mind was what you are already doing so at least I know that this is what you guys want. Cheers mate.

**Comment by jomres** [comment]
Folks, can I have some feedback from you as to whether or not this was what you had in mind?

If I don't get feedback then I assume that either the feature wasn't really wanted, or it was done in a way that you didn't want. Without feedback there's no motivation to produce more feature requests.

**Comment by JuanGarciaG** [comment]
It's perfect Vince, that's what it takes. 👍 

Besides it is made with class, not like my homemade fudge.  :- D

Do not be discouraged, you have many improvements to make.
