### ISSUE TITLE
Feature request: Automatic Ban user that make fake booking

### ISSUE THREAD

**Issue by natanzi** [WoollyinWalesIT/jomres#180]
Dear Vince ,
If somebody Cancel booking for 3 or 4 time this is maybe affect hotel business! specially in pick time , in additional when Jomres connected to remote site and other booking website I think we need a method for Ban user that make fake booking so I suggest add plugin for automatic ban user that make fake Booking.

Best Regard

**Comment by alibarthi** [comment]
You can blacklist a guest (list guests->edit, set blacklisted to yes). If a guest is blacklisted, he can`t make bookings anymore, instead he`ll see the contact form.

**Comment by natanzi** [comment]
yes of course but : 
Jomres is Online Booking system and when user make booking anymore , its better to move it to blacklist automatically ,this process can be done manually for few user not all users .consider in online system you don't know how many users go on website and make booking.

**Comment by natanzi** [comment]
Also this mechanism use to be in Online taxi booking such as Uber,snap and ....

**Comment by jomres** [comment]
Use to be? You mean they no longer use the feature?

**Comment by alibarthi** [comment]
Well, deposits are charged at booking time so that cancellations won`t happen that often. The refund is manually processed by the property manager, so depending on the number of days till arrival, you can issue a refund or not.
We`ll consider adding guest groups and there probably have some settings to blacklist users if more than N cancellations in N months, but this is not going to happen in the very near future.

**Comment by natanzi** [comment]
good job alibarthi

**Comment by natanzi** [comment]
@jomres I hear something about consumer complain about that feature in some country.
Thank you vince for your attention.

**Comment by jomres** [comment]
Just giving this some thought. Are guest cancellations a problem for you, Natanzi? Does it happen often?

**Comment by natanzi** [comment]
Yes guest cancellations is normal and most of the time they want change date or maybe cancel.
and also consider if agent wanna to get frequently reserve and cancel so maybe affect the Hotel business.

**Comment by natanzi** [comment]
Vince please consider API for cancelation process also...
this is Very Important option (not feature request)...with API cancellation everybody can make custom plugin an runing scenarios for Cancel

**Comment by jomres** [comment]
The reason I ask, is I'm trying to understand if this is vital for your business as you're getting fraudulent booking that are then being cancelled as a way to disrupt your business, or if it's just a "nice to have" feature.

If it's the former, then I would have expected the requirement for bookers to pay a deposit would help to deter people like that.

**Comment by jomres** [comment]
Ok, it seems like this is a "nice to have" feature, rather than an "OMG I need this now" feature.

**Comment by natanzi** [comment]
Much appreciate

**Comment by jomres** [comment]
Natanzi,

By my comment, I meant that it's not really mission critical for you, instead it'd be nice to have but it's not that important. Did I understand this correctly?

You know me by now, I'm always looking for cool features to add, however I don't want to add an extra layer of complexity if it's not really needed. My job at this point is to understand whether or not a feature like this would significantly improve your business, or if you thought "Hey, this would be cool, let's ask Vince". I wouldn't dream of deterring you from asking for features, but I want to understand where in the scale of 1 -> nice to have to 10 -> OMG I need it now, where does this feature lie for you?

**Comment by natanzi** [comment]
Dear Vince , 
I thinks so this is grate feature for somebody used jomres for few properties, 
yes ,this is not critical But if it is better (we can skip it now)
my point of view jomres is good Infrastructure and basically need something like this for users management ,
I accepted your comment and know you have big mission with less time.

Thank you
