### ISSUE TITLE
Update from 9.8.2 to 9.9.5

### ISSUE THREAD

**Issue by Igcorreia** [WoollyinWalesIT/jomres#182]
After installing the update I get this error in all pages in Joomla 3.7.2 front and backoffice.

Error, class javascript_cache doesn't exist.
File /home/vhosts/***/***/jomres/libraries/jomres/classes/mcHandler.class.php Line 175 Function __construct
File /home/vhosts/***/***/jomres/admin.php Line 87 Function triggerEvent
File /home/vhosts/***/***/administrator/components/com_jomres/jomres.php Line 30 Function require_once

Upgrade was done via WEB INSTALL because update didn't worked.

**Comment by Igcorreia** [comment]
The reference in Github of such class is here: https://github.com/WoollyinWalesIT/jomres/search?utf8=%E2%9C%93&q=javascript_cache&type=

**Comment by tevez15** [comment]
Extensions -> manage -> install -> install from web

Search by "Jomres", and install. Follow the steps (dont drop the tables).

Done.

**Comment by Igcorreia** [comment]
Deu??

Sent from my iPhone

On 20 Jun 2017, at 17:58, Diogo Esteves <notifications@github.com<mailto:notifications@github.com>> wrote:


Extensions -> manage -> install -> install from web

Search by "Jomres", and install. Follow the steps (dont drop the tables).

Done.

-

**Comment by tevez15** [comment]
Deu, mas depois fiz alguma coisa e voltou ao mesmo.

**Comment by jomres** [comment]
Igcorreia advice was correct, did you try it?

**Comment by tevez15** [comment]
We work together, so no! I try, and work, but I do something after, and the problem comeback again

**Comment by Igcorreia** [comment]
@jomres it does not work, it corrects for a second and than after 1 refresh it breaks.

**Comment by jomres** [comment]
As you can see 

https://github.com/WoollyinWalesIT/jomres/blob/master/libraries/jomres/classes/mcHandler.class.php

doesn't have a reference to javascript cache on L175. I have also scanned the entire Jomres and plugin codebase for references to the old class javascript_cache and there's nothing in either set.

The most likely cause is that you have customised versions of some Jomres scripts which contain old code. That's outside of my control I'm afraid as I wouldn't know what you have customised.

**Comment by Igcorreia** [comment]
@jomres we are installing a new version and we will add our custom code slowly. Let you know if it fixes. @tevez15 let's see how it goes :)

**Comment by tevez15** [comment]
OK, I can solved. (Probably)
I continue with my proporties, my blocks, but for some reason I can't use my overrides correctly.

Other problem, is the loading time. I give many time outs.

**Comment by tevez15** [comment]
I can't list my properties, the loading is so long. The server give time out
