### ISSUE TITLE
javascript_cache.class.php is automatically removed 

### ISSUE THREAD

**Issue by tevez15** [WoollyinWalesIT/jomres#183]
Hi,

When I install a new version, since Jomres 9.9.0, I have this error:
`Error, class javascript_cache doesn't exist.
File C:\wamp64\www\flat\jomres\libraries\jomres\classes\mcHandler.class.php Line 175 Function __construct
File C:\wamp64\www\flat\jomres\framework.php Line 127 Function triggerEvent
File C:\wamp64\www\flat\jomres\framework.php Line 34 Function load_jomres_environment`

So, I upload the file javascript_cache.class.php, from other versions, and I can open jomres. But when I reload the page, and come back to the folder, the file no longer exist, is bean deleted.

I solve this? Thank you?

**Comment by jomres** [comment]
Not a bug, the system is behaving as expected because that file is no longer required by Jomres Core.

**Comment by tevez15** [comment]
And why he give me the error?

**Comment by jomres** [comment]
Because you have customised files that are calling that class.

**Comment by tevez15** [comment]
Ok, thank you very much.
