### ISSUE TITLE
Problem with search module and confirmation

### ISSUE THREAD

**Issue by tevez15** [WoollyinWalesIT/jomres#184]
Hi,

When you watching the details of reservation, you have an option to change your details. When you in, and click in the button, nothing happens.
In my case, I have a search form, with the same ID on "Town" select(search mod) and input (form reservation).

On jomres.js file, I change the line 883:
`var town = jomresJquery.trim(jomresJquery('#bookingform_address #town').val());`

 And work.

I don't know if it happens in more places of jomres.

**Comment by jomres** [comment]
Hi,

On exactly which page is this? The booking form? The line you've removed is for checking that the town address field has been completed. If you're happy for that field not to be checked when users submit bookings, then that's great.
