### ISSUE TITLE
QR code doesn't work with most scanners when non standard chars in string

### ISSUE THREAD

**Issue by fonnysmets** [WoollyinWalesIT/jomres#187]
Set country to Belgium -> scan works 
Set country to België -> scan gives error.

Tried the demo on http://phpqrcode.sourceforge.net/index.php#demo and got the same result.

Maybe this solution could help
https://stackoverflow.com/questions/1612062/unicode-encoding-and-decoding-issues-in-qrcode

**Comment by alibarthi** [comment]
We`ve updated the qrcode library for the next version. Let me know if this is still an issue after jomres 9.9.9 is out. You`ll have to delete the /jomres/temp/qr_code dir first so new codes will be generated.
