### ISSUE TITLE
fault in Widget Manager News plugin

### ISSUE THREAD

**Issue by mreza9** [WoollyinWalesIT/jomres#192]
Dear Vince,
in /jomres/core-plugins/widget_manager_news/j16000widget_manager_news.class.php
line 72: $tmpl->readTemplatesFromInput( 'list_news_articles.html' );

'list_news_articles.html' file does not exist. Please add it. the user can not add news...

pat-Warning: Path to template is not set.
Related topublic_html/jomres/core-plugins/widget_manager_news/templates/bootstrap
Backtrace of files
j16000widget_manager_news.class.php on line 76
admin.php on line 173
jomres.php on line 30
administrator.php on line 98
administrator.php on line 152
cms.php on line 261

Regards,

**Comment by jomres** [comment]
Thanks for letting me know, the plugin has been updated.
