### ISSUE TITLE
some errors after install jomres 9.9.8

### ISSUE THREAD

**Issue by mreza9** [WoollyinWalesIT/jomres#197]
Dear vince, hi
There are some errors after install jomres 9.9.8 as follow:

Error, class jomres_video_tutorials doesn't exist.
File /home/public_html/administrator/components/com_jomres/jomres.php Line 30 Function require_once
File /home/public_html/libraries/cms/component/helper.php Line 405 Function require_once
File /home/public_html/libraries/cms/component/helper.php Line 380 Function executeComponent

**Comment by jomres** [comment]
Try reinstalling thru the joomla indtall from web feature, it lookks like not all files were extracted

**Comment by jomres** [comment]
Did that work for you?

**Comment by mreza9** [comment]
Unfortunately No, I installed manually by jomres_webinstall.php, and automatically, again.

**Comment by jomres** [comment]
Did you forget to finish the sentence? :D

**Comment by mreza9** [comment]
Error, class jomres_video_tutorials doesn't exist.
File /home/public_html/jomres/libraries/jomres/classes/mcHandler.class.php Line 175 Function __construct
File /home/public_html/jomres/jomres.php Line 268 Function triggerEvent
File /home/public_html/components/com_jomres/jomres.php Line 58 Function require_once

**Comment by jomres** [comment]
Please raise a ticket with the server's login details and I'll look into it for you.
