### ISSUE TITLE
Slideshow Corner flash for Marketing Info

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#20]
https://www.jomres.net/forum/Feature-requests/24171-slideshow-corner-flash-for-marketing-info

One feature which would be useful for marketing purposes would be an editable cornerflash for the image slider (example below).

This could be used to display special offers such as 'free car hire', 10%,15%, 20% discount, Limited time offer, etc. Ideally these offers could be set to expire after a specified number of days.

Would anyone else find this useful?

**Comment by natanzi** [comment]
Excellent...
very useful if Designed in API mode

**Comment by jomres** [comment]
Closed due to lack of support.
