### ISSUE TITLE
Main menu location chooser

### ISSUE THREAD

**Issue by creagmhor** [WoollyinWalesIT/jomres#201]
Hi,
I am trying to create a main menu option so that visitors can choose a location within our site to visit. 

I have managed to add a menu item using the asamodule Location Map Regions plugin but this shows regions and  we only have perhaps 1 region so it would be advantageous if there was a similar module that only showed cities or towns. I have tried to change the argument to towns but it does not work.

Ideally the module would link to a dedicated town or city page within the CMS instead of pointing to properties within that location only

**Comment by creagmhor** [comment]
We have exchanged tickets on this feature and I accept that the CMS is not an option for creating location pages. The development of location station as per our ticket exchanges would be the best option provided that the pages are optimised and allow page editing and shortcodes/modules insertion

**Comment by jomres** [comment]
Closed due to lack of support for the feature.
