### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#207]
If I List Bookings and Amend Reservation, I can see **Booking number 9876543 - Guest Name** at the top of the page.

But if I Cancel booking, Add service to bill or Add note, the **Booking number 9876543 - Guest Name** is not shown.

(other pages viewed from the edit booking screen do show the booking and name details due to their purpose)

Can a future change be made to include these 2 items (tag & guest first & last name) so that when cancelling a booking, adding service or adding a note so that receptionist can be assured they are within the correct booking before committing to make changes.

Thank you

Ally

**Comment by JeromePayan** [comment]
Hey, this a good idea.
Can we be able to undo the cancellation ! 

Merci

Jerome

**Comment by natanzi** [comment]
+ 1 good

**Comment by jomres** [comment]
> Can a future change be made to include these 2 items (tag & guest first & last name) so that when cancelling a booking, adding service or adding a note so that receptionist can be assured they are within the correct booking before committing to make changes.
> 

Done.
