### ISSUE TITLE
guesttypes 9.9.9

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#208]
The core plugin guest_types appears to have some language missing.

If you view a property guest type page ?task=listcustomertypes there are the following new items 
_JOMRES_GUESTTYPES_INTRO 
_JOMRES_GUESTTYPES_INSTRUCTIONS

If you look in any language file, of the plugin or the properties, they are not defined.

Sorry ! ;)

Ally

**Comment by rrmdp** [comment]
Ally I see the constants being defined at core-plugins\guest_types\language\en-GB.php , are you sure you have the latests plugin version ?

**Comment by jomres** [comment]
Cheers matey. Plugin has been updated if you'd like to re-download and confirm it's resolved.

**Comment by allynat** [comment]
Hi Rod

Well I have updated that plugin. Yes its the 9.9.9 version.

I have checked & double checked it

The bootstrap3 template in the plugin is being used and the language file is not containing those constants

Ally

**Comment by jomres** [comment]
Try re-installing the plugin, there was a minute's delay between me uploading the info file and the actual lang file, perhaps you updated during that time.

**Comment by allynat** [comment]
Bingo !

Thanks very much.

The upgrade went like a dream.

Thanks so much for this.

Ally
