### ISSUE TITLE
Type of selected payment method on invoices 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#21]
https://www.jomres.net/forum/Feature-requests/23971-type-of-selected-payment-method-on-invoices

I would appreciate a note on the generated invoices indicating the payment method selected by the guest. For example something like:
Payment method: Cheque
Payment method: Paypal

I think it's useful information for the property owner in case several payment options are offered.

**Comment by villykou** [comment]
Not all members of the forum have an account here, so they cannot vote for feature requests.
Since there are several payment methods, it`s a must to have a note in the invoice. Especially in List Invoices view, of the property manager.

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Feature added in https://github.com/WoollyinWalesIT/jomres/commit/9d2f60120c18b3c6f48a6411237a1f5f10bfb19c

The Stripe gateway has been updated, that'll be released with 9.9.16. I haven't done the Paypal gateway yet as that requires being on a live server to thoroughly test things so that'll be done sometime after .16 is released.
