### ISSUE TITLE
Offers and Lastminute Module

### ISSUE THREAD

**Issue by giancarlo1970** [WoollyinWalesIT/jomres#216]
It would be very useful to add a joomla module that shows the offers/lastminute of the properties
thanks

**Comment by natanzi** [comment]
Its good feature but should put in jomres as a class

**Comment by ReneCB** [comment]
+1

**Comment by jomres** [comment]
A plugin was added recently that allows you to list properties that offer last minute discounts. I wont close this yet as I want to find a way of displaying those discounts on the list properties pages.

**Comment by ReneCB** [comment]
P.S.: 
Vince, maybe you can discuss this topic also with Rodrigo - it would be great if his plugin "jpd_jomres_discounts" would be compatible (if those discounts would be considered in the calculation, too).

**Comment by JeromePayan** [comment]
Just to share with you 

While Waiting for this update... i added in Jomres "Translate lang string" after night or nights  this message 

night (click on the Book Now button to calculate the possible promotion)
nights (click on the Book Now button to calculate the possible promotion)
