### ISSUE TITLE
Prelimanary black bookings

### ISSUE THREAD

**Issue by RethaJac** [WoollyinWalesIT/jomres#217]
I am not sure if there is something similar in use already and if not it could be a feature request perhaps.

I would like the ability to mark black bookings as preliminary/unpaid bookings (they could show on the calendar as a different colour) or the confirmed booking (red). 

Thank you.

**Comment by jomres** [comment]
It sounds like you're using black bookings for reasons other than the intended one. If you want to show a booking as paid/not paid etc I would advise you to use either the full booking form, or the dashboard/timeline popup.
