### ISSUE TITLE
Remove selected dates from session with reset 

### ISSUE THREAD

**Issue by superdeluxxx** [WoollyinWalesIT/jomres#218]
If you use the search module on the home, resetting isn't clearing the selected dates. So it's not a resetting the filters as a user expect.

**Comment by alibarthi** [comment]
The search module on the homepage doesn`t have a reset button...are you maybe referring to ajax search composite plugin?

**Comment by superdeluxxx** [comment]
Yes correct

**Comment by jomres** [comment]
Insufficient support for this change request.
