### ISSUE TITLE
Sort function for pictures in backend

### ISSUE THREAD

**Issue by SentenzaFree** [WoollyinWalesIT/jomres#223]
I find it would be better to add in backend the function for sorting and disabling/enabling of pictures of towns, properties, rooms, facilities etc.

**Comment by jomres** [comment]
I'm not going to add this. 

Rod at Jomres Plugins https://www.jomres-plugins.com/ has created an extended version of the media centre uploader called JPD Slideshow Enhancer which I highly recommend. It also allows you to add captions and tags and other whizzy stuff. Seriously, give it a look. While you're there check out his other plugins, there's lots of great things that might interest you.
