### ISSUE TITLE
Error in Authorisation URL (jomres 9.9.14)

### ISSUE THREAD

**Issue by mreza9** [WoollyinWalesIT/jomres#225]
Dear Vince
When using the implicit grant type flow by Authorisation URL, the below error has appeared:

Fatal error: require_once(): Failed opening required '/home/domaindotcom/public_html/jomres/core-minicomponents/../../api/oauth/server.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/domaindotcom/public_html/jomres/core-minicomponents/j06005oauth_authorise.class.php on line 61

**Comment by jomres** [comment]
Hi Mreza,

In j06005oauth_authorise.class.php at L61 change that line to 

require_once JOMRESPATH_BASE.'/api/oauth/server.php';

Does that fix it?

**Comment by mreza9** [comment]
yes, it does.
