### ISSUE TITLE
List Guests - Active Bookings

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#226]
If selecting to filter "Guests with active bookings" and there are records for past & future bookings for a guest that has been searched for by email address, then the expected behaviour is surely that only today & forwards records would show. 

But the current behaviour still shows the historic record.

I believe this may be to do with booked in - booked out not being used but am unable to prove it.

So if it is due to the book in & out, then it would be better to not base active bookings on historic bookings that didn't arrive (booked in/ booked out) to allow for receptionists to make the selection of Active or Past correctly.

**Comment by jomres** [comment]
The problem with this is that many users don't use the book in/out functionality therefore it's pointless. Sorry Ally.
