### ISSUE TITLE
Adjusting Google Map height

### ISSUE THREAD

**Issue by gavaudun** [WoollyinWalesIT/jomres#227]
The Site Configuration Google Map Option _JOMRES_MAP_HEIGHT does not seem to have any effect on the map displayed in the properties details.
The map height seems to be hard coded at line 69 of j06000show_property_map.class.php (this should be fairly easy to fix).
PROPERTY_MAP_ZOOM does work fine.
Eric

**Comment by alibarthi** [comment]
This change will solve it: https://github.com/WoollyinWalesIT/jomres/commit/99415a3d5d926fed6c439226a129c7ae41b118d0
