### ISSUE TITLE
Can not load BrowserConsoleHandler.php

### ISSUE THREAD

**Issue by mreza9** [WoollyinWalesIT/jomres#228]
hi,
There's an error in jomres 9.9.14 as follow:

Fatal error: Class 'Monolog\Handler\AbstractProcessingHandler' not found in /home/domaindotcom/public_html/jomres/vendor/monolog/monolog/src/Monolog/Handler/BrowserConsoleHandler.php on line 21

regards.

**Comment by jomres** [comment]
Please raise a ticket with the url, login details, ftp details and exact url you're seeing this on.

**Comment by mreza9** [comment]
Unfortunately. I can not raise a ticket, 
Please give me an email address.

Error message : 

Access Denied - Sucuri Website Firewall

If you are the site owner (or you manage this site), please whitelist your IP or if you think this block is an error please open a support ticket and make sure to include the block details (displayed in the box below), so we can assist you in troubleshooting the issue.

**Comment by jomres** [comment]
support@jomres.net

**Comment by mreza9** [comment]
thanks, I sent you an email ...

**Comment by jomres** [comment]
Mreza, was this resolved?

**Comment by mreza9** [comment]
Unfortunately No ...,
I reinstall jomres 9.9.14 completely... and applied changeset https://github.com/WoollyinWalesIT/jomres/commit/2f9d6f402cc4cb22366f4fa5adf98be31d953064#diff-771741c1f5e26c5ec1faed3228adf24b.
but did not work....

I raised a ticket (GOQ-313-18661). and sent you all of login and ftp information. you can test it.
The website's for test, so you can any edit in it Safely.

**Comment by jomres** [comment]
Don't forget that I'm still waiting for a reply to GOQ-313-18661 Mreza ;)

**Comment by mreza9** [comment]
I answered two days ago, but unfortunately, I could not be applied ticket, because of firewall problem :(.

**Comment by jomres** [comment]
Are you still seeing this in 9.9.15?

**Comment by mreza9** [comment]
No, The problem fixed in jomres 9.9.15.
thanks,...

**Comment by jomres** [comment]
https://www.youtube.com/watch?v=XmkPEy3Mur8
