### ISSUE TITLE
return ::1 instead of 127.0.0.1

### ISSUE THREAD

**Issue by mreza9** [WoollyinWalesIT/jomres#231]
Dear Vince, hi

In jomres\libraries\jomres\classes\jomres_temp_booking_handler.class.php after line 52, please add below code:

        if ($this->ip == '::1') {
            $this->ip = '127.0.0.1';

In localhost, the line '$this->ip = $_SERVER['REMOTE_ADDR'];' (line 52) return ::1 instead of 127.0.0.1;

Regards,

**Comment by jomres** [comment]
Closed in https://github.com/WoollyinWalesIT/jomres/commit/a1a7ed223c87596d64e012ad8ad013cd467c8e15
