### ISSUE TITLE
Channel manager report statistic 

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#233]
Hi

Could you think about having the possibility to edit reservation statistics by channel manager
(booking, expedia, airbnb ...).

I want to know how incomes from airbnb, booking...

Thanks
Jérôme

**Comment by ReneCB** [comment]
+1

**Comment by JeromePayan** [comment]
Please can you do this statistic available for :
- Site owner (entire site)
- Property manager in the report menu and the widget menu

Merci
