### ISSUE TITLE
Booking details via API or export

### ISSUE THREAD

**Issue by frederikbrudy** [WoollyinWalesIT/jomres#234]
For bookkeeping purposes, the exact details of all bookings are needed, however the current export of bookings via Bookings -> List Bookings -> csv as well as Invoices -> List Invoices -> csv only give the grand total of each booking. The API endpoints `listbooking `/`listinvoices ` endpoints only give this very limited information as well. 
More details for a booking via either the `listbooking` or any other endpoint would already be helpful rather than a complete csv export. 
In particular information like the number and type of guests, the number and type of rooms, and any booked extras for each booking.

**Comment by jomres** [comment]
The CMF REST API endpoints include guest numbers where available.
