### ISSUE TITLE
Allow customers to add their own custom fields - Feature Request

### ISSUE THREAD

**Issue by featurist-au** [WoollyinWalesIT/jomres#235]
Enable Individual vendors to choose which fields they need to show, in their booking forms.
eg: A tour operator may need to ask about dietary requirements, which other tour operators do not need to ask.

**Comment by natanzi** [comment]
+1 really necessary

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/historic-github-issues/p/allow-customers-to-add-their-own-custom-fields
