### ISSUE TITLE
edit invoice-send invoice with payment link- feature request

### ISSUE THREAD

**Issue by rboersma** [WoollyinWalesIT/jomres#239]
Dear reader,
When a booking from, for example, booking.com comes in through beds24, the jomres invoice only shows one line with the total amount. Since Beds24 gets all specified invoice lines from booking.com, it should be possible to sync these lines including the correct VAT code with jomres invoice. This way one could send the Jomres invoice directly to the Booking.com customer, instead of manually sending an invoice. If for good reasons this is not possible, then create an edit invoice, so we can edit the invoice and then send it directly to the booking.com customer.
Also i;d like to have a payment link using the configured gateway in Jomres to be send with the invoice, so the customer can easily use the link to pay. Instead of using his IBAN to manuale transfer the amount. When payed the invoice status should be set to DEPOSIT (when only the deposit is payed) and PAYED. So status DEPOSIT should be added.

**Comment by jomres** [comment]
Closed due to lack of support for the feature.
