### ISSUE TITLE
waiting list 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#24]
https://www.jomres.net/forum/Feature-requests/24415-waiting-list

Dear Vince;
At some times a reservation request must be denied because the hotel is fully booked. However, with enough lead time, interested guests may be put on a wait listing list for the requested dates. Hotels experiencing high-volume reservations may satisfy excess demand through this technique.
We should be Help the guest to find alternative dates if no rooms are available.
I suggest add waiting list to jomres.

**Comment by natanzi** [comment]
+1

**Comment by jomres** [comment]
Not enough support for this feature. Closed.
