### ISSUE TITLE
Clone Property Clarification required

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#241]
If an existing property (A) is similar to a proposed new property (B), then a manager / developer may be inclined to clone (A).

They may also be inclined to set up a unique property type for (B) and also a room type for good measure.

When property (B) detail is then edited in the front end, the property type will always be that belonging to property (A) and there is a friendly warning displayed to state that rooms, tariffs & property settings will be deleted.

Therefore I believe it would be prudent to state that Clone Property can only be used to duplicate an existing property that will thereafter use the same property and room type.

I have searched the manual, forum and plugin info but cannot find any advice displayed to aid understanding.

This may save people wasting time & reduce frustration of people using Property Types to customise their templates.

Hope this may help someone.

Ally

**Comment by jomres** [comment]
Notes updated Ally.
