### ISSUE TITLE
Input filtering term in forum search causes error

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#243]
Tried to search the forum to assist a poster regarding input filtering.

I got bombed out to:

https://www.jomres.net/forum/search?query=input%20filtering&childforums=1

and showing the screenshot attached.

<img width="1041" alt="screen shot 2561-01-05 at 18 49 46" src="https://user-images.githubusercontent.com/23444544/34608385-b081ed8c-f24a-11e7-83d1-f6d6172faaac.png">

Ally

**Comment by jomres** [comment]
I suffered the same thing when searching the manual, Ally. Unfortunately it's a valid signature to block so whilst I'd like to whitelist it, I daren't.

**Comment by allynat** [comment]
:) No worries, glad you know about it.

Cheers

Ally

**Comment by jomres** [comment]
Yeah, it's a bit of a pig. 

The search generally just results in this page http://www.jomres.net/manual/site-managers-guide/35-control-panel/main/site-configuration/133-site-configuration-input-filtering-tab

It's the only really useful one there and that is a screencap of the settings tab you already see in the administrator area, Site Config, Input Filtering tab. 

To be honest, that tab provides pretty much all the useful information that's needed, the manual doesn't add any more to the discussion.
