### ISSUE TITLE
ACL Enhancement for Actionbar Buttons

### ISSUE THREAD

**Issue by thleh** [WoollyinWalesIT/jomres#245]
Hi,

i have installed the ACL Plugin to control the menu items and to limit the available features to my customer. E.g. I disabled the new_property task for frontend user.

The menu item disappear but in the listyouproperties view the button in the action bar to create new properties is still there. It should be removed too.

JomRes Version is 9.9.17

Thanks
Thomas

**Comment by jomres** [comment]
This is not the place for support. If you'd like support please raise a ticket at https://tickets.jomres.net

**Comment by thleh** [comment]
In the forum they told me to leave that issue here: https://www.jomres.net/forum/General-discussion/25902-acl-enhancement-for-actionbar-buttons#46644

**Comment by jomres** [comment]
My apologies, I misread the feature request. I've reopened it now.

**Comment by jomres** [comment]
Closed due to lack of support for the feature.
