### ISSUE TITLE
Search options - Feature request

### ISSUE THREAD

**Issue by Farham777** [WoollyinWalesIT/jomres#247]
Hi.

I would like to suggest a tweak on the search options.

You've got your check-in check-out dates, town then type and number of guests.
Would it be possible to have Country, Province, City, Area, Suburb, type then Guests and to include a Keyword Search bar somewhere?

I live in South Africa, Cape Town but Cape Town is huge with many suburbs, extensions ect.
Just in and around Cape Town it would look something like this for a search on other competitors sites.
Here's a link for an example.

http://www.capestay.co.za/cape-town-guest-houses.asp

**Comment by jomres** [comment]
Insufficient support for feature request.
