### ISSUE TITLE
Availability calendar improvements

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#248]
Hello,

The availability calendar do not fit into  Small or Phone Screen.
I think it should be edited as follows: 2 months / line

Merci,

Jérôme

**Comment by jomres** [comment]
I assume you're referring to this screen https://snippets.jomres.net/2018-02-12_f36op.png

**Comment by JeromePayan** [comment]
Yes ! but on my phone it's look like that
![screenshot_20180212-124017](https://user-images.githubusercontent.com/25484155/36095485-b786a81e-0ff2-11e8-9f25-adc0e276f033.png)
