### ISSUE TITLE
Beds24 export tariff and minimum night

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#249]
Bonsoir,

in micromanagement mode The super property manager should be able to export the rates and night minimum of any property, whatever the property manager.

Merci,

**Comment by jomres** [comment]
Can't you configure the sub account's API key to be the same as your super property manager's key? I haven't tried that, does it work?

**Comment by JeromePayan** [comment]
Hey vince,

I cannot use an API key twice in beds24. I may ask to marck if they can do something
