### ISSUE TITLE
Button in guest interface to  get a maximum of comment

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#250]
Hi guys,

When a guest is connected to his account, he is able to check all reservation he made.

Can you add a new button to allow him to post a comment/review for each reservation he did ?

Or

a button to let the owner to send him a email and invite him to post a comment

That could be nice !

Jérôme

**Comment by jomres** [comment]
Jerome, can you confirm that the feature suits your requirements?

**Comment by JeromePayan** [comment]
Vince... That great thanks for having doing it possible !
jerome
