### ISSUE TITLE
 Basic pricing for renting

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#251]
Today, all OTAs like booking.com or airbnb offer a basic fare configuration for an apartment of 4 people (for example), and give the possibility to add a supplement from the fifth person for an amount " x "
If jomres could have this same type of tariff configuration, it would be great because it would change only the base price.

**Comment by ReneCB** [comment]
+1
Even this can also be achieved with the creation of a second tarif it would be much more easier if there would be a field like "+ _______ EUR for one additional person".

**Comment by JeromePayan** [comment]
Vince, 

I Hope your thinking about this issue,  because we want to do pricing for next year, and need to know if this option will be available soon.

This option could help us to limit the number of tariff to change in each property .... and avoid us to make mistake with the beds24 plugin while exporting the tariff to beds24

Merci !

**Comment by joniale** [comment]
I will vote up for this feature. Add to the base price a defined ammount per additional person. For example, You define what the extra person cost: e.g. +10€, then calculation is  2 extra persons cost +10*2=20€, 3 extra persons 30€.

Anyway, the problem with the prices would be reduced if Jomres implement a way to use the php API for managers. Coding the tariffs using php may sound complex but it is faster and easier than using the GUI. More important, it allow you to create scripts and batch massive modifications for many tariffs.
See my other ticket requestint this API. https://github.com/WoollyinWalesIT/jomres/issues/396#issue-430076536

**Comment by JeromePayan** [comment]
Vince, this is a very important issue for us and maybe for you if you want to improve beds24 connection.

For exemple today i need to create 2 tariffs for the same property.
tariff 1 = basic price for 2 guests
tariff 2 = price for 3/4 guests

Today working like that make us having several pricing to update with jomres and make the jomres  plugin TotalList editing wrong price in the list. This last, seems to display the tariff using the first ligne tariff (for ex. 2guests tariff for a 4 guest search)

Hope you will care about this for next update, because we are doing tariff for 2020 !

Best regards,

Jerome

**Comment by JeromePayan** [comment]
An extra option could be great

**Comment by jomres** [comment]
Standard tariff editing mode covers these requests.
