### ISSUE TITLE
The editing Tarif and min night calendar out of screen in Jomre template 

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#257]
Bonjour Vince,

I prefer to use the jomres template in the property manager profile.

For 2 main reasons
The first is that we have a drop-down menu that allows us to select the current property. Very practical thing when the property manager has several properties.

The second is that the screen is more readable, and especially at the level of widgets calendar and reservation (the screen is wider)

![jomres-tmpl](https://user-images.githubusercontent.com/25484155/35676135-f8e5642c-074a-11e8-90ee-f57ef12326cc.JPG)

However, in the pricing configuration in micromanagement mode, the calendar is displayed partly off the screen. This poses problems of readability and input error.

![tarif-jomres-tmpl](https://user-images.githubusercontent.com/25484155/35676148-fed2fb6a-074a-11e8-937b-3d0aeeb034d5.JPG)

On the contrary, in case of a lethtian template, the calendar is displayed well (but no drop-down menu or better readability for the rest)

**Comment by JuanGarciaG** [comment]
It would be great that from the calendar you could consult and modify the rates. It is a very repetitive suggestion in our clients.

**Comment by jomres** [comment]
Update that plugin, the scrolling problem is resolved.

Juan, you know you can click a date button to set the javascript calendar's start and end dates, don't you?
