### ISSUE TITLE
Extra available and translatable for all properties

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#258]
Hey Vince,

The labels of extras are specific to each rental.
Is there a possibility of create extra valid for all properties (at least for the label) so we could be able to translate the label in jomres translate pages.

Merci if you can do something for a next update !

**Comment by cmmfender** [comment]
i need too!!!

**Comment by ReneCB** [comment]
I support this feature request from JeromePayan. Especially for chargeable extras like air conditioning or addable breakfast it would be helpful to have the translation option.

**Comment by By-Pixel** [comment]
Also for custom property fields.
