### ISSUE TITLE
Grouping of Extras

### ISSUE THREAD

**Issue by hkraskian** [WoollyinWalesIT/jomres#260]
#83 
When offering multiple "Extras", the booking form becomes very long and sometimes near redundant.
for example:
Tour to destination with 4 seat car,
Tour to destination with 7 seat car,
....
I think about two different solutions
**1- Categorization (and subcategorization) of Extras. which will be opened i.e as an accordion list** 
A- Food
A-1 in restaurant,
A-2 pre-packed, 
.....

B- Tour
B1- destination 1
B1a- 4 seat car
B1b- 7 seat car

B2-destination 2
B2a- 4 seat car
B2b- 7 seat car
.....
....
**2- More customization of in "Extras" definition page,** to use resources for all group and resources per each guest. for example, the car is for the group, food can be for some guests, i.e.
![screenshot from 2018-02-20 12-43-24](https://user-images.githubusercontent.com/5346966/36414504-ed447afe-163b-11e8-9034-a65015dd3e8d.png)

**Comment by jomres** [comment]
Insufficient support for feature request.
