### ISSUE TITLE
Go to standard Joomla interface for Extras and Jintour lists

### ISSUE THREAD

**Issue by hkraskian** [WoollyinWalesIT/jomres#261]
#83 
The list of extras doesn't comply with the Joomla's other lists. There is no search, multi-select, delete and such. 
It would be more flexible to add this feature.

The case is the same for the "Tour/Activity management". 
Sometimes you need new tours very similar to existing ones, so a "Save as copy" or "duplicate" button will ease creation of them, 
Or the ability to bulk delete created lengthy tours list.

**Comment by jomres** [comment]
Closed due to lack of support for the feature.
