### ISSUE TITLE
Billing data from Beds24 to Jomres and VS

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#263]
Hey guys,

I would love to be able to use Jomres as an unique portal of information entry. But for now it's a little bit confusing because of this :

When some OTAs like homeway send the reservation on beds24, the price of the stay is not sent to beds24, and beds24 adds a set minimum price. Then beds 24 sends average billing information (most often false) to jomers.

For other platforms like booking.com, only the price of accommodation is sent to beds24. (are excluded from billing options, such as cleaning, garage, tourist tax ...)

1 So we end up in jomres with false billing information. If Jomres can add other benefits (it's great), it does not change the price of the stay sent by Beds24. Can you make this possible?

2. Jomres does not take into account the VAT setting possibly programmed in jomres when importing beds24.

It would be good to be able to get your hands on Jomres and have the possibility to change the price imported from beds24.

On the other hand, can we hope that once this is made possible by your work, we can hope to return the corrected billing information back to beds 24 again?

**Comment by jomres** [comment]
If the other platforms don't send a price, or if one platform sends prices ex-vat and another sends them int-vat but accommodation only, then that makes it very difficult to set the true price in Jomres, doesn't it?

**Comment by jomres** [comment]
Closed due to lack of support for the feature.
