### ISSUE TITLE
Scandinavian standard for dates and week start

### ISSUE THREAD

**Issue by celius** [WoollyinWalesIT/jomres#270]
The settings seems to just change the calendar in the booking form, but not anything else throughout the system. 

![screenshot-spiterstulen webist no-2018 03 16-09-52-33](https://user-images.githubusercontent.com/4268181/37516780-98c46d9a-290f-11e8-9992-792e4e1ce90a.png)
![screenshot-spiterstulen webist no-2018 03 16-09-53-22](https://user-images.githubusercontent.com/4268181/37516781-98e5e8d0-290f-11e8-99a1-9ed1b8576490.png)
![screenshot-spiterstulen webist no-2018 03 16-09-54-27](https://user-images.githubusercontent.com/4268181/37516782-99120c76-290f-11e8-9de2-3e76208504b1.png)

**Comment by alibarthi** [comment]
The dashboard dates are as intended to be displayed (always yyyy/mm/dd), but for the availability calendar please apply this change: https://github.com/WoollyinWalesIT/jomres/commit/a8e20dfe5785f1beea2e98b71944f437468a032c
