### ISSUE TITLE
Wrong include directory in api routes.php

### ISSUE THREAD

**Issue by kopfnuss** [WoollyinWalesIT/jomres#271]
Third party API plugins are not included correctly. There is an additional "." in the require_once call. The previous line checking the file's existence is correct, but the require call uses `remote_plugins.` instead of `remote_plugins`. 

Correcting the following two lines works as expected: 
https://github.com/WoollyinWalesIT/jomres/blob/22e61c9ca399016d8c54b82eb97b0b48c955b848/api/routes.php#L34
https://github.com/WoollyinWalesIT/jomres/blob/22e61c9ca399016d8c54b82eb97b0b48c955b848/api/routes.php#L38

**Comment by jomres** [comment]
Cheers, fix applied to Nightly branch.

This might interest you http://www.jomres.net/manual/installation-and-upgrading/370-installing-updating-to-the-nightly-branch
