### ISSUE TITLE
Lifetime of API tokens

### ISSUE THREAD

**Issue by kopfnuss** [WoollyinWalesIT/jomres#272]
When creating an access_token, the lifetime is 31536000 seconds (365 days). This seems an unusual long lifetime for an access token. The code in `jomres/api/oauth/oAuth2/ResponseType/AccessToken.php` seems to suggest it should be 3600, which is a more usual lifetime.

This is particularly problematic since deleting an oAuth client does not revoke it's access tokens and therefore allows all further API requests (within their scope).

Either reducing the lifetime drastically or at least having the lifetime configurable would be a good option.

**Comment by jomres** [comment]
It is a longer time, it's probably a better idea to make it a configurable option and I'll do that at some point.

**Comment by kopfnuss** [comment]
Is it on purpose that the access tokens continue to be active once a client has been deleted? 


In case anyone else comes across this and wants to override the access token lifetime, the relevant line is here: https://github.com/WoollyinWalesIT/jomres/blob/22e61c9ca399016d8c54b82eb97b0b48c955b848/api/oauth/server.php#L56

**Comment by jomres** [comment]
See the commits added today.
