### ISSUE TITLE
set several days of the week possible for check-in

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#281]
Hey,

I need to allow guest to do check-in saturday, sunday and monday because some of my properties are located in Thermal city and guest need to check-in on this 3 days of week.

I could be great to be able to setup it in the micromanage tariff mode in "extra option"

Jérôme

**Comment by jomres** [comment]
That's a very specific requirement, nobody's asked for it before.

What you can do is create three tariffs, one for each start day (Sat. Sun. Mon), that would give you a lot more scope for setting minimum intervals of the bookings, too.

**Comment by JeromePayan** [comment]
Vince,

In a previous post, I suggested creating a basic pricing for "x" guest, and having an extra "x" per additional customer (you flaged it as Feature request)

I Thinks this could be consider as a same request for future :

This is to facilitate the updating of the rates on the whole site, but also on the relation with Beds24. And to have only one basic tariff to export.

Multiply the number of rates on Jomres is a source of conflicts and errors that our users can not control.

I believe for myself that Jomres should copy the method used on other platforms like booking.com or airbnb.com so that our users are not lost and especially if the site jomres and connected with Beds24

**Comment by jomres** [comment]
Insufficient support for feature request.
