### ISSUE TITLE
Micromanage tariff display avaibility calendar

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#282]
Vince,

The micromanage mode allows to make a precise pricing according to the day, the week ... Super!

Would it be possible to know the state of availability of the property on this same schedule? for example with a color code (free = green - Busy = red?)

This would allow us to modify the rate and duration of the stay and thus do some Yield Management

Jérôme

**Comment by jomres** [comment]
Have a look at the Wise Price plugin http://www.jomres.net/manual/property-managers-guide/49-your-toolbar/settings/property-configuration/253-wiseprice-or-lastminute which automatically adjusts prices based on availability at the time of the booking.

**Comment by JeromePayan** [comment]
Hey vince,

The idea of ​​my request is rather based on the organization that property managers can have. To know :

We set a minimum of night often 3 or 4

It may happen that there is between two reservations for the same property, an availability of 2 nights.

In this case we put the apartment on a duration of 2 nights to rent these 2 nights.

Also, today we have to go to beds24 to look at our schedules and then go back to jomres to change the price of the night and the minimum stay.

Being able to display on the schedule of the mircomange tariff module would therefore be a significant improvement for the type of managers like us.

**Comment by jomres** [comment]
As I understand it, Beds24 now supports this through their integration with the CMF REST API.
