### ISSUE TITLE
Parse error: syntax error, unexpected '>' in /jomres/core-minicomponents/j06001dashboard.class.php on line 268

### ISSUE THREAD

**Issue by paul2011** [WoollyinWalesIT/jomres#285]
Hi,

I updated to Nightly (Joomla, Wordpress) tonight and wondered if you knew about this error:
Parse error: syntax error, unexpected '>' in /jomres/core-minicomponents/j06001dashboard.class.php on line 268 

After updating to Nightly tonight, I selected the Plugin Manager tab and got that error.
I copied the code from j06001dashboard.class.php I got a few days ago from another Nightly update, and it worked.

Nightly - Old Code:

WHERE `property_uid` IN (' .jomres_implode($thisJRUser->authorisedProperties).') 
ORDER BY surname';

Nightly - New Code:

WHERE `property_uid` IN (' .jomres_implode($thisJRUser->authorisedProperties).')';

===========================================

Nightly - Added New Code:

$temp_arr = array();

foreach ($existingCustomers as $customer) {
$temp_arr[] = array ( "guests_uid" =>$customer->guests_uid , "firstname" => stripslashes($jomres_encryption->decrypt($customer->enc_firstname)) , "surname" => stripslashes($jomres_encryption->decrypt($customer->enc_surname)) );
}

usort($temp_arr, function($a, $b) {
return $a['surname'] <=> $b['surname'];
}); 

==========================================

Nightly - Old Code:

foreach ($existingCustomers as $customer) {
$ec[] = jomresHTML::makeOption($customer->guests_uid, stripslashes($jomres_encryption->decrypt($customer->enc_surname)).' '.stripslashes($jomres_encryption->decrypt($customer->enc_firstname)));

Nightly - New Code:

foreach ($temp_arr as $customer) {
$ec[] = jomresHTML::makeOption($customer['guests_uid'], $customer['surname'].' '.$customer['firstname']);

Just trying to help.

**Comment by jomres** [comment]
Hi Paul,

Sorry, I missed this message. What version of php are you running?

**Comment by jomres** [comment]
Ok, I think I understand the problem. 

This should resolve it https://github.com/WoollyinWalesIT/jomres/commit/99006d58de20275f4cd6b59a883a31c8481eadc6 

Assuming you read this about 1/2 after I post it the Nighly will have the updated code. Thanks for highlighting it, it's a perfect example of why we need testing help :)

**Comment by paul2011** [comment]
Hi Vince,

I'm using PHP 5.6. I just re-installed Jomres Nightly just now, and that worked! Great!

For some reason, I am not able to see all the property images when I list all properties.

**Comment by jomres** [comment]
Ah, somebody else is seeing that too, it's not just me :(

**Comment by paul2011** [comment]
Hi,

I just tried: PHP 5.6, PHP 7.0, and PHP 7.2 to see if it was just me. I guess not.

Thanks

**Comment by jomres** [comment]
Fixed.
