### ISSUE TITLE
Commisions billing problem

### ISSUE THREAD

**Issue by JuanGarciaG** [WoollyinWalesIT/jomres#290]
Since the last version it seems that Commissions billing does not work correctly. The Cron does not seem to work and you can not see the bills from the hotel backend.

Could it be that the plugin has to be updated by the new GDPR?

**Comment by jomres** [comment]
I've scanned the cron code for commission, there are no fields in there that I can see that would be impacted by the gdpr stuff, Juan. 

Are you running cron jobs as "minicomponent" or via real Cron?

**Comment by JuanGarciaG** [comment]
Hello Vince, I had it in real cron but I have also tried it in a mini component and it does not work either.

I have also tried to run the cron manually and it does not work either.

It seems he does not do anything.

**Comment by jomres** [comment]
Raise a ticket please, I'll need to edit the scripts to see if I can find what the cause is.

**Comment by JuanGarciaG** [comment]
Ok, Vince
