### ISSUE TITLE
Enhanced Property List Totals -  Consideration of last minute and/or wise price settings

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#291]
Dear Vince, I tested the "Enhanced Property List Totals" (experimental) plugin for some time now on my live site. From my experience it has a positive impact on the amount of bookings we receive (compared to the time before when the plugin was not installed), as it directly shows the show exact pricing based on the items (type of room/accommodation) searched on in the search results list. The feedback from my customers is very good (I discussed the matter with some rebooking customers) and they like that they can see directly for which room/accommodation (combination) the price in the search results list is displayed (e.g. 1 x 4 bed apartment + 1 x 2 bed apartment / search for 6 persons).

As the impact of the "Enhanced Property List Totals" plugin on the number of bookings is positive I definitely want to further use this plugin in the future. Therefore I would be glad if you could enhance the "Enhanced Property List Totals" plugin so that last minute and/or wise price settings are considered as the users cannot see the discounted prices otherwise. I know that this might increase the time for calculations (server) - but maybe you could mention that (after this enhancement) only Jomres users should install it who have a fast server. 

As last minute prices are pretty important also for the PMs we work with it is necessary that the discounted prices are displayed/considered in the search results list (otherwise the guests do not get aware of the final prices before they actually add a room). I would be very happy not having to uninstall the Enhanced Property List Totals (experimental plugin) to achieve this.
Would be happy about a positive answer from you. 
Best regards, René

**Comment by ReneCB** [comment]
P.S.: As it looks the "Enhanced Property List Totals" plugin currently causes a malfunction in the calculation of the defined wise prices for apartments / MRPs as always the highest discount is considered independly of the percentage of rooms booked. It would be great if you could solve this with the next "Enhanced Property List Totals" plugin release.

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/historic-github-issues/p/enhanced-property-list-totals-consideration-of-last-minute-andor-wise-price-sett
