### ISSUE TITLE
Booking enquiries and Beds24

### ISSUE THREAD

**Issue by JuanGarciaG** [WoollyinWalesIT/jomres#293]
It seems that booking enquiries  when approved are not sent to Beds24. I tried to add these lines in "approve_enquiry_class" after I modified the contract (line 83), but in addition to sending the correct reservation to Beds24, I also sent another one that appears canceled.

Lines added:

$webhook_notification                               = new stdClass();
$webhook_notification->webhook_event                = 'booking_added';
$webhook_notification->webhook_event_description    = 'Logs when a booking is added.';
$webhook_notification->webhook_event_plugin         = 'core';
$webhook_notification->data                         = new stdClass();
$webhook_notification->data->property_uid           = $property_uid;
$webhook_notification->data->contract_uid           = $contract_uid;
add_webhook_notification($webhook_notification);

**Comment by jomres** [comment]
Thank you Juan! I'll add that to the next version.

**Comment by jomres** [comment]
It shouldn't create a cancelled booking, tho. That's very weird.

**Comment by JuanGarciaG** [comment]
A mystery.   :-O
