### ISSUE TITLE
Feature request: Include hreflang attribute in Jomres so that Jomres properties are considered/displayed in XML hreflang sitemap (which currently is not the case)

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#296]
Dear Vince, 

it would be great if you could include the HTML hreflang attribute in Jomres so that every accommodation page (if you find a way maybe also town page) would have the hreflang attribute included.

See: 
https://support.google.com/webmasters/answer/189077?hl=en

I think that many Jomres users have their site content (fully) translated into multiple languages and would welcome this.

Thank you in advance
René

**Comment by ReneCB** [comment]
To better illustrate this:

In the XML Standard Sitemap of my Joomla/Jomres installation all the Jomres properties are shown:
[https://corfu.apartments/index.php?option=com_jmap&view=sitemap&format=xml&xslt=1&lang=en](url)

The XML hreflang sitemap currently only considers all other pages of my installation but NONE of the Jomres properties:
[https://corfu.apartments/index.php?option=com_jmap&view=sitemap&format=hreflang&xslt=1&lang=en](url)

With the integration of an HTML hreflang attribute in Jomres this could be changed.

Maybe this helps to get some "+1"s for this topic ;-)

**Comment by jomres** [comment]
is this still needed?
