### ISSUE TITLE
Subscription package – option to limit number of rooms/apartments (units) per business/property (feature request)

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#298]
Dear Vince, 

it would be great if you could add a feature to the "package options" of the subscription packages which allows the admin to limit the number of rooms/apartments (units) per business/property for MRPs for the respective subscription package.

Currently it is only possible to limit the number of businesses (properties) per package. 

I would like to set up packages like
 
Subscription for 1 year for 1 hotel with max. 10 rooms
Subscription for 1 year for 1 hotel with max. 50 rooms
Subscription for 1 year for 1 hotel with max. 100 rooms
Subscription for 1 year for 1 hotel with > 100 rooms

Subscription for 1 year for 1 apartment house with max. 5 apartments
Subscription for 1 year for 1 apartment house with max. 10 apartments
Subscription for 1 year for 1 apartment house with max. 15 apartments
Subscription for 1 year for 1 apartment house > 15 apartments

As far as I can see this is currently not possible so it would be great to get an option to limit the number of rooms/apartments (units) per business/property.

Thank you in advance 
René

**Comment by biobill** [comment]
This is a feature I would like to use in my portal too...

**Comment by jomres** [comment]
Insufficient support for feature request.
