### ISSUE TITLE
Feature request: Option for the property manager/landlord to leave a comment on a review

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#303]
Hi Vince, 

it would be great if you in include the following feature in Jomres:

+ Option for the property manager/landlord to leave a comment on a review. 

Currently it is not possible to leave a comment on a (maybe negative) review about a property. I think that it would be good if (at least) the property manager/landlord has the option to leave a response/comment to a review that he receives. The comment should be place directly below the respective review so that the connection to the respective review is clear.

I would be grateful to all Jomres admins who consider this useful if they could write a comment about this feature request (to increase attention).

Thank you in advance,
René

**Comment by mcr71** [comment]
+1 yes, please add this useful feature

**Comment by paul2011** [comment]
+1 yes, me too, please add this useful feature

**Comment by davidskate15** [comment]
+1 This would be helpful to us as well.

**Comment by jomres** [comment]
I'm tempted to have some fun with this feature and make it so that once a manager leaves a reply, they can't then remove it.

**Comment by jomres** [comment]
The nightly has been updated to include this feature. Once you have updated to the Nightly branch remember to run the Database Integrity Check to make the relevant table changes.

https://www.jomres.net/manual/installation-and-upgrading/370-installing-updating-to-the-nightly-branch

**Comment by ReneCB** [comment]
Dear Vince,
thank you very much for adding the "review reply feature" with Jomres 9.14.0.
I like how you implemented it, especially with the "guidelines for a review reply".
Well done!
Best regards
René
