### ISSUE TITLE
label editing mode

### ISSUE THREAD

**Issue by hkraskian** [WoollyinWalesIT/jomres#304]
In the frontend, 
when "label editing" is set to "on", 
in the property manager's view, in the property details, 

After switching "label editing" to off  (in the label editing mode = on, submit doesn't click) 
when the view is "normal view" and using not the main language of the site
submit button doesn't save edited label.

If change to the main language, or change to the "Full-screen view", it functions.

**Comment by jomres** [comment]
I have tried to recreate this but can't, is anybody else seeing this as a problem?
