### ISSUE TITLE
Support for OpenStreetMap -->Jomres your vote?

### ISSUE THREAD

**Issue by ssnobben** [WoollyinWalesIT/jomres#305]
Hi many have asked for support for OpenStreetMap though many have problem with Google maps nowdays especially the charge money and changed their model.  

See this post at Joomshaper https://www.joomshaper.com/blog/sp-page-builder-3-2-9-comes-with-open-street-map-addon

Info
https://www.openstreetmap.org
Licenses etc
https://wiki.osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ

**Comment by ReneCB** [comment]
I also would be happy to have a maps solution where no link to the accommodation owners page (that is actually competing with our portal... and currently we pay for advertising the owners page displayed in Google maps...) is by default inserted (as in Google maps) and cannot be switched off.

**Comment by ssnobben** [comment]
Yes I agree with you too ReneCB :)

**Comment by rrmdp** [comment]
JPD Valentina v2 including Open Street Map has been released, more info https://www.jomres-plugins.com/open-street-maps-and-jpd-valentina-jomres-template-package
