### ISSUE TITLE
show "approved" and "commission rate" on 1st page 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#31]
https://www.jomres.net/forum/Feature-requests/24615-show-approved-and-commission-rate-on-1st-page

Hello,

when in admin page you, you get a list of system's Businesses with various information, like name, region, tel, etc
But for the most important info you have to click on the green button in order to see if a property is approved or which commission rate is assigned to that.
It would be better to have these information on the initial page as they are more important than fax or tel number.
Maybe unpublished property should have a red button instead of the green one.

Thank you

**Comment by aadz1** [comment]
+1

**Comment by alibarthi** [comment]
This feature is already available. Approved and Commission dropdowns show up visible by default.
