### ISSUE TITLE
Feature Request: Last Minute discounts considered directly on front page/in search result list and property details page and not only after adding a accommodation unit on the booking form site

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#310]
Currently the last automated last minute discounts are only calculated/displayed after a user has aready picked an accommodation (for its normal price). This way he gets the last minute discount as a bonus when he already decided to book the accommodation for the normal price (and the owner gives a discount when it would not be necessary). It would be great if the automated last minute discount would be considered directly on the front page and in search result list and on the property details page and not only after adding a accommodation unit on the booking form site. I think the automated last minute discount feature is a great feature (which is also good for marketing/advertising towards accommodation owners) but the current realization is not optimal. Happy for everyone supporting this feature request ;-).

Best wishes, René

**Comment by JeromePayan** [comment]
Bonjour,

Could we have the possibility to display the last minute discounts but also the long term discounts, which are generable by JPD discount!

Best regards,

jerome

**Comment by ReneCB** [comment]
P.S.: Vince, I think it would be great if you could also integrate #291 when you start to work on this as it is related. Best wishes, René

**Comment by JeromePayan** [comment]
Hello ! Any news with this issue ?

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/feature-requests/p/last-minute-discounts-considered-directly-on-front-page
