### ISSUE TITLE
Feature request: Simplify the review process so that no login is required to leave a review

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#311]
Is it maybe possible to simplify the review process so that no login is required? I know this is a matter of access rights but most other booking sites do not require that you have to be logged in to leave a review (to have as few obstacles as possible which could prevent users from leaving reviews).

Maybe a link like 
https://SITENAME/en/all-accommodations?task=add_review&property_uid=XYZ&contract_uid=XYZ plus some extra information (that can only be used one time) to avoid the login process could be sent to the user?

**Comment by paul2011** [comment]
This is just my option. I don't think this would be a good thing because once the spammers find your site they will spam it with fake reviews and post links to other sites. This would make more work for the site owner to take time to delete these fake reviews. Thanks!

**Comment by ReneCB** [comment]
As I wrote the link (that would be sent via the review reminder function so that only users who have already been a guest in one accommodation can receive it) should be configured the way that it can only be used once for one review. This way there should be no spamming risk.

**Comment by jomres** [comment]
Given that new bookers are automatically logged in now, I think that this request is redundant, Rene.
