### ISSUE TITLE
Feature request: Option for user to (at least partly) anonymise their review

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#312]
I think we could get more users to leave a review if there would be an option for the user to (at least partly) anonymise his review. Not all users may want to leave a review with their complete name (currently this is the only option as far as I can see). Maybe you could ask the user if he is O.K. with publishing his name next to the review or not. 

If the user has the name Peter Miller, I think best would be to have/offer a dropdown (or however you think it is best to implement) like
-	publish with full name [Peter Miller]
-	publish partly anonymised [Peter M.] 
-	publish partly anonymised [P. Miller]
-	publish completely anonymised [name hidden/anonymous] (maybe stating the travel dates from ... to...)
and not a text input field where a fake name could be entered. 

Grateful for every supporter of this function ;-)
René

**Comment by jomres** [comment]
Guests can now choose to anonymise their details. Historic reviews are not affected.

**Comment by ReneCB** [comment]
Thank you for adding this feature, Vince!
