### ISSUE TITLE
Feature request / feasibility discussion: Show also properties where a one-time room change is unavoidable/necessary during the stay (only MRPs).

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#314]
I think everybody knows how many days holiday accommodations (MRP) cannot be rented due to relatively short gaps between bookings that are hard to close (especially for apartment house with less than 5 units).
In order to increase the probability to close such gaps it would be very helpful if (only for MRPs) short gaps like 1st – 3rd May in room A and 3rd - 7th May in room B could be sort of “connected” so that a booking with a one-time room change from room A to B would be possible (in virtual room AB). If a user would currently search from 1st - 7th May this property would not appear in the search results list at all.
Currently we sometimes handle these cases by a “workaround solution” and create of an “virtual” additional room (n+1) for an MRP with n rooms where we close (for room n+1) all dates by with black bookings apart from the “gap-connection” periods. This way the property will appear in the search results list. But this work around is labour intensive and prone to errors and many property owner who work with us should better not try this at all ;-).

I know this idea is tricky - otherwise every accommodation booking portal would already have implemented this. From a technical point of view I think maybe a function could extract/collect all periods for the same room types in a MRP where there are uninterrupted periods that could be extended by connection of two rooms so that the period that can be booked is extended by combination (= one time room change; by the way from my experience 99% of the guests would not want to change a room more than once during their stay, so that only the one time room change case seems to be relevant). Maybe the data collected by the function described above could be stored in a one-time room change cache matrix (or something similar – as I am not a programmer Vince might have a better idea) which is generated every hour/day so that the calculation time can be reduced when the user starts a search. 
Then a checkbox on the front page search could be integrated (“I am fine with changing my room once during my stay”) and so the user would also have more properties to choose from and the probability to close gaps in the properties could be increased.

Vince, please state if you see a chance, if and how something like this could maybe be implemented. 
I think that this function for sure would be very suitable to advertise the software to property owners.
But it needs a lot of brain and we would have to developed also how the booking process would work (would the virtual room AB be booked? How would the booking parts in room A and B be closed in the calendar if a virtual room would be created in the background, …).

Well, as it is already late I hope you do not think that I am already dreaming ;-).
Looking forward to Vince opinion and your comments on this topic.

**Comment by jomres** [comment]
Insufficient support for feature request.
