### ISSUE TITLE
Feature request: Option to really EDIT (modify) black bookings + add a column "room(s) included in black booking" in the table under "Bookings" -> "Black bookings" 

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#315]
When I currently click on the icon in the column "Edit item" under "Bookings" -> "Black bookings" I only have the option to delete the respective booking but not to edit it. When I just want to make a change to a multi room black booking like removing a room, I currently have to delete it and create a new one. It would be great to be able to add the following options to modify black bookings:
- add room(s) to black booking
- remove room(s)  from black booking
- change arrival day
- change departure day.

I order to make it easier to quickly identify/find the black booking that I want to modify it would be great to add a column "room(s) included in black booking" in the table under "Bookings" -> "Black bookings" where the room(s) included in the respective black booking are displayed. Currently I sometimes have to open multiple black bookings to identify the one which has the room(s) I am looking for included.

If someone sees other options that should be added to modify black booking, it would be nice to add them below in a comment. Of course, I'm grateful for supporters of this feature requests ;-)

**Comment by ReneCB** [comment]
P.S.:
Maybe also 
- Split black booking (or extract room from black booking in new black booking)
would make sense (in cases, when I have a group black booking and some people want to extend their stay). Then I could extract the rooms for those who decided to stay longer from the original black booking and modify the departure date in a next modification step.

**Comment by jomres** [comment]
Insufficient support for feature request.
