### ISSUE TITLE
Feature request: Display of the next available times on the property details page for approximately the same number of days, if the booking period currently entered via the search function is already occupied.

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#316]
You might now this feature from other booking portals/OTAs. If the exact requested booking period is already occupied, it would be nice if the nearest available period for a booking with approximately the same booking duration is displayed on the property details page. 

It should be clarified where this information should best be displayed on the property details page; e.g. below the room type icons at the end of the object description text (separated by room type) or perhaps below the slideshow or (YOUR SUGGESTION??). 

It would be good if on admin level (or PM level?) the following configuration options could be defined:
- Display nearest available booking periods on the property details page within "+/- x days" of the dates provided in the search [maybe +/- x days as dropdown menu]  
- Display only available booking periods in the range defined above for (approximately the same number of days (booking duration), like) "+/- x days" more / less of the originally specified booking duration.

I think this feature is especially useful for customers who want to book a specific accommodation again.

Comments and supporters welcome!

**Comment by JeromePayan** [comment]
Vince this feature will be very Nice. 

Booking.com is displaying this kind of information.

I would  prefer that suggestion of next available stay could be display in The search Console first then why not in the property details.

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/feature-requests/p/display-of-the-next-available-times-on-the-property-details-page
