### ISSUE TITLE
One Smart calendar

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#317]
Vince

I know that it may asked a lot of work. But as all other OTA are changing the way of displaying calendar,  we need to have the same things. I mean in one screen all information  about occupancies, prices and minimum nights settings.

It could be great to display and be able to setup on widget calendar (or somewhere else) this information  :

Booking information (as today)
Price per day (daily price in beds24)
Minimum Nights
Price multiplier to be able to increase or decrease daily price on jomres 
Calendar events configurable by PM or site owner to help pricing (Christmas holidays, world cup.... )

BEDS24 is a nice example.

This kind of screen will be helpful to PM who can and want to adapt their yield management system

I wish I could attract some of you about this huge feature ! 

All like will be welcome

Merci

**Comment by jomres** [comment]
Insufficient support for feature request.
