### ISSUE TITLE
Stripe Uncapture payment for deposit

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#318]
Vince

Stripe allows us to Uncapture for 7 days a  payment within their own website to capture a deposit. But we need to connect to stripe, choose the property where the check-in is...

It could be great if a receptionist OR Guest  will be able to UNcapture the deposit thru Jomres.

He will connect (or not) on to Jomres and go to property or guest page and click on stripe deposit.

This will help us to do a very quick check in.

**Comment by jomres** [comment]
What's the purpose of "uncapturing", Jerome? Do you mean to pre-approve a payment?

**Comment by JeromePayan** [comment]
yes sorry i mean to autorize only a payment (stripe langage)
