### ISSUE TITLE
Housekeeping Report

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#320]
Hey Guys,

Here is a report that could be interesting to develop to allow men and women maintenance, housekeeping and check-in check-out, which I would call "housekeeper" in the rest of this message.

This report could be of the same format as the "list of reservations" module, which adapts to screens of any format. I love the plus button to developp all information

We should find the following information (already seized upon booking)
Name of the property
Customer Name and Sales Channel
Start of arrival
Date of departure
No. of people
Customer's email
Customer's phone
customer comment / reservation

And the information we will have to add by hand, according to everyone's needs. Mine are the following

on one line, allow the property manager to check boxes to tell the housekeeper what to do - what is expected of her
Check in
Household
Check-out

And finally the following information that the property manager / receptionist will have entered, to prepare the check-in

Estimated time of arrival
Tourist tax to be paid on the spot
Surcharge to be paid on the spot
Deposit (add the link here eg stripe to enter a payment capture see other issues)
Observation for the housekeeper (for exempale, maintenance to do, repair to do verbal guest comment....)

Hope this could suite you ! Like it if so !

Merci

**Comment by compi66** [comment]
would be very good this report

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/historic-github-issues/p/housekeeping-report
