### ISSUE TITLE
Property manager need to charged Owner property for services every month

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#322]
Hey Every body, 

I care of several properties manager who need to charge to property owner their service every month.
Booking are coming from all OTA as booking.com, airbnb, expedia... I am using Beds24 channel manager too.

This billing need to be done as well,

- A percentage on the amount of accommodation paid
- the possibility of charging for cleaning fees if the host customer has to pay for example directly from the OTA operator (booking.com, airbnb.com ...). Although often the cleaning service is paid locally, on arrival.
- the possibility to charge a cleaning fee for linen and bed linen
- the possibility to charge additional cleaning or repair costs

Today I export billing data (Beds24) and retrieve all data on EXCEL file
I do a report with all booking information, and add some billing columms 

I may not be  the only one to have this billing need / process

How do you do ? does it interest you?

Jérôme

**Comment by jomres** [comment]
Insufficient support for feature request.
