### ISSUE TITLE
Feature Request: Additional booking reporting

### ISSUE THREAD

**Issue by SPMoto** [WoollyinWalesIT/jomres#323]
Hi.

I would love additional metrics for reports.
I use Jomres for a motorcycle hire business.
So I control all properties.

Additional metrics would be great. The current 'Monthly income' doesn't show details like:
How many bookings per Hotel/Bike. Weekly/Monthly/Lifetime.
What time of day they were booked. - Can track impact of advertising or post.
Average booking cost.
Average booking days.

Lots of good solid data always helps.

Thanks

**Comment by jomres** [comment]
Insufficient support for feature request.
