### ISSUE TITLE
Jomres - Plan Your Route Plugin - Feature Request

### ISSUE THREAD

**Issue by ChiliKutiAfrica** [WoollyinWalesIT/jomres#326]
Hi,
Would it be possible to add the following feature to the jomres plan your route plugin:
If you go to a listing on jomres, and you go to read more, it displays the info of the listing with the amenities, descriptions etc and then there is a section there called plan your route. The plan your route function requires one to enter an address. Would it be possible to add an option called “current location” as the user might not be at home when he plans his route but might be on another holiday destination already and would need to use that location’s address to plan his route to the next destination?

Thanks.

**Comment by alibarthi** [comment]
The Google maps with driving directions plugin already has such route planning feature with upto 9 intermediate waypoints/stops.
