### ISSUE TITLE
Feature request: Make extras editable/deletable

### ISSUE THREAD

**Issue by HDelfs** [WoollyinWalesIT/jomres#327]
Once an extra was added to an invoice it should be deletable or editable as long as the invoice is not paid.

**Comment by JeromePayan** [comment]
Make payments too... with With the possibility of classifying the different payment methods (bank card, cash, ...)

**Comment by jomres** [comment]
Use the "Add service to bill" feature, and  put the cost in as the negative version of the cost of the extra. That will maintain not only a record of the extra required, but also that you have removed the cost of that extra.
