### ISSUE TITLE
Rate comparison widget on booking page like Triptease do

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#328]
Hey guys,

In future it could be great to be able to activate a rate comparision widget price on booking page
(for those who sell on airbnb, expedia, booking)

know that Beds24 for example allow to connect to Triptease.com

This is a very nice app to explain guest that we are doing best price on our own website... and be sure to convert a vist to a booking !

maybe we can trade on this subject !?

Jerôme

**Comment by jomres** [comment]
Add a screenshot please Jerome.

**Comment by JeromePayan** [comment]
for example on that website www.https://thehoxton.com
![comparison triptease](https://user-images.githubusercontent.com/25484155/47075247-78982200-d1fc-11e8-9226-0784bb75cce3.PNG)

**Comment by JeromePayan** [comment]
This a new comparison system too... 
https://about.hotelpricexplorer.com/fr/page/hotel-price-explorer-premium.3.html

**Comment by wordskill** [comment]
It is a nice idea, especially in the context of a hotel's own website. Assuring the customer, in such a visual manner, that they are getting the best price will definitely reduce last-minute hesitations and increase conversions.

The only problem is that all of these platforms - Booking.com, Expedia, Hotels.com, Agoda - have rules against undercutting them. I don't know how actively those rules are enforced, but that is the reason why you have the bizarre situation whereby booking directly with a hotel is often more expensive than using a third-party site that charges them a hefty commission. It is also the reason why many hostels unofficially offer a 10% discount code to repeat guests who book direct, as a "hidden" way to undercut the platforms.
