### ISSUE TITLE
Agent/private notes for a listing

### ISSUE THREAD

**Issue by davidskate15** [WoollyinWalesIT/jomres#329]
Hello, It would be useful to have a section in administrative are where managers and agents can add private notes only available to them, like contact details of owners, key holders, cleaners, terms and conditions etc? Thanks

**Comment by jomres** [comment]
Hi David,

I've added a new plugin called "property notes" which allows you to save notes for each property. Install it and you'll see a new menu option in the dashboard which is currently worded "private notes".

Additionally, it allows you to add a widget to the control panel/dashboard which displays those notes. The only formatting allowed is carriage returns.  

Let me know how you get on with it.

**Comment by jomres** [comment]
Screenie https://snippets.jomres.net/2018-11-12-mfppa.png
