### ISSUE TITLE
Reference Nº

### ISSUE THREAD

**Issue by davidskate15** [WoollyinWalesIT/jomres#330]
Hello, Think it would be good for each property to have a reference or ID number and to be able to search by ref.-ID  number.

**Comment by natanzi** [comment]
There is property id for each property

**Comment by rrmdp** [comment]
You could add the reference ID to the property description and then you'd be able to fint it using the description field at Jomres search form.

**Comment by jomres** [comment]
Yeah, there are already a number of ways that this particular cat can be skinned. Do we really need yet another one?
