### ISSUE TITLE
Mark invoice as paid when paid in bed24

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#331]
Hey Vince,

I have many bills that are automatically paid on beds24 via OTA.

It would be great if I could automatically consider these bills as paid.

Or allow the property manager to mark several invoices at once as paid.

Best regards,

Jérôme

**Comment by jomres** [comment]
> It would be great if I could automatically consider these bills as paid.

You mean when the booking is created in Jomres?

**Comment by JeromePayan** [comment]
Vince,

when the reservation is generated by beds24 (aribnb, booking.com, expedia.com ...) in most cases, this reservation is pre-paid by a virtual card. Which means that Beds24 sends the booking to jomres with a balance to Zero.

I do not know if you can make sure that if the balance to be paid is 0 on beds24, then the bill is marked as paid in jomres

On the other hand it can happen in frequent cases, that I have to add on the invoice (reservation) additional expenses annexes on beds24, but in a way subsequent to the creation of the reservation

**Comment by jomres** [comment]
Ok, so you have a problem. In some cases you want to mark the invoice paid as soon as the booking is imported from Beds24, but in other cases you don't want it marked as paid? How is Jomres to know the difference?

**Comment by JeromePayan** [comment]
Bonjour Vince,

I think that for beds24 users, it would be more efficient for reservations from beds24 to be sold out .

Then property manager must be able to manage or not the necessary extras

Moreover, maybe you could make it possible to make a multi-selection of invoices and mark them as paid or unpaid ... without having to display invoice by invoice, as is the case today.

Moreover, I add that the graphs and statistics of earnings cumulate only the completed / paid bookings, which can be frustrating for the one who does not take the time to pay the bills on the skirts .... but this last point mentions a request I made some time ago.

**Comment by jomres** [comment]
Does Beds24 CMF REST API feature do this now Jerome?
