### ISSUE TITLE
Feature Request: Linked rooms

### ISSUE THREAD

**Issue by By-Pixel** [WoollyinWalesIT/jomres#332]
We have the need to link "rooms" in some properties, like hotels make available family rooms joining two or more adjacent rooms.

Example: A villa with some sub apartment or rooms, guests can book the entire villa or one sub apartment/room. When they book the entire property the sub apartments are no more available or vice versa.

**Comment by JeromePayan** [comment]
Yes this is a good Idea. For example in beds24, you can create a virtual property available only if a linked property is available...

Jérôme

**Comment by By-Pixel** [comment]
Yes Jérôme, it looks pretty simple:
https://wiki.beds24.com/index.php/Bookings_which_can_be_assigned_to_more_than_one_room_type

Essential feature to implement in Jomres.

Thanks

**Comment by jomres** [comment]
Insufficient support for feature request.
