### ISSUE TITLE
Navigator Forward Button  and search property list

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#334]
Hey Vince,

When we do a search, then a property list is showing available properties !
If we click on "book now"  then  jomres open the booking page 

At this point everything is perfect !Jomres is doing a good job (just need a real live price on this property list as we asked with René)

BUT

If we go back with the internet browser to the list because we change our mind... or we are not agree with the calculated price

THEN

Jomres list all properties even those who are not available

Rodrigo from JPD did a nice job with jpd_properties_navigator... but this button is working only on the detail property page and not in booking page

Can you both of you do something ?

Best regards

**Comment by jomres** [comment]
> Jomres list all properties even those who are not available

That's why the return to search results button was added, as this includes functionality to pull from previous searches to ensure that the return to the results includes the filters.
