### ISSUE TITLE
Feature request: Longterm Discount in advanced tariff

### ISSUE THREAD

**Issue by compi66** [WoollyinWalesIT/jomres#339]
We think it will be a big plus if we can configure longterm Discounts, based on how many days a property rent, In percent or decimal. depends on complete booking duration, overall matched tariff.

For example, we offer a client a discount if he rent a property more then 7 days up to 14 days 8%, if he rent between 15 and 21 days 14% and so on.
Overall tariff. we suggest this to have it in advanced tariff.
it would save a lot of time for configuration of each discount level as a tariff for each season.

**Comment by ReneCB** [comment]
Hi compi66,

Have a look at Rodrigo's JPD Discounts plugin (3rd party plugin for Jomres). This does exactly what you request.
[https://www.jomres-plugins.com/jomres-plugin/jpd-discounts#services](url)
or
[https://extensions.joomla.org/extension/jpd-discounts-for-jomres/](url).

Best wishes
René

**Comment by rrmdp** [comment]
Thanks Rene 👍

**Comment by compi66** [comment]
Thanks Rene.
Looks like this issue is solved with this :-)
