### ISSUE TITLE
Mobile Friendly / Collapse room feature filter 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#34]
https://www.jomres.net/forum/Feature-requests/24683-mobile-friendly-collapse-room-feature-filter

Filter rooms based on their features.
Can we collapse the room features filter for small viewport / mobile devices?

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Whilst I'd like to add this feature there isn't enough support for it therefore closing this feature request.
