### ISSUE TITLE
Feature request: Departure Day in advanced Tariff

### ISSUE THREAD

**Issue by compi66** [WoollyinWalesIT/jomres#340]
in addition to arrival Day we suggest a departure day, in same way as arrival day.

this would help to configure a tariff in that way, client has to book the complete week.

for example, currently in advanced tariff we have a tariff for season 1, with arrival day everyday, min. days 2 days.
a season 2, with arrival day saturday and min. days 7.
If a client book 10 days, 7 days are part of season 1, 3 days are part of season 2.
then all rules match, but guest not stay 7 days in season 2, just complete duration ist more then 7 , and
this is why season 2 match anyway.
we want that guest stay the complete week in season 2. 
so if we can configure departure day as well to saturday on season 2, guest cannot book or has
to change booking request

**Comment by jomres** [comment]
Sorry, I won't be adding this.
