### ISSUE TITLE
research fields / or widget to search in all properties 

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#345]
Hello,

We need to search all bookings made for a given client, we must do it property by property

Would it be possible to consider 2 methods:

The first, to display all the reservations of the customer via the account of the property manager

The second, to display all the reservations of the customer on the whole site (all property managers confused)

Thanks in advance

**Comment by jomres** [comment]
If you list bookings and use the all properties filter, then those bookings should appear when you filter by guest name.
