### ISSUE TITLE
Copy business description - Option from one to all selected properties

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#346]
Heys Guys

What do you think about to be able to copy from one to selected propertes, some fields like (check-in procedure, direction, Apartment rules, Policies & disclaimers,...) for a PM or Super Property Manager

Have a great end of year ! enjoy it !

Jérôme

**Comment by ReneCB** [comment]
Hi Jérôme, 

currently we solved this issue via an (offline) template document from which we simply copy links into these fields, which link to some general pages (which we set up in Joomla as regular Joomla pages for check-in/out, policies & disclaimers, local activities, ...) and only integrate the links to the general pages in the respective fields in the property description when we set up a new property.

See for example:
[https://corfu.apartments/en/all-accommodations/apartments-st-george-cove-25/view](url)
Have a look there at the fields:
- Policies & disclaimers
- Check-In & Check-Out
- Nearest Airport
- Area Activities
- Airport Transfer & Car Rental
(I think for directions it does not make to much sense...)

This is the easiest way to (simply without any work for Vince) solve this. 
If some PM does not like the links he can simply delete them and use his own texts.
But if you need to change one of these "general links" you currently have to do this for all accommodations that use the general links (in all the fields). Well, this would also be the case for all the properties with the "copy fields" that you proposed. 

Smarter would maybe be a solution where - if required - general texts/links could also be added/edited centrally and one could select which field (in the installation) should be general one and which one not in the backend (the general links/texts make especially sense for geographically "focused" installations from my point of view).

Maybe Vince could integrate something like ("use general links/texts for ... fields or not" + checkbox). 
But I think Vince has to decide if this is worth it or if the solution described above is currently sufficient from his point of view. 

Best wishes and already a Happy New Year 2019!
René

**Comment by jomres** [comment]
Insufficient support for feature request.
