### ISSUE TITLE
Referrer Booking

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#349]
Hey vince,

You have just update Beds24 plugin to show the referrer (OTA) number booking, that great !

And can you add the referrer name too, in other column ? this could help us to know where the booking is coming from... and in the future to do good graph statistic / OTA

Merci

**Comment by jomres** [comment]
Referrer name added

https://github.com/WoollyinWalesIT/jomres/commit/7b47bb62686e7f94b0ac7b34c2b22530c8a60805

**Comment by JeromePayan** [comment]
Hey vince, I can not see refer name column in new jomres 9.17.1
