### ISSUE TITLE
Price on rooms Tab 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#35]
https://www.jomres.net/forum/Feature-requests/24690-price-on-rooms-tab

In an effort to simplify the user experience.
I would like to suggest: SEE Image
1) Room price be published on the room tab.
2) ADD Wise Price discount below the crossed-out price.
3) ADD a room description,
4) ADD a [ Reserve this Room ] button.

RESULTS: The end user has ALL the information needed to select a room on 1 page.

Oh, 1 more thing!
Replace the "Room Type" (ie: King Bed) with "Room Name" (ie: Contemporary Premier King) and we're GOLDEN!!
Thank You!!

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Closed due to lack of support.
