### ISSUE TITLE
Optimisation of input calendar for task "New black booking", so that a faster date entry is possible

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#350]
Dear Vince,

it would be great if you could optimise the following calendar related usability issue to save to for the PMs when they enter a black booking:

Whenever a PM enters a “New Black booking” (task=new_black_booking), which is some months in the future from today, it would be great if the departure date would directly jump to a day/some days after the arrival date when the arrival date is entered via the date picker by the PM. This would save time and would be more elegant. 

To illustrate: If I today (January 2019) pick the 06/07/2019 as arrival / black booking start day (task=new_black_booking), the black booking departure date currently still “remains” in January 2019. If would be great if the date for the departure date would be adjusted in the same way as this is on the front page search so that I do not have to bother to navigate from January to July again also for the departure date. Just the same way as it is in the regular front page search / search bar that the users/guests see.

I am sure the PMs would appreciate this every time they have to enter a black booking.

Thank you in advance,
René

**Comment by jomres** [comment]
Done, Rene.

**Comment by ReneCB** [comment]
Thank you very much for adding this, Vince :-)

**Comment by ReneCB** [comment]
Dear Vince, 

can you please check in the latest Jomres nightly for an MRP:
When I enter a new black booking then the feature described above is fine for the first page/step in the entry process but the dates are not "forwarded/transported" to the second step/page where I choose the relevant room of the MRP. There (in the second step) the arrival/departure dates now are completely missing and need to be entered again. 

Thank you in advance and best regards,
René

**Comment by jomres** [comment]
This seems to fix it for me, Rene

https://github.com/WoollyinWalesIT/jomres/commit/8e2bbd54920bbd94222daf3cc6e277b53a3fb1e7

**Comment by ReneCB** [comment]
Thank you Vince, it seems to fix it for me, too. Great support!
Kalo Pascha from Corfu!
René
