### ISSUE TITLE
multilistbookings fails to show additional booking

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#354]
1 - If manager makes booking for customer using email ABC@xyz, the new customer account is created. The customer logs in and visits List My Bookings multilistbookings shows booking.

If manager makes another booking for the same email ABC@xyz, the customer does not see the 2nd booking in the multilistbookings.

But if the customer visits Show My Invoices, listinvoices shows both invoices.

Issue is that both bookings need to be shown on multilistbookings.

**Comment by allynat** [comment]
To confirm - wordpress- 9.16.1

**Comment by allynat** [comment]
I believe there may be a wider issue in the mulistbookings.

Having done a data wipe and started over with new bookings, I only see invoice content in Show My Invoices but do not see any bookings in mulistbookings.

I will test further and update here.

**Comment by allynat** [comment]
Data Wipe does not wipe CMS user or Invoice Numbers.

Having run a data wipe again and manually cleared CMS users I note that invoice numbers are starting from the previous data set.

The original issue still stands, mulistbooking only shows the first booking made. List invoices shows all bookings made.

Note, bookings are only made by managers.

**Comment by allynat** [comment]
Update on last comment - For information
_Having run a data wipe again and manually cleared CMS users I note that invoice numbers are starting from the previous data set._

A wipe indeed clears test data entered but Property Configuration-Invoice numbers, retains the previous number reached by the old test data.

**Comment by jomres** [comment]
Don't forget that there's the new Custom Invoice numbers feature, which makes this issue moot now.
