### ISSUE TITLE
show_invoice_seller Property Name + Guest Name

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#355]
2 - show_invoice_seller by default shows
<patTemplate:tmpl name="pageoutput" unusedvars="strip">
	<div class="row">
		<div class="col-md-6">
			<strong>{HFIRSTNAME}</strong>
		</div>
		<div class="col-md-6">
			{FIRSTNAME} {SURNAME}
		</div>
	</div>

The result is that view_invoice displays the property name + the guest first & lastname.

By removing {SURNAME}, the guest name is removed and the property name is displayed.

<patTemplate:tmpl name="pageoutput" unusedvars="strip">
	<div class="row">
		<div class="col-md-6">
			<strong>{HFIRSTNAME}</strong>
		</div>
		<div class="col-md-6">
			{FIRSTNAME}
		</div>
	</div>

Issue is A)why do both show from {FIRSTNAME} {SURNAME} & B)how does the issue resolve if {SURNAME} is removed

**Comment by allynat** [comment]
To confirm - wordpress- 9.16.1

**Comment by jomres** [comment]
Sounds like it's to do with L226 of this file

https://github.com/WoollyinWalesIT/jomres/blob/master/libraries/jomres/classes/jrportal_invoice.class.php

**Comment by jomres** [comment]
Is this still an issue, Ally?

**Comment by allynat** [comment]
Hi Vince

Well I have just instructed the staff to do time@ initials of customer @ dummy.org <http://dummy.org/> 

But as you appreciate, this could cause major issues for some users.

Sadly with some installations this will break the deal as its a fudge rather than a solution.

Currently I have 3 installations following the workaround but I have a 4th still awaiting to go to Jomres version with GDPR onwards and I am scared stiff, as it has so many bookings & uses a lot of office made bookings. 

Ally
