### ISSUE TITLE
show_invoice_seller not displaying {COUNTRY}

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#356]
show_invoice_seller contains {COUNTRY} but view_invoice fails to display the value of country but does display other data of region & landline etc.

<div class="row">
		<div class="col-md-6">
			<strong>{HREGION}</strong>
		</div>
		<div class="col-md-6">
			{REGION}
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<strong>{HCOUNTRY}</strong>
		</div>
		<div class="col-md-6">
			{COUNTRY}
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<strong>{HLANDLINE}</strong>
		</div>
		<div class="col-md-6">
			{LANDLINE}
		</div>
	</div>
Issue is that Country needs to display in address shown on invoice

**Comment by allynat** [comment]
To confirm - wordpress- 9.16.1

**Comment by jomres** [comment]
Do you have data saved in the "Your company details" tab of property config?

**Comment by allynat** [comment]
Yes Vince

**Comment by jomres** [comment]
Is this still an issue, Ally?
