### ISSUE TITLE
Provisional Bookings Handling plugin

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#358]
9.16.1

Settings-Site Configuration-Cron jobs settings and logs 

Text says "This plugin runs automatically in the background and sends a payment reminder email to guests that that made provisional bookings which are not marked as paid within an interval of your choice. This is useful when you accept bookings that are paid using offline payment methods (wire transfer, cheque). If a booking is not paid within X number of days from the time when the booking was made, then a payment reminder email is sent to the guest. You will also receive a copy of it. If you also use the Provisional Bookings Handling plugin, then make sure the interval at which you want to send the payment reminder email is at least 1 day lower than the one set for deleting or cancelling the unpaid booking."

Provisional Bookings Handling plugin is not featured on the available plugin list.

Issue is that the Provisional Bookings Handling plugin is possibly referring to the Payment Reminder plugin and if not then where is the additional plugin?

**Comment by jomres** [comment]
Refers to payments reminder plugin
