### ISSUE TITLE
Safari browser - Excel export button fails in listing pages

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#361]
9.16.1
(It's been like this for 5 years already)

When listing Properties, Bookings, Guests & Invoices, the button display above the listing shows 6 buttons.

Using Chrome, Firefox on Mac, all 6 display and function correctly.

Using Safari on Mac shows, 6 buttons are displayed but the dt-button buttons-excel buttons-html5 is smaller and does not show text "Excel" and when clicked does not function as it should and does in other browsers.

Issue is that Mac using Safari, displays a smaller blank and non functioning Excel export button.

**Comment by jomres** [comment]
Sounds like it could be this problem

https://datatables.net/forums/discussion/44789/export-button-pdf-and-excel-do-not-show-on-mac

**Comment by allynat** [comment]
Safari works fine on the link they provide

https://datatables.net/extensions/buttons/examples/initialisation/simple.html



So respectfully I would suggest it’s not Safari but Jomres :(

**Comment by jomres** [comment]
Anybody else with a mac able to replicate this? I don't have one.

**Comment by wordskill** [comment]
Yup.

Current Safari on current MacOS.

<img width="386" alt="screen shot 2019-02-05 at 2 29 03 pm" src="https://user-images.githubusercontent.com/3686911/52279934-97a8f400-2952-11e9-95c7-ea81c9803cf0.png">

<img width="1280" alt="screen shot 2019-02-05 at 2 29 38 pm" src="https://user-images.githubusercontent.com/3686911/52279946-9d9ed500-2952-11e9-97c0-00d8dac41a6f.png">

**Comment by jomres** [comment]
Is this still an issue? There have been some updates of various libraries that may well have resolved it.

**Comment by allynat** [comment]
Hi Vince

No it’s fixed now

Regards

Ally
