### ISSUE TITLE
List Property Categories -  _JOMRES_PROPERTY_HCATEGORIES

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#365]
9.16.1

Backend Settings menu item displays _JOMRES_PROPERTY_HCATEGORIES

At the top of  task=list_property_categories the same _JOMRES_PROPERTY_HCATEGORIES appears.

en-GB.php contains
jr_define( '_JOMRES_PROPERTY_HCATEGORIES', 'Property Categories' ); 

Issue appears to be a language file disconnect.

**Comment by jomres** [comment]
You would need to check for a sub-directory with the name of the property type, Ally. Add 

jr_define( '_JOMRES_PROPERTY_HCATEGORIES', 'Property Categories' );

to that language file and the issue should be resolved.

**Comment by allynat** [comment]
I have not defined a property type. In front end, the properties are uncategorized.

If I do, and create /jomres/language/subdirectory/new language file, the result is the same = _JOMRES_PROPERTY_HCATEGORIES appears in backend menu

Not sure why in backend, the language file of a property(s) not using or using the category option in Settings-Property details would not read the core language file.
