### ISSUE TITLE
404 error when saving account details for the first time

### ISSUE THREAD

**Issue by cristin** [WoollyinWalesIT/jomres#366]
Reproduction steps:
1. Create a new account
2. Try to buy a subscription
3. You will get redirected to "Edit account" form
4. Complete the form and press submit.

Actual behavior: The redirect link is not correct and you get to a 404 page.
Expected behavior: The redirect link is correct and you are redirected to "list_gateways_for_invoice" page.

Fix: Go to "j06005save_my_account.class.php" line 254 and replace: 
`$return_url = base64_decode($return_url);`
with
`$return_url = jr_base64url_decode($return_url);`

**Comment by jomres** [comment]
Thanks for the great issue report and including the solution.
