### ISSUE TITLE
improved customer communication 

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#367]
Here I am going to try to pose an idea of ​​development, maybe for JOMRES via our super Vince, or Rodrigo from JPD
My main idea is: Improve and master communication after booking - for check-in and check-out with the client, whatever the origin of the booking (jomres or OTA)

Currently for my part, I use JPD Email Enhancer to send the email after booking, but this email is only sent if the reservation is made from Jomres.
I also use an email generated by Acymailing, thanks to the integration of jomres. In this automatic email, I ask the customer to contact me by email, or whatapps, so that he informs me the information of check-in. And if I had to use acymailing to allow the customer to complete a form, then I would have 2 separate databases ... so not cool.

In fact I had the opportunity to test for 20 days the new application https://wishbox.co/

Here is what Jomres could do:

Automatic email after booking
Send an email to the customer, recalling the details of his reservation, prices, conditions, conditions of arrival, departure scheduled on JOMRES ... (what already does the JPD email enhancer of rodrigo) but also suggesting the customer to put in day the details of his pre-check-in, directly on JOMRES, via a redirect link.

At this point the customer could have his own customer area, with which he could communicate with us.

The customer can update, or complete:
- update or confirmation of his email address (I remind you that if the customer comes by OTA, often it is a temporary address assigned by the OTA which is filled)
- details of his means of travel (plane, train ...) and his expected arrival time at the airport, train station + his desired arrival time at the apartment
- ask him for a copy of his passport. Make it clear that the passport must match the owner of the credit card used for payment
- remind him that at check-in he will have to pay by credit card a deposit. At this stage Wishbox requires a copy of the bank card front ... I would rather recommend that the receptionist can enter in jomres, a pre-authorization stripe at check-in.

In the case where the customer did not fill in this information, an email can be reprogrammed, x days before arrival then Y days before arrival, if the information has not been entered

An email sent X days before arrival is also programmable, specifying to the client, the address of the apartment, the scheduled arrival time ... the name of the person who will come to welcome him

and why not an email during the stay, to validate the customer's satisfaction (reception, cleanliness, equipment, services)
 + this email request to confirm departure information (date, time ...)

An email after quality survey check-out (4 criteria, from 1 to 5 stars) and if everything is more than 4stars, then the customer is redirected to the site by which he made the reservation to put a comment. (booking.com, airbnb, google map and jomres)

To your keyboards to give your opinions and comments
(I'm doing another post to talk about the following on wishbox, which adds an upselling module!)

Hope to reading from you guys !

**Comment by jomres** [comment]
Basically what  you want is a complete new application that behaves as a ticket system, or a lead handling system, isn't it?

Instead of re-inventing the wheel, it would be better to see if there's a system like that already that we can hook into.

**Comment by jomres** [comment]
Insufficient support for feature request.
