### ISSUE TITLE
Extra are not charged in you untick them an tick them again

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#368]
since you give the ability for PM to untick or tick extra on booking form... i just see that the % commision charge extra are not charged again if you tick them again.
(the per day or booking are OK)
Can you replicate that on your own website ?

Jerôme

**Comment by jomres** [comment]
Nope, sorry, I can't replicate it. It's working as expected on my server. Anybody else seeing what Jerome's seeing?

**Comment by JeromePayan** [comment]
I am using jpd Valentina template... Does it could affect it?

**Comment by jomres** [comment]
Try uninstalling it and see.

**Comment by JeromePayan** [comment]
Hey vince, i have tried to uninstall the extra plugin and install it again... no change
Please find the vidéo

**Comment by JeromePayan** [comment]
Juste note this

If i configure the extra to per/night/person then i don't have anymore issue

This issue concern only % commission charge

**Comment by jomres** [comment]
That's what I tested.

**Comment by JeromePayan** [comment]
And remember that i still have the issue in jomres extra config, when i want to save it as FORCE, i need to do twice saving !

**Comment by jomres** [comment]
Jerome, I can't recreate this and nobody else is reporting it. I have a feeling that it's related to your server's particular setup but until we can figure out a way of re-creating it there's no way I can "fix" it.

I'm going to close this issue now but if anybody comes across it in their own installation please feel free to comment and re-open it.

**Comment by jomres** [comment]
Jerome, I can't recreate this and nobody else is reporting it. I have a feeling that it's related to your server's particular setup but until we can figure out a way of re-creating it there's no way I can "fix" it.

I'm going to close this issue now but if anybody comes across it in their own installation please feel free to comment and re-open it.
