### ISSUE TITLE
Register Link

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#369]
9.16.1

Not logged in visitor sees drop down menu with Register listed. 

cms_user_register can be set to nobody in Access Control but it has no effect, the link is still visible.

Issue is that the Register link cannot be hidden.

**Comment by jomres** [comment]
Is the Quick Register plugin installed? If so, uninstall it for that option to be added to the menu. The plugin unsets the menu option because it appear explicitly on the page in the form of the registration button

( took me bloody ages to track that down :D )

**Comment by allynat** [comment]
So sorry Vince, no the plugin was not installed.

However, I have installed it and weirdly the link is no longer visible despite cms_user_register  being Anybody.

So with the plugin installed and turned off, the link goes away without access control.

I have uninstalled the plugin again and switched cms_user_register to Nobody and again it still displays.

**Comment by jomres** [comment]
If you're logged in, the registration link would not be shown. Are you logged in?

**Comment by allynat** [comment]
No, please visit https://www.wildlifevolunteer.org/system

**Comment by jomres** [comment]
It could be a browser cache issue then, I can see the registration link here

https://snippets.jomres.net/2019-02-05-hlanb.png

**Comment by allynat** [comment]
Ok, I have just (before you saw it) changed the access level from Anybody to Super User.

If we try to change it to Nobody, the setting doesn’t get saved.

**Comment by jomres** [comment]
The plugin has been updated, please test and let me know how you get on.

**Comment by allynat** [comment]
Thats sorted

Thanks Vince
