### ISSUE TITLE
Availability Calendar - Clicked goes to blank page

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#370]
9.16.1

**Scenario**
Visitors cannot book online
Registered users only can book online
All bookings are created by manager for customer
Inline Availability calendar shown and in tab 

If not logged in as manager, and the user clicks on an available date, they are taken to a blank screen.

?option=com_jomres&task=dobooking&selectedProperty=3&pdetails_cal=1&arrivalDate=2019%2F02%2F24

Issue is that either the calendar should not be selectable for this scenario or that if it is clickable, the user is shown an error.

**Comment by jomres** [comment]
Got a screenshot for this Cal, Ally? Let's make sure I'm looking at the right one please Bud.

**Comment by allynat** [comment]
Both of these calendars

Thanks

Ally
