### ISSUE TITLE
jomres/assets/css/classic-loader.gif 404 (Not Found) - Chrome

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#371]
9.16.1

Viewing property details page on Chrome
?option=com_jomres&task=viewproperty&property_uid=3

Right click and Inspect, displays the following 

jquery.js?ver=1.12.4:3 GET xx/jomres/assets/css/classic-loader.gif 404 (Not Found)

But there is a loading.gif here
xx/jomres/assets/images/loading.gif

**Comment by jomres** [comment]
See that changeset Ally, should resolve it.

**Comment by allynat** [comment]
Sorted

**Comment by JeromePayan** [comment]
Maybe can be add to changeset

I found some URL redirection on joomla

jomres/images/ajax_animation/broken_circle.gif 
----> correct is /jomres/assets/images/ajax_animation/broken_circle.gif | 

AND 

jomres/images/noimage.gif 
------> correct is jomres/assets/images/noimage.gif
