### ISSUE TITLE
Label Editing mode OFF still appear in Dashboard 

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#372]
Hey guys !

I switched off the Label editing mode in jomres user control with  "switcheditingmode"
But the option it is still available on the PM dasboard... But cannot save to on

Vince Can you make sure the option does not appear ?

Merci

**Comment by jomres** [comment]
Is your user a super manager? IIRC that dropdown will still remain for super managers, but not for normal managers when you select that option.

**Comment by JeromePayan** [comment]
All PM, even non super managers can see the Label editing mode dropdown. But they cannot save the mode ! can be confusing for them to see an option non usable

**Comment by jomres** [comment]
Jerome, on reflection it looks like that setting may have been removed. Can you show me a screenshot of your setting in context?

**Comment by JeromePayan** [comment]
here a screenshot in full sceen mode. the label editing option is OFF but the dropdown menu still appear
(same things in the normal view)
![labelediting-off-fullscreen](https://user-images.githubusercontent.com/25484155/52704374-ae69cf00-2f80-11e9-8167-207a253edaa1.PNG)

**Comment by jomres** [comment]
I was referring to the setting in the admin area, Jerome.

**Comment by JeromePayan** [comment]
That one in user access ?
![labelediting-off-fullscreen2](https://user-images.githubusercontent.com/25484155/52955857-13ad2e00-338e-11e9-8fad-71da96f575f9.PNG)

**Comment by jomres** [comment]
Jerome, Access Control wont prevent that dropdown from showing. The dropdown used to be managed by another setting-

**Comment by JeromePayan** [comment]
Vince, how can we do it not showing ?
