### ISSUE TITLE
Editing email templates - br stripped if save in Visual tab(WP)

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#373]
9.16.1
Wordpress

Backend Input filtering set to weak and contains
p,b,strong,a[href],i,br,em,table[width],table[border],tr,td,th,img,h2,h3,h4,li,ul

If editing a template and wanting to use a line break using br or br / saving the template in text tab mode retains the line return.

But if saved or Viewed in the Visual tab mode, br or br / (or p if trying to use) are lost but all other tags are saved.

Issue is that email text loses line breaks if saved in Visual tab.

**Comment by jomres** [comment]
Offhand it sounds like the Visual tab is converting brs to maybe linebreaks, Ally. Is that correct?

**Comment by allynat** [comment]
Believe so 

But if saved without br in text then it wraps upwards in the resulting content

Ally

**Comment by jomres** [comment]
If the javascript editor is stripping line breaks, there's not a lot that Jomres can do to re-add them, Ally.

**Comment by allynat** [comment]
Thanks for following this one up.

I am working around this one.

Cheers

Ally
