### ISSUE TITLE
Update Hide Address Feature

### ISSUE THREAD

**Issue by TravelCubaOnline** [WoollyinWalesIT/jomres#375]
Hi Vine;
    I was thinking in this option to, and I saw the option you show here, but this option is good if Site Admins also work as Booking Central.
    What happens if site admins, don't want to do this and just hide the address until the booking is complete? and leave all relationship between Host (Property Managers) and future Guests
    Can you update this feature, pleeeeeease!

Update is about to include Phone number in this option.

It's not a bad idea. Can you add it as a feature request here please, so that I don't lose it?

**Comment by jomres** [comment]
IIRC this was added a while back.
