### ISSUE TITLE
New Feature: Booking by Time.

### ISSUE THREAD

**Issue by TravelCubaOnline** [WoollyinWalesIT/jomres#377]
Hi Vince;
I don't know if this new feature has been requested before, but I will mention it here.
Jomres (Thanks for this great tool) is a super flexible tool for booking online, and that means it can be used to book from Rooms to Bikes or Restaurants tables, etc.
Not all "Room types" are booked the same way, and here is a practical example:
For a multi property portal, a restaurant can be added, and room types become in Tables, so for a Double Room it could be Table for two.
In this scenario, a table can't be booked all day/night, the solution will be create multiple tariff with name like "Table for two at 7 pm", "Table for two at 8.30 pm" etc.
What happen if instead of doing that, we could have the availability to configure "Time Slots" for a Table?

Another example will be Boats, or jet skis, or any other "property" that can be reserved for a period of time, for example, one hour, two hours, etc.

Please let me know your opinion on this feature.

Y.

**Comment by salesbluejaypm** [comment]
I'm looking for a program/plugin just like this one for Jomres? 

I would use this "Booking by Time" plugin everyday for my small business.

I think if this plugin was available more people would sign up with Jomres and use it for their small family business that needs appointments during the day, and NOT all day.

Thanks for adding this to the Feature request list.

**Comment by rubenkincade** [comment]
Built it and they will come! :-)

**Comment by florescamila** [comment]
Having a New plugin for "Booking by Time" would be great for businesses that run with daily appointments like Clinics, Spas, Hair Stylists, Personal Trainers, Hair & Beauty Salons. etc.

**Comment by CharlesMason** [comment]
I can't vouch for it but there IS a plug-in for this:  https://geitawi.com/plugins-list/plugins/booking-customizations/time-slot-reservation

**Comment by lopezacuba** [comment]
> I can't vouch for it but there IS a plug-in for this: https://geitawi.com/plugins-list/plugins/booking-customizations/time-slot-reservation

This plugin cost to much money. Vince can make it and add it to his many plugins. This would bring more customers to Jomres.

**Comment by jomres** [comment]
Sorry, I shan't be adding this feature.

**Comment by CharlesMason** [comment]
Glad to see you guys still handling these items.  Stay on it! Thanks for the continued support!
