### ISSUE TITLE
Extending subscriptions

### ISSUE THREAD

**Issue by joejoe2010** [WoollyinWalesIT/jomres#378]
Hi,
I would like to extend the subscription feature to depending on the subscription package limit or not
a) to only create properties of type "No bookings/Real estate ( simple listing )" or (if enabled in package) being able to create properties of all types (Rooms in the property, Entire property, Tours)
b) showing the availability calendar (probably goes together with, probably goes hand-in-hand with e)
c) the number of images to show / upload in the media center. Alternatively to allow by default only the main image and logo or (if enabled in package) allow unlimited number of images
d) being able to appear as "Instant booking", if this option is not included in a package then making a booking should not be possible but only "Request reservation via e-mail or phone"
e) Being able to appear in a special list that I create, something like "all properties that offer candle light dinner"
f) being shown in the map

If you don't see a high priority for this and therefore don't want to implement it: If I create a pull request with the changes, would you be willing to integrate/merge these changes into the main code? If I know well the subscription plugin is not part of this repository so code changes would also be needed in other repos?

Greetings
joejoe

**Comment by jomres** [comment]
That's right, none of the plugins are in this Repo.

Those are all great features but I'm snowed under with other requests (and Ally's fervent bug reporting (love you Ally)) so if you'd like to raise a ticket with the changes in, fire away! I'll review them and offer suggestions before adding them to the code.

Does that sound ok?

**Comment by joejoe2010** [comment]
Thanks for letting me know.
