### ISSUE TITLE
generating invoices as pdf

### ISSUE THREAD

**Issue by joejoe2010** [WoollyinWalesIT/jomres#379]
Hi,
in my country it is necessary to store receipts for years and if I'm well informed also in a format that is not editable. So I'm wondering if it's possible to generate each receipt invoice of a room booking as a pdf on the webspace and send them as attachment via mail to the super user, the property manager and the customer/guest. Same applies to subscription invoices that property managers pay to the super user.
(If I have the pdfs on my webspace I can easily back them up via akeeba backup and/or ftp)

I read on the forum that a jomres-user once made a plugin but I'm not sure if this is still available/up-to-date.

Are there plans to integrate pdf-invoicing into jomres core? (I saw that it's already possible to generate pdfs of tables but not of invoices).

Thanks
joejoe

**Comment by jomres** [comment]
See the pdf related functionality added yesterday.
