### ISSUE TITLE
Search with price range in Frontpage search m1 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#38]
https://www.jomres.net/forum/Feature-requests/24724-search-with-price-range-in-frontpage-search-m1

Hello,

the frontpage search (leothian template) can be configured that a price range is displayed, but sadly this information is not passed over to the ajax search.
I was really suprised that you can enable the price range in the options of the module, but this option has no effect.

Therefore I suggest that all information which can be configured in the search module options should be passed to the ajax search. (From my perspective this is more a bug than a feature request...)

Denis

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Closed due to lack of support.
