### ISSUE TITLE
Invoice numbers - Not displayed in lists

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#381]
9.16.1

The facility to have custom elements to invoice numbers is great.

com_jomres&task=list_invoices displays invoice numbers
com_jomres&task=list_bookings does not display invoice numbers but shows invoice_uid

Issue is that managers cannot view Invoice numbers in list property bookings

**Comment by jomres** [comment]
Thanks Ally. Update to nightly blahblahblah to test changes etc. 

https://www.jomres.net/manual/installation-and-upgrading-2/370-installing-updating-to-the-nightly-branch

**Comment by jomres** [comment]
Link to nightly for other observers, I know you know the drill

**Comment by allynat** [comment]
Just going to watch the greatest show @ 12 in the UK & have a laugh at the overpaid politicians doing stand up comedy!

I will let you know later ;)

Ally

**Comment by jomres** [comment]
<check's date> Is it PMQs time again?

**Comment by allynat** [comment]
Yep

Ally

**Comment by jomres** [comment]
Not sure if I can face another hour of the old trout saying sweet FA of any value or substance.
