### ISSUE TITLE
Portal Functionality - Reviews

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#382]
9.16.1

Backend, Settings - Portal Functionality - Reviews

All options set to No

com_jomres&task=mulistbookings displays a link to Add a new review

Clicking the button goes to blank page

Issue is that if Reviews are not required, the setting is not stopping the appearance of the button in mulistbookings and a template override is unnecessarily required.

**Comment by jomres** [comment]
Thanks Ally.

Waiting for  your next report 👯‍♂️

**Comment by allynat** [comment]
Done!

Thanks Vince
