### ISSUE TITLE
Currency Format - various displays

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#385]
9.16.1

Settings - Property Configuration - Tariffs & Currency - Currency Format = 123456
Settings - Property Configuration - Bookings - Round deposit up to nearest integer? = No
 
Tariff - Advanced
3 weeks = 276.67 because only 2 places held.
Actual rate per week for 3 weeks is 830 

Booking Form
Tariff for 3 weeks displayed as 277
Calculated Grand Total shows 830

Invoice
Line Items show 830
If Invoice is marked paid then Transactions show Price & Total 830.01

Quick resolve is to increase _jomres_rates roomrateperday from double 11,2 to double 11,7 and be allowed to store 276.6666667

This shows invoice transactions correctly and yet Tariff display in booking form still shows 277.

Issue is that to achieve a correct invoice, for a room that is discounted on a weekly basis, the booking form rounds the display up and the database table needs a structure change to allow the Settings - Property Configuration - Tariffs & Currency - Currency Format = 123456 to show consistently true throughout the site.

**Comment by jomres** [comment]
Next version will have 11,7 for the rates table. Given the age of the issue it's possible that other changes may have affected the output so if that's still a problem please raise it here https://jomres.canny.io/bug-reports
