### ISSUE TITLE
_jomres_mangers - users_timezone

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#386]
9.16.1

(been the same for 5 years)

If a new cms user is created and a manager is assigned, the _jomres_mangers - users_timezone is set to a default value "Europe/Berlin"

This value is not able to be changed from within Jomres and each user needs manually adjusting via phpMyAdmin to their local timezone.

Issue is that bookings made by managers show time booking made as the default time zone until manually changed in the db.

**Comment by allynat** [comment]
A little update

I have been monitoring this after recent changes to this version of Jomres and note the wording in the original issue was ambiguous..

> Issue is that bookings made by managers show time booking made as the default time zone until manually changed in the db.

The change to a new timezone in the manager table makes no difference to the timestamp. What ever the timezone is set to, the timestamp appears to consistently record UTC.

**Comment by jomres** [comment]
All bookings are assumed to be UTC, regardless of the user's tz.
