### ISSUE TITLE
Manager added bookings - email too long 

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#387]
9.16.1

Adding several bookings with Danish names as a manager, I am adding their full name to the front of the office email to ensure some hope of uniqueness.

On Confirm Booking, I get error - this has been reported ...

If I hit back and amend the email to only contain some of the unique name, I can confirm booking without error.

If I list bookings, I see both bookings. The error & the shortened email version.

I now cancel the error version of the booking.

If I now recreate the same error & cancel the error bookings (several times) with more unique emails, , when I list bookings, I see all bookings that were cancelled due to the error, show guest details of the most recent error guest. 

If I list guests I see the first instance of the error scenario as guest_uid 9 and this guest record has the latest error guest details in place of the original.

If I look at the contracts table, all records that experienced this error have guest_uid 9

Issue is that a booking / guest is created, despite the email being too long and causes conflict with other guests and contracts. Jomres should not create contracts & guests at this point and hitting back button should not be allowed after clicking confirm booking.

**Comment by jomres** [comment]
How long is the email, Ally?

**Comment by allynat** [comment]
Hi Vince (on a Sunday !! Shhh)

MarielleAgathaMargarethaSnoekerofficebookings@wildlifevolunteer.org <mailto:MarielleAgathaMargarethaSnoekofficebookings@wildlifevolunteer.org>

Crazy I know but I need something simple to work with and full name & office email is practical.

I could shorted officebookings@ but how long can a name be needs defining somewhere:(
Cheers
Ally

**Comment by jomres** [comment]
What does the error log say?

**Comment by allynat** [comment]
Here is the common error

Error logged Database error more than one result returned. One expected. Stop. <a href="https://www.wildlifevolunteer.org/system/index.php?option=com_jomres&page_id=5&task=show_logfile&logfile=tnfovrGaprmtTTxRFfulVjUDfiuWOK.html"> Logfile </a> https://www.wildlifevolunteer.org/system/?option=com_jomres&task=confirmbooking 2019-02-24 07:22:24 180.183.200.137 Message: <strong>Database error more than one result returned. One expected. Stop.</strong>   	File: /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/libraries/jomres/functions/database.php<br /> Line: 48 Trace: #0 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/libraries/jomres/classes/jrportal_invoice.class.php(167): doSelectSql('SELECT\n\t\t\t\t\t\t`e...', 2)<br /> #1 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/libraries/jomres/classes/jrportal_invoice.class.php(113): jrportal_invoice-&gt;create_pii_buyer()<br /> #2 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/core-minicomponents/j03025insertbooking_invoice.class.php(372): jrportal_invoice-&gt;create_new_invoice(Array, Array)<br /> #3 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/libraries/jomres/classes/mcHandler.class.php(152): j03025insertbooking_invoice-&gt;__construct(Array)<br /> #4 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/core-minicomponents/j03020insertbooking.class.php(671): mcHandler-&gt;triggerEvent('03025', Array)<br /> #5 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/libraries/jomres/classes/mcHandler.class.php(152): j03020insertbooking-&gt;__construct(Array)<br /> #6 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/libraries/jomres/functions/functions.php(3191): mcHandler-&gt;triggerEvent('03020', Array)<br /> #7 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/core-minicomponents/j06000processpayment.class.php(79): insertInternetBooking('LbhBjPMVowhnyNV...', false, true, '')<br /> #8 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/libraries/jomres/classes/mcHandler.class.php(217): j06000processpayment-&gt;__construct(NULL)<br /> #9 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/jomres/jomres.php(279): mcHandler-&gt;specificEvent('06000', 'processpayment')<br /> #10 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/wp-content/plugins/jomres/includes/functions.php(118): require_once('/var/www/vhosts...')<br /> #11 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/wp-content/plugins/jomres/includes/functions.php(103): jr_wp_trigger_frontend()<br /> #12 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/wp-content/plugins/jomres/public/jomres-public.php(80): trigger_jomres()<br /> #13 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/wp-includes/class-wp-hook.php(286): Jomres_Public-&gt;frontend_trigger_jomres(Object(WP))<br /> #14 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters('', Array)<br /> #15 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/wp-includes/plugin.php(531): WP_Hook-&gt;do_action(Array)<br /> #16 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/wp-includes/class-wp.php(750): do_action_ref_array('wp', Array)<br /> #17 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/wp-includes/functions.php(1105): WP-&gt;main('')<br /> #18 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/wp-blog-header.php(16): wp()<br /> #19 /var/www/vhosts/vps299483.ovh.net/wildlifevolunteer.org/system/index.php(17): require('/var/www/vhosts...')<br /> #20 {main}    




Ally

**Comment by jomres** [comment]
That's not a password length problem.

In the __jomres_guest_profile table, check that that particular user doesn't have more than one row for that user's CMS id. Somehow you've got a duplicated user in that table and that's what the cause of the problem is.

**Comment by allynat** [comment]
Ok, here are 2 screenshots of wp_users and the jomres_guest_profile

I am mos_userid 1 in CMS & Master ID1 and am the creator of the contract & guest_uid 9

**Comment by jomres** [comment]
Raise a ticket please Ally.

**Comment by jomres** [comment]
This has been resolved and the change is in 9.17
