### ISSUE TITLE
 Show Booking form in property details page? - Stuck

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#390]
9.17
Wordpress

If "Show Booking form in property details page?" is set to YES the result is correct

If the setting is then changed back to NO, non logged in users cannot view property details page unless forcing the url to include task=viewproperty&property_uid=1

Have cleared caches & used various browsers.

**Comment by jomres** [comment]
Is that possibly caused by their session data? What happens if you empty the sessions table contents after making that change?
