### ISSUE TITLE
Amazon Payments Gateway

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#392]
Dear Vince,

after comparing the fees and conditions of several payment service providers (Paypal, Stripe, Worldpay...) I think it would be great to also have an Amazon Payments gateway as the conditions (our business is based in Germany, but we have customers all over Europe) are much better (lower fees) than those from Paypal or Stripe. Especially for cross border bookings there is a huge difference in the fees being charged by the different payment service providers. 

For instance if the monthly payment volume of your business is 5.000,01 EUR to 25.000,00 EUR, the fee you would have to pay to Paypal (as of today, 14th March 2019) for a transfer from a customer from another EU country like Austria, Spain, France or Italy is 1,99 % (merchant rate) + 2,0% (cross-border fee) + 0,35 EUR (authorisation fee) = 3,99% + 0,35 EUR. So for an 1000 EUR booking from a customer in Austria the fee is (incredible...) 40,25 EUR. See: [https://www.paypal.com/de/webapps/mpp/ua/useragreement-full?locale.x=de_DE#16](url)

With Amazon Payments (monthly payment volume also 5.000,01 EUR to 25.000,00 EUR) the fee would be 1,7 % + 0 % + 0,35 EUR = 1,7% + 0,35 EUR. So for an 1000 EUR booking from a customer in Austria the fee would be 17,35 EUR. This is only 43,11 % of the fee that Paypal demands. Especially the cross-border fee that Paypal demands hurts a lot. I know that the fees that Amazon Payment charges also differ quite a lot per country (i.e. if your business is based in Spain they are not as attractive as if your business is baded for Germany or France). 
See:
[https://pay.amazon.com/de/help/SKX7JCY3G3SP73U](url)

If you are to busy yourself this might also be a topic for Rodrigo (Jomres plugins & development)?

I will also check some more payment service providers because the fees that Amazon Payments charges are from my point of view still extremely high for an automated service.

Thank you in advance! Best wishes, René

**Comment by rrmdp** [comment]
Hi René, unfortunately I do not have the time to develop the plugin.

  Best regards, Rodrigo.

**Comment by jomres** [comment]
Insufficient support for feature request.
