### ISSUE TITLE
Template Package Property Header Cover

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#393]
Version 0.2
9.17

Upload of image with space in file name causes upload to succeed and image shown in front end media centre but the image is not shown in the header.

Remove the space in file name, the image is shown ok.

This behaviour is not seen in the slideshow upload & view.

**Comment by jomres** [comment]
This fixes it

https://github.com/WoollyinWalesIT/jomres/commit/5ed774831e7948f75933285d1cd1d7240f83a759

Spaces etc can be problematic, so it's best to remove them altogether when uploading images.
