### ISSUE TITLE
Possible performance improvements

### ISSUE THREAD

**Issue by joejoe2010** [WoollyinWalesIT/jomres#394]
Hi,
I ran a scan of my own jomres-installation (using joomla) and also of the http://joomla-portal.jomres.net/en/ demo page using https://gtmetrix.com to find some performance bottlenecks.

See https://gtmetrix.com/reports/joomla-portal.jomres.net/yuBfyWvK
I know that your demo-page probably isn't optimized so much for performance (eg. gzip-compression is missing) but some other findings might be valid a consideration in general.

One thing it marks is "Defer parsing of JavaScript" 591.3KiB of JavaScript is parsed during initial page load. Defer parsing JavaScript to reduce blocking of page rendering.

Alternatively it might be a good idea to get bootstrap, jquery and other general stuff from a google cdn instead of the own server as the one from google probably already was loaded before from another site and therfore already is in the browser.

Another issues are "Minimize request size" and "Specify a cache validator" - they are related to the stuff from maps.googleapis.com. Do you have an idea how this could be improved?

Best regards
joejoe2010

What do you think?

**Comment by jomres** [comment]
I think that this is more of a site level question, rather than a Jomres level question, Joe. Aside from CDNs (which I like, but don't feel it's practical for Jomres), there isn't a hell of a lot I can do. I've tried several times to implement caching of js & css files, with varying levels of success. Right now, I'm pondering re-attacking the problem sometime again.

**Comment by ReneCB** [comment]
Maybe check "Admin Tools Professional" (current version is 5.3.1) from the same developer who develops Akeeba Backup. 
You can define in the ".htaccess Maker" there for your installation (apart from the useful WAF):

- Automatically compress static resources (Enabling this option instructs the server to send plain text, HTML, XML, CSS, XHTML, RSS and Javascript pages and files to the browser after compressing them with GZip. This significantly reduces the amount of data transferred and speeds up the site.)

- Force GZip compression for mangled Accept-Encoding headers

BTW: Admin Tools Professional and Akeeba are offered for Joomla and WordPress.

Best wishes,
René
