### ISSUE TITLE
Responses to issues update

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#398]
This is just a quick note for all folks to let them know the reason why addressing issues raised has slowed down in the last month or two.

There are a number of factors, primarily that I'm working on crafting a new channel manager framework (CMFW) for Jomres. I'm building it in such a way that each remote channel would be a plugin for the channel manager framework, the goal being that it be relatively easy to integrate multiple channel manager handling functionality into one Jomres installation. As you can appreciate, this is a huge task and is requring a lot of careful thinking.

Secondly, I'm exhausted. I've been doing this now for 14 years and tickets, minor bug reports and real life all take their toll. Jomres itself is robust, there aren't any major bugs in the system therefore the CMFW aside I'm not planning any major releases of Jomres in the next few months, although the CMFW might cause a few small changes here and there. Naturally if any vulnerabilities in Jomres or it's libaries come to light then a new release would happen fast, as always. 

Sure, Jomres is not perfect, as somebody who handles support tickets every day I'm very aware of that, but the documentation is (mostly) coherent. There's one annoying that has a fix in the Nightly (https://github.com/WoollyinWalesIT/jomres/commit/5596a3aeed3a33542198f3be4d6d917f30f18cfc) that will prompt a minor release soonish, but that's it.

**Comment by JeromePayan** [comment]
Hey vince ! thanks for all your job. It's a great job ! And we have only life, so take it easy.

Channel management framework for my point of view is very important

I am connecting jomres with beds24, so if you need help or information about needs... let me know

Best regards,

Jérôme
