### ISSUE TITLE
Clone resources

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#40]
https://www.jomres.net/forum/Feature-requests/24232-duplicate-resource

I dont wand duplicate pictures, pictures once attached to the master room, shall be used. I love micromanage tarif, but than duplicating rooms is a very hard job, causing many mistake, and wasting time. To me even it lloks like i am wrong sitting and klicking room features, attaching picture to each room. Some hotel have more than 100rooms. I will never get a hotel manager doing this. But may be i dont understand.

**Comment by alibarthi** [comment]
Room images can`t be cloned, but this changeset will solve the cloning problems. When cloning, room type, name, number, floor, room features, etc will be automatically populated. Saving will create a new room. [https://github.com/WoollyinWalesIT/jomres/commit/8cce2dd59122e64f4f4a94e90bae08d4882bff11](url)
