### ISSUE TITLE
Print coupons layout fix for Bootstrap 3

### ISSUE THREAD

**Issue by mauriciosalguero** [WoollyinWalesIT/jomres#401]
Current QR code is overlaping the  promo paragraph,

This can be solved by adding the class `img-responsive` to the tag img and changing the bootstrap  columns  to 3-5-2-2 instead of the current 2-6-2-2

![2019-04-24 10_38_58-Reserva](https://user-images.githubusercontent.com/48019716/56673333-b11e2a00-667d-11e9-8148-409c052cc792.png)

![2019-04-24 10_44_03-Herramientas de desarrollo - Reserva - https___hotelsantacruzcorferias com_es_nu](https://user-images.githubusercontent.com/48019716/56673446-e7f44000-667d-11e9-979b-c9cefad36a40.png)

**Comment by jomres** [comment]
Thanks for letting me know, that plugin has been updated.
