### ISSUE TITLE
Add Invoice as pdf to Email

### ISSUE THREAD

**Issue by getcarsten** [WoollyinWalesIT/jomres#402]
Please Add the Invoice.pdf to the Confirmation Emails.

Best solution would be a shortcode for email templates, but it would even be great as a standard

**Comment by JeromePayan** [comment]
Por fovor ?
Can Rodrigo add this option to in JPDemail-Enhancer ?
Merci

**Comment by getcarsten** [comment]
Hi Vince,

I already ask Rodrigo. He i full of work and couldn`t do it.

Regards

Carsten

**Comment by rrmdp** [comment]
Hi, I will add Jomres default pdf functionality to JPD Emails Enhancer plugin asap.

**Comment by JeromePayan** [comment]
Hey Rodrigo,

Sauf erreur de ma part, dans la nouvelle version de jpd email enhancer, only booking condition is sent to guest, can you add the invoice to ? and could you make the PM receving this info too?
Best regards,
jerome

**Comment by rrmdp** [comment]
Hi Jerome, sorry but I am not planning to add a pdf invoice to the plugin. As said I've added support for the Jomres core pdf functionality to the [JPD Emails Enhancer plugin](https://www.jomres-plugins.com/jomres-plugin/jpd-jomres-emails-enhancer#plugins)

**Comment by jomres** [comment]
Feature was added earlier this year.
