### ISSUE TITLE
Edit System Emails

### ISSUE THREAD

**Issue by getcarsten** [WoollyinWalesIT/jomres#405]
There as several Emails send by the System, wich could note be customiced or disabled.

Eg.: Registration new property, confirmation new property, unpaid bookings, payment reminder

They are comming even with wrong translations. By editing the translations you are unable to set a "br" . The result is an urgly email, nobody want to read.

Please make it editable like the owners mails.

**Comment by jomres** [comment]
Insufficient support for feature request.
