### ISSUE TITLE
Add tariff configuration column

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#411]

**Comment by JeromePayan** [comment]
Hey vince, can you add option column in tariff configuration list

as shown in screen shoot

Merci
![extra_option_tariff](https://user-images.githubusercontent.com/25484155/57514069-ebd7c180-730f-11e9-8f1a-cd09933a601b.PNG)
![tariff_details_configuration](https://user-images.githubusercontent.com/25484155/57514070-ebd7c180-730f-11e9-9ff9-903c69939ed7.PNG)

**Comment by JeromePayan** [comment]
By the way... i really need a extra person charge option for property (#251). If you are working on channel manager module, you will need to add this option too because channel are asking this option.
I know you did it for room configuration tariff...
Hope you will find time for that.

**Comment by joniale** [comment]
The problem managing prices would be reduced if Jomres implement a way to use the php API for managers. Coding the tariffs using php may sound complex but it is faster and easier than using the GUI. More important, it allow you to create scripts and batch massive modifications for many tariffs.
See my other ticket requestint this API. https://github.com/WoollyinWalesIT/jomres/issues/396#issue-430076536

**Comment by jomres** [comment]
> Coding the tariffs using php may sound complex but it is faster and easier than using the GUI. More important, it allow you to create scripts and batch massive modifications for many tariffs.

I absolutely agree. It's on my "when I get around to it" list.

**Comment by jomres** [comment]
https://api.jomres.net/#a30bc15c-4e9a-44dc-af81-21dba616710c
