### ISSUE TITLE
email new user with user account details template

### ISSUE THREAD

**Issue by joniale** [WoollyinWalesIT/jomres#412]
Hi Vince,

There are some webpages that the do not have the frontdoor jomres page visible on their web or in the main page. Those pages would need to have another email new user account information.

The default jomres email with the information of the new user account have the following information:
-----------------------------
Sehr geehrte(r) <GUEST_NAME>

Vielen Dank für die Registrierung 

Ihr Benutzername lautet: <GUEST_EMAIL>

Ihr Passwort lautet: <GUEST_PASSWORD>

Um Ihre Buchungen anzusehen, loggen Sie sich bitte unter folgender Adresse ein: <PROPERTY_WEB>
-----------------------------

It would be nice (and in some cases required) to **modify this email template**. This could be added to the other email templates jomres already have.
In my case, i would like to add another <PROPERTY_WEB> and include pictures explaining how the client can access his dashboard.

Would it be possible to modify this email in future jomres versions?
Thanks

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/historic-github-issues/p/email-new-user-with-user-account-details-template
