### ISSUE TITLE
Review Reminder - Please add multilanguage support

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#415]
Dear Vince,

It would be great if you could add multilanguage support to the "Review Reminder" plugin.

For instance it would be great if the guests get the review reminder email in the language in that they have booked. Currently all mails go out in English even if the guest booked via the German site version /de. 
I already added a German language file under  
.../jomres/core-plugins/review_reminder/language/
which I can also find considered under "Translations" / "Translate Lang File Strings" in the Jomres backend but all mails go out in English.

Also I would suggest to set the font sizes in the two files
.../jomres/core-plugins/review_reminder/templates/bootstrap/review_reminder_email.html
.../jomres/core-plugins/review_reminder/templates/bootstrap3/review_reminder_email.html
from 11px to 15px as 15px "nearly" equals font size 11 which I think is far better for an email than (the very small) font size 8.5 which equals 11px. 

Naturally I would be happy for every +1 from supporters of this idea.

Best wishes,
René

**Comment by jomres** [comment]
Rene, is this still an issue?
