### ISSUE TITLE
Feature request: Copy current year prices to next year / season

### ISSUE THREAD

**Issue by ReneCB** [WoollyinWalesIT/jomres#416]
Dear Vince, 

As we are just inserting the prices for 2020 I notice that it would be great to have a feature "Copy current year prices to next year" as many owners just leave the 2019 prices the same for 2020. This would simplify this work enormously. 

Also it would be good if one could see the prices of the whole current year under "Settings" / "Tariffs" to have it more easy to see / keep track how the prices in the beginning of the year were when the prices for the next season are entered (which for us is normally in June as the flights for the next year are normally published by the airlines then).

Thank you very much for consideration. 
Kind regards
René

P.S.: Every "+1" to support this feature request welcome ;-)

**Comment by joniale** [comment]
I think this is also a good feature, and moreover I think this could also be done using the prices API feature requested on the ticket https://github.com/WoollyinWalesIT/jomres/issues/396#issue-430076536.

**Comment by CharlesMason** [comment]
This could be done with a simple JavaScript, copying the rates from the fields to the new fields, so long as the old rates are on the same page as the new rates.

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/feature-requests/p/copy-current-year-prices-to-next-year-season
