### ISSUE TITLE
Strong Customer Authentication (SCA), a new European regulatory requirement that will require two-factor authentication on many online payments beginning 14 September 2019

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#417]
Hello Vince,

In september 2019 Stripe as us to be sure our API or plateform will be ready SCA for EU user
This is no more an option for us, and this is a good news to insure payment (like I asked #319)

Can you confirm to us that you are working on it to be plugin ready for that SCA? Stripe is asking me to answer several times how i management payment.

Here the entire information
https://stripe.com/docs/strong-customer-authentication

As i remember we are using the stripe check-out app

By the main time, will you be able to use the new and lovely Check-out stripe screen ?
![image]
(https://user-images.githubusercontent.com/25484155/59503002-94dd8300-8e9f-11e9-8972-8845a0cb589e.png)

Best regards to all of us

**Comment by JeromePayan** [comment]
And if you need to work on this plugin, can you make the credit card payment information save in Stripe. This is an option available in stripe to allow us to charge guest in the future. for ex. to capture a deposit upon arrival.
Jerome

**Comment by JeromePayan** [comment]
Hello,
Do am i the only one working in the EU community and working with Stripe ?
D-19
Jerome

**Comment by jomres** [comment]
This is WIP, however I'm waiting on other parties to resolve some issues. It requires adoption of some completely new technology from Stripe.

**Comment by JeromePayan** [comment]
Ok cool !

Sure you will do you best !

At the same time this will be great to integreate to jomres the new checkout that allow guest to choose some other payment method like applepay, googlepay, wechatpay, wisacheckout, sepa...
And get the lovely checkout popup like that one shown in the 
https://stripe.com/docs/payments/checkout

Best regards, 

jerome

**Comment by JeromePayan** [comment]
Vince thanks for you quick work on this plugin, to make it ready for SCA process !

I did the update and did a test in test_mode with jomres/stripe... looks working fine.
I did a real payment with my card... looks working well but i thinks, we need to wait a while. The processing operation in stripe took a while... with error message in stripe dashboard (not in jomres), but a second successfull payment was done. For your information, the stripe check-out did not ask me the confirmation code from my bank...don't know why.

Apart from this, you must consider this needs

In the new checkout  screen (jomres), there is no amount information to pay. Guest will need to be sure about the total amount to pay before performing the process

In the stripe dashboard

The jomres plugin does not send all this information to stripe, and this is a need to secure the payment and do a build a correct payment listing

- Guest name and surname and/or emailaddress 
- Guest adress to fill in the card information

- In Payment descrpition : you could add the name of the website and booking number for ex. zeperfectplace_jomres1245454 instead of the api payment information

Again thanks to care about this so quickly,

Best regards, 

Jerome
