### ISSUE TITLE
consider at best the minimum length of stay in the search results

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#424]
Vince, 

As you answered to me via the support website, to avoid making the search too long Jomrers does not take into account the length of stay requested by the customer. 

Also in the list of search results, jomres offers all the rentals that may be available.

But

For rentals that accept a stay of 4 nights (in my example), jomres displays the price with the plugin "Enhanced Property List Totals"

For rentals that do not accept a duration of less than 5 nights, jomres displays the property in the list, but without price.
In this case, it would be great, if jomres could display a message specifying the minimum possible night time, and list this kind of property at the end of the listing

Currently I have set a common message asking the customer to enter the dates in order to have an estimated price.

That an idea !

**Comment by jomres** [comment]
Insufficient support for feature request.
