### ISSUE TITLE
Automatic filling charges & payments on beds24

### ISSUE THREAD

**Issue by rent4natu** [WoollyinWalesIT/jomres#425]
Hello Vince.
Jomres does not allow to cash the balance of a reservation.
One solution would be to do it in auto action with beds24. 
But for that, it would be necessary that jomres automatically fill the charges & payments of beds 24 (as do airbnb, booking and more).
I hope that my request will hold your attention.
Thank.
![Capture d’écran 2019-09-24 à 14 02 39](https://user-images.githubusercontent.com/55848011/65705373-9a468e00-e088-11e9-9b14-31e921ed60a4.png)

**Comment by jomres** [comment]
I believe the Beds24 CMF REST API functionality should be able to do this.
