### ISSUE TITLE
New Jomres Guest Profiles link with social account ...

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#435]
Vince,

Some idea for For guest profile

- allow user to link the profile with his own social profile like google, facebook. For ex. I am using the JFBconnect component to to soo. I could be easier and more friendly for guest to connect again on my web site www.zeperfectplace.com

- In the guest profile screen points out in clear, with a few words, what is public and private because it's not clear for now.

- why do you want to show in that profile IBAN or driver licence ? This is real and very confidential information !

- Many doing a distinction/difference  with guest and Pmanager profile

Hope jomres user will add some more idea to developp this new jomres function

Merci

Jerome
www.zeperfectplace.com

**Comment by jomres** [comment]
1. That's outside the realm of Jomres functionality, you should use something like https://extensions.joomla.org/extensions/extension/social-web/social-display/jfbconnect/

2. Didn't you see that the panel is red and green, highlighting what's private and public?

3. It's optional, but things like this are often requested by hosts when somebody makes a booking so pre-filling this information is better to give the guest credibility. Remember that this information is encrypted in the database. Also, remember you can rename those fields for your own choices, if you wish. 

4. There's already a flag under the image that says if they're a manager or a guest, do you have any other ideas of what it can say?
