### ISSUE TITLE
Invoice not updated if dragndrop change of date

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#436]
9.20
If viewing a booking in Dashboard-Timeline and the booking is dragged to a new date, the invoice is not updated with the new date.

The booking (contract) is updated

If a booking is viewed and then Amended, and a new date selected, the invoice is updated.

**Comment by allynat** [comment]
To add to the issue, if the dashboard is viewed, a booking lozenge selected & dragged, there is no record in the audit log, there is no note made to view, so therefore anyone viewing the reservation detail only sees that there is a current status, the lozenge detail still shows the original detail.
![draggedbooking](https://user-images.githubusercontent.com/23444544/69912685-5cd2f800-145f-11ea-8d86-d0a82e31276c.png)

![Screen Shot 2562-12-01 at 17 17 16](https://user-images.githubusercontent.com/23444544/69912693-76743f80-145f-11ea-953c-9f26c1703bca.png)

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/historic-github-issues/p/invoice-not-updated-if-dragndrop-change-of-date
