### ISSUE TITLE
Deposit Payments - One Night Charge

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#437]
9.20
If expecting to take deposits for 1st night of booking, there is a fundamental lack of clarity in the documentation in the manual, which is also replicated in Settings-Property Configuration-Bookings tab

The 1st issue is that the 2nd sentence of the following is ambiguous.
"Prices are calculated on a per night basis. Do you want the deposit to be one night's charge? If so, you can ignore the following options."

The formula of the one night charge is the sum of (the price of each room in the booking), each being (divided by the number of rooms in the booking)

eg rooms cost 10, 20 & 30
The calculated deposit would be 3.333+6.666+10 = 20

Therefore not the sum total of the one night of all rooms in the booking. 

It would not be 60

This causes a huge loss for property owners if bookings are cancelled, especially for multinight bookings.

Jomres needs changing to allow for the sum of all rooms of the one night either by selection of the option or default of Jomres.

The documentation must be changed to allow necessary understanding of this current issue.

The 2nd issue is related. 
"Prices are calculated on a per night basis. Do you want the deposit to be one night's charge? If so, you can ignore the following options."

If the property is configured to take deposits of one night, then there is no trigger point at which full payment is demanded eg @7 days before arrival.

This further compounds the loss of money experienced by the 1st issue, as a booking cancelled at -3 days will likely result in the rooms not being sold again at such short notice & the deposit being withheld virtue of a cancellation policy, is not representative of the sum of all rooms for one night in the booking. 

This is not immediately clear from any documentation available.

"Prices are calculated on a per night basis. Do you want the deposit to be one night's charge? If so, you can ignore the following options."

If "...you can ignore the following options." is really ONLY available for % deposits, then the options visible below the selection of deposit method must be hidden and not visible.

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/historic-github-issues/p/deposit-payments-one-night-charge-2
