### ISSUE TITLE
Change the login link 

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#441]
9.20

Wordpress customer and manager login by default is /wp-admin

If we change this link to be /new-login to thwart hackers, then Jomres Login dropdown causes 404.

If we put in place a redirect plugin to 301 /wp-admin -> /new-login, it defeats the objective of stopping hackers targetting /wp-admin

To force Jomres to allow the new link we can amend:
jomres/libraries/jomres/cms_specific/wordpress/cms_specific_functions.php

```
function jomres_cmsspecific_getlogin_task()
{
return 'index.php?option=com_users&view=login';

```
to be 
```
function jomres_cmsspecific_getlogin_task()
{
return '/new-login';

```
However, we are forced to overwrite the core cms_specific_functions.php file and we are unable to put a customised file safe from upgrade overwrite.

**Comment by jomres** [comment]
What you really want then is a site config option to show the login page path?

**Comment by allynat** [comment]
I believe so, thereby offering wp the ability to handle the secret / custom url



Regards

Ally

**Comment by jomres** [comment]
Resolved
