### ISSUE TITLE
Stripe process fees and charges with (capabilities)

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#447]
Hey vince,

I would like to add this issue for stripe plugin in addition with #430.

Before last update, all was ok
BUT
Today if a guest do a payment via stripe plugin
THEN, stripe charge the plateform of credit card fees 
AND send a transfert to the owner account (connected account)

It means the jomres owner website is charged now with credit card fees....

Looking in stripe manual, now they are doing a difference with the "capabilities" and approach of payment.
https://stripe.com/docs/connect/charges#choosing-approach

Can you do something with that please ? And make jomes doing direct charges to connected account ?

Merci

Jerome

**Comment by jomres** [comment]
More information has been added.
