### ISSUE TITLE
Extended maps JS broken

### ISSUE THREAD

**Issue by rrmdp** [WoollyinWalesIT/jomres#450]
This is due to events and attractions lat/long not being sanitized for hyphens

**Comment by jomres** [comment]
Can you give me an example of the code that's causing the issue as displayed in the page source?

**Comment by rrmdp** [comment]
Just set any event with a negative lat/long and you will see the problem.

**Comment by jomres** [comment]
Yeah, but I want to know if it's an actual - or the html equivalent, Rod.

**Comment by jomres** [comment]
Resolved
