### ISSUE TITLE
Elfsight widget intégration

### ISSUE THREAD

**Issue by JeromePayan** [WoollyinWalesIT/jomres#456]
Hello again, 

Elfsight.com Can help us to add some lovely performing widget on our website, without code knowledge (i don't know to code yet ...)

For example = a booking.com or Airbnb.com review list. 
https://elfsight.com/airbnb-reviews-widget/

I know that Vince does not like this platform, but lot of guest feel more secure to read external review, from this kind of booking plateform.

**This  could let us converse the visit to a direct booking.**

For example, if i would like to add a airbnb Widget i will need to add this  script on my property page : 
<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-ee8d166c-c30a-41ee-8aa6-ca85e79854e5"></div>

Is there a hope to get this kind of widget in jomres core, or be able to integrate any property script code to call this kind of link

I am sure that PM will love to have this option ! 

Best regards and happy new year to all JOMRES community

Merci

Jerome

**Comment by jomres** [comment]
Can you show me the entire integration code?

**Comment by JeromePayan** [comment]
Vince the only integration code is a script calling the widget on their server.

On my demand, they did a new update, so now, Google can read the rating.... that great an helpfull for qualifing the property.

I asked them to make a all in one review so in my front page, i can get the entire review of all propertys (booking, airbnb, expedia, facebook).

That's looks great for now.

Check on : 
www.zeperfectplace.com

If jomres user wants to get a cupon code
https://www.elfsight.com/?ref=6d068a92-3a9c-47ef-8cf7-5dce4c23df6f&utm_source=referral&utm_medium=clients&utm_content=6d068a92-3a9c-47ef-8cf7-5dce4c23df6f


And here a screen shot for google reviewed :
![image](https://user-images.githubusercontent.com/25484155/86528141-a415e100-bea5-11ea-8054-5a203acb6a48.png)

**Comment by jomres** [comment]
So what do you want from me, Jerome? After their change?

**Comment by JeromePayan** [comment]
Vince, maybe can we be able to add this widget in the Review tab. For now i add the "ELFSIGHT" script in the property description

**Comment by jomres** [comment]
I think, as this is very specific to your requirements, it's best left to you to decide how you want it displayed. In the property description sounds best.
