### ISSUE TITLE
Adult and Child Tariffs

### ISSUE THREAD

**Issue by nine007** [WoollyinWalesIT/jomres#468]
Good day

this has always been a big big issue for us, that we cant set if a room can take children or not, and extra adult tariff, I see now that we can set what is the max adults and children per room, and that is fantastic, but there is still more issues. I saw that we can set the extra adult tariff in the property settings but than that tariff is for all rooms and it will not work because not all rooms are the  same some are 2 star or others are 3 star, some have extra features and so on, and then the tariff for extra adult is always different, it will be best to put the extra adult tariff field in the tariff plugin, and the ability to add more extra guests,  I attached a screenshot of what I have found on many many sites, and it works like a charm. Please, please, consider this while you are working on it, I have worked with this type of tariff setup on a couple if the big sites and its a real pleasure, it reduced the amount of tariffs greatly, then it wont be such a long list of tariffs in the front end, and what is more, the property owners find it very easy to work with.

thank you
![guestchildtarrif](https://user-images.githubusercontent.com/1021432/88376489-cf516900-cd9d-11ea-85d9-420f734541bc.png)

**Comment by jomres** [comment]
If you have a look at the Nightly commits, you'll see that work on this is already being done (I'm ahead of you here). I was reviewing the new functionality, and based on that and a client's feature requests I decided to enhance the new Standard tariff editing mode as now was the right time. 

Feel free to bang away at it and see if you can break things for me.

**Comment by nine007** [comment]
Good day

Sorry only getting back now, but am busy working on another project.  I like where you are going with it, and it could work really nice, but like you said in your blog you have to make the child rates and extra guests dependent on the room type, as it is now we still cant use it because all our clients tariffs are dependent on room types or the room only. if it could be expanded like my screenshot to be able to add more than just one extra guest and have the child rates included in the tariffs so that it could work on per room type or per room it would be great.

We use SRP's and MRP's, mostly MRP's

thank you for your great work, looking forward to see the end result.

**Comment by mcr71** [comment]
Hi Vince, 
I am not sure if I have understood the new functionality correctly: The price is always based on an occupancy with 2 adults? And each additional adult and child can then be charged separately?
However, I (and certainly many other users) miss the functionality of the old Advance Optional Plugin. 
Example: The basic price of the accommodation is for 4 guests (whether adults or children), the maximum occupancy is 6 guests. 
Every additional guest (guest number 5 and number 6) will be charged extra.
It would be great if you could take this into account in the further development. 
Thank you!

**Comment by JeromePayan** [comment]
Vince, hope your doing well and secure,
We all have a lack of understanding with the new guest level and extra person tariff.
Look to my ticket : View Ticket: #WTW-318-67486, i gave you access to my PM
We keep forward reading from you

**Comment by nine007** [comment]
Good day

Hope everyone is in good health, keep safe.

For me the quest types is a real issue, we have to keep telling clients that we cannot accommodate all their quest types and or their tariffs model. Below info on the Standard Tariff Model.

I like the occupancy level, I can set the number of adults and children per room.

The Child Rates are a step in the right directions but it needs 3 additional key features:
1.  We need to be able to set the child rates against a room or room type.
2.  From and To dates fields for seasonal rates.
3.  Percentage or fixed price field

Then in the Standard Tariffs model we need to be able to list the rates for 1 Adult, 2 Adults and so on, you can look at my screenshot I made.

Then on the booking page we need to be able to select the child numbers per room or per room type. We are loosing clients on a weekly basis because we cant give them what they want by providing them child policies on a per room basis. Some rooms only take babies, some take more ages and some do not take any children, all in just one property.  We really need this to work, all the other commercial sites provide their clients with these basic features.

Keep well all, and thank you.

![standard_tariffs](https://user-images.githubusercontent.com/1021432/108030311-b65d1d80-7037-11eb-95e0-7697d30a290a.png)

![guest_book](https://user-images.githubusercontent.com/1021432/108030415-ddb3ea80-7037-11eb-9147-95da0fbc4c88.png)

**Comment by Nikos-c** [comment]
That's is how it should be, all modern booking engines have these features. In real situations current way of creating rooms and tariffs doesn't give much flexibility and some simple things are impossible to do.
As I said in another post, tariffs should be created by room (name), not room type.
https://github.com/WoollyinWalesIT/jomres/issues/490


> 
> Good day
> 
> Hope everyone is in good health, keep safe.
> 
> For me the quest types is a real issue, we have to keep telling clients that we cannot accommodate all their quest types and or their tariffs model. Below info on the Standard Tariff Model.
> 
> I like the occupancy level, I can set the number of adults and children per room.
> 
> The Child Rates are a step in the right directions but it needs 3 additional key features:
> 
>     1. We need to be able to set the child rates against a room or room type.
> 
>     2. From and To dates fields for seasonal rates.
> 
>     3. Percentage or fixed price field
> 
> 
> Then in the Standard Tariffs model we need to be able to list the rates for 1 Adult, 2 Adults and so on, you can look at my screenshot I made.
> 
> Then on the booking page we need to be able to select the child numbers per room or per room type. We are loosing clients on a weekly basis because we cant give them what they want by providing them child policies on a per room basis. Some rooms only take babies, some take more ages and some do not take any children, all in just one property. We really need this to work, all the other commercial sites provide their clients with these basic features.
> 
> Keep well all, and thank you.
> 
> ![standard_tariffs](https://user-images.githubusercontent.com/1021432/108030311-b65d1d80-7037-11eb-95e0-7697d30a290a.png)
> 
> ![guest_book](https://user-images.githubusercontent.com/1021432/108030415-ddb3ea80-7037-11eb-9147-95da0fbc4c88.png)

**Comment by nine007** [comment]
Good day

when will these changes be incorporated so that we we could be inline with the current commercial booking sites?

thank you

**Comment by jomres** [comment]
Moved to here https://jomres.canny.io/historic-github-issues/p/adult-and-child-tariffs
