### ISSUE TITLE
Data too long for column 'rooms_tariffs'

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#480]
A booking was made a while ago for 66 guests in same booking. Jomres did what was expected.

Now to amend and change the date of the same booking, without any other changes, the following error is thrown

Core.ERROR: ~~ ally ~~ Do insert failed :: Data too long for column 'rooms_tariffs' at row 1 UPDATE #__jomres_contracts SET 					`arrival` 					= '2022/02/21', 					`departure`					= '2022/02/28', 					`rates_uid`					= '0', 					`guest_uid`					= '168550', 					`rate_rules`				= 'guesttype_41_66_1714.28571,', 					`rooms_tariffs`				= '516^156,517^156,518^156,519^156,520^156,521^156,522^156,523^156,524^156,525^156,526^156,527^156,528^156,529^156,530^156,531^156,532^156,533^156,534^156,535^156,536^156,537^156,538^156,539^156,540^156,541^156,542^156,543^156,544^156,545^156,546^156,547^156,548^156,549^156,550^156,551^156,552^156,553^156,554^156,555^156,556^156,557^156,558^156,559^156,560^156,561^156,562^156,563^156,564^156,565^156,785^156,786^156,805^156,806^156,807^156,808^156,809^156,810^156,811^156,812^156,813^156,814^156,952^156,953^156,954^156,955^156', 	
 	
Remedial action has been to cancel & create 2 x 33 guests new bookings.

**Comment by jomres** [comment]
That's certainly an edge case, first time I've seen that in 15 years. Have you seen it before?

**Comment by allynat** [comment]
Thankfully not. Maybe 66 rooms haven’t been amended in same booking before :(

Sorry you needed to close the forum :(

Regards

Ally

**Comment by jomres** [comment]
Yeah, 66 is a fair old chunk. You can change the length of that column in the db to "text" if you want, I don't think it'll cause you any problems.

**Comment by allynat** [comment]
Thanks Vince, I will bear that in mind for the next time (if it happens) & then I will change it!

Regards

Ally
