### ISSUE TITLE
Connect datepickers in advanced tarrifs

### ISSUE THREAD

**Issue by Nikos-c** [WoollyinWalesIT/jomres#483]
When selecting a date range in advanced or micromanage tariffs mode the "To" datepicker should jump to +1 day from the date already selected in "From" datepicker and disable previous dates.

Just in case you missed it: Documentation: https://jqueryui.com/datepicker/#date-range

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/historic-github-issues/p/connect-datepickers-in-advanced-tarrifs
