### ISSUE TITLE
Plugin Retired, uninstall it - Cannot

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#484]
Hi Vince

Joomla! 3.9.22
Jomres 9.23.6

Backend Plugin Manager
As expected I see 

- Guest Types
- Advanced Micromanage Tariff Editing Modes 

are listed as Plugin retired, uninstall it in Red.

I am unable to click the Uninstall button to remove the 2 plugins.

Regards

Ally

**Comment by mcr71** [comment]
I was able to do this. Did you clear all caches or temp directories?

**Comment by allynat** [comment]
Unresolved

**Comment by jomres** [comment]
Update to the Nightly, IIRC there's a fix in there for that.

**Comment by allynat** [comment]
Thanks

Regards

Ally

**Comment by rrmdp** [comment]
Yeah, it's due to a JS error, you could just remove both plugins folders within the core-plugins one and then rebuild Jomres registry. Vince's included both plugins as core code so are not longer needed.

PS: hope you are doing well Ally!

**Comment by allynat** [comment]
Hi Rod!

Thanks for the suggestion, I was interested to notify Vince of the issue, rather than fix/work-around myself 🤓

All is good here, hope you are too, stay well & healthy!

Regards

Ally
