### ISSUE TITLE
Please do not install REST API related plugins

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#485]
Joomla! 3.9.22
Jomres 9.23.6

The Yellow banner at the top of the Plugin manager page reads

_Please do not install REST API related plugins until you have confirmed that your installation of Jomres is able to run them. To do that, please visit the Admin > Jomres > Tools > REST API test page. This includes any of the "Channelmanagement" plugins._ 

However, there is not Admin > Jomres > Tools > REST API test page option in the Admin > Jomres > Tools > menu

**Comment by mcr71** [comment]
Hi Ally, 
the option is still there. Maybe you have selected the basic setting for viewing the admin area options (new since 9.23.5) ?
![image](https://user-images.githubusercontent.com/23499447/99631269-92d80600-2a3b-11eb-983d-f6e4e0a4ee59.png)

**Comment by allynat** [comment]
Sorted
