### ISSUE TITLE
Do you accept children under 18 years of age?

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#486]
Joomla! 3.9.22
Jomres 9.23.6

Do you accept children under 18 years of age? = YES

_Set this option to Yes if you allow children. If yes, then in the Settings menu you will have an option called Child Policies where you can edit children related settings._

However, there is not an additional menu option Settings>Child Policies

Regards

Ally

**Comment by mcr71** [comment]
It's there ;)
![image](https://user-images.githubusercontent.com/23499447/99632503-9d939a80-2a3d-11eb-8904-44ae69af8a0d.png)

**Comment by allynat** [comment]
Unresolved

**Comment by lajanchi** [comment]
hi!!! i think this option "child policies" only shows up when selecting the new tariff method... i think it is the "standard tariff mode"...

**Comment by mcr71** [comment]
Yes, you are right - it's a little bit confusing for those who don't use the standard tariff mode. It should be added to the notes on the setting page, that it only appears if you select the standard tariff mode.

**Comment by hkraskian** [comment]
Older installations don't have "Standard tariff mode" tab in their admin panel -> settings -> property configuration.
Neither they have "child policies" and "minimum occupancy" menu items.
So, we have to train property managers for two different interfaces, which is confusing.
I understand, that we can not force older property managers to change their settings, but it will be good to have a choice for site admin to decide about it, or migrate all users to the same interface.

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/historic-github-issues/p/do-you-accept-children-under-18-years-of-age
