### ISSUE TITLE
Dashboard scrunches up all lozenges to a single lozenge - Wordpress 5.6 Breaks it

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#489]
Jomres 9.23.6
Wordpress 5.6

Data of system intact and List Bookings show many bookings for period to be displayed.

If the duration to show is Day, more of a lozenge is displayed but not all. If Week, Month or Year are selected, then all lozenges are scrunched.

Sh*t happens at this time of year ! Happy New Year

Regards

Ally

**Comment by jomres** [comment]
I'm aware of this, try the Nightly branch, it should have been resolved in that.

**Comment by allynat** [comment]
Thanks Vince

Regards

Ally
