### ISSUE TITLE
bookings reports 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#49]
https://www.jomres.net/forum/Feature-requests/24947-very-basic-feature-missing-bookings-reports

a very basic feature is missing from Jomres.
Right now there is no way for admin to know how many bookings were made, for which properties, commission earned by each property, how many clicks each property had, etc.
These statistics should be available under reports in admin area

**Comment by aadz1** [comment]
+1

**Comment by juliogar63** [comment]
+1

**Comment by ReneCB** [comment]
+1
