### ISSUE TITLE
Tariffs by room name not by room type

### ISSUE THREAD

**Issue by Nikos-c** [WoollyinWalesIT/jomres#490]
Dear Vince,

Having the limitation of creating just one tariff per room type doesn't make the whole procedure very flexible.
Tariffs should be created by room name.
 A real life example:
 A hotel offers rooms, all of them identical, except of that some have view to the sea and some to the garden. The ones with view to the sea cost more than the others, so there must be two different tariffs, one for rooms with sea view and one for rooms with garden view.
 In the above situation you can not create two different tariffs based on room type, you can create just one (that's the problem).
 One may say that you could create two different room types and then create one room name for each room type. But if you do that, then what is the point of having room types and room names. That can only confuse users, not to mention that room types have no meaning any more.
 I can give many more examples but I believe I made my point.

Thank you

**Comment by jomres** [comment]
Moved to https://jomres.canny.io
