### ISSUE TITLE
Who Cancelled the Booking

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#50]
https://www.jomres.net/forum/Feature-requests/24989-who-cancelled-the-booking

If a system is used by many receptionists then managing who did what & when is a little difficult if people do not write notes against everything they do.

If a booking is cancelled (Cancel Booking link) then a field is shown to allow user input. A cancellation reason can be added and if the reception staff are kind, they could enter their name.

But as the reception staff member is logged in to do this, then recording the username of the user who cancelled the booking would be possible.

When we look at the cancelled booking Reservation details - Notes, the cancellation reason message entered during cancellation is not currently shown, merely a Booking cancelled message.
2016-05-10 21:32:06
Booking cancelled

When the cancellation email is sent, the following items are sent to either the guest or the hotel:
Booking number: [BOOKING_NUMBER]
Arrival: [ARRIVAL]
Departure: [DEPARTURE]
Grand total: [TOTAL]
Deposit: [DEPOSIT]

Ideally the cancellation reason and the username who cancelled the booking should be visible in the Notes of the booking and also available to be relayed to the recipients of the cancellation emails.

Please join me in recommending this suggestion for inclusion in a future release.

**Comment by natanzi** [comment]
+1 
Very Useful and professional item

**Comment by natanzi** [comment]
Dear Vince when we talking about who make a booking and who cancel a booking we need username
better than we can see this username in one column of  booking list.

**Comment by aadz1** [comment]
+1
