### ISSUE TITLE
Global Payment Gateway - Show Confirmation

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#515]
If the global payment gateway is enabled and set to override front end, and require deposits is set to No, the payment gateway still shows in the Show Confirmation page.

Therefore if 1 property of xN properties does not take deposits, the global payment gateway must be set to not override front end and all properties configured separately.

I would suggest this detail needs to be included in the property booking form configuration tab.

Regards

Ally

**Comment by jomres** [comment]
Moved to https://jomres.canny.io/historic-github-issues/p/global-payment-gateway-show-confirmation
