### ISSUE TITLE
Overwrite paypal frontend settings 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#55]
https://www.jomres.net/forum/Feature-requests/25079-overwrite-paypal-frontend-settings

Some portals uses the payment method, that every money is send to their account.
Its possible to overwrite the payment settings for a lot of gateways except paypal. If there the option is turned on EVERY other gateway is dead.

My feature request is that it overwrites just the frontend settings of paypal property owner and KEEP other gateways alive too

**Comment by marinhio** [comment]
Found a very easy way to do this and to keep other gateways alive^^

**Comment by mirko-mcr** [comment]
Great to hear Marinhio...but how? I hope you will let us know ;)
