### ISSUE TITLE
Cart checkout and Booking Enquiries plugins

### ISSUE THREAD

**Issue by allynat** [WoollyinWalesIT/jomres#61]
Checkout using the cart facility is a great way for a customer to add bookings from multiple properties to a cart and then proceed as 1 confirmation.

But the downside is that each property raises a paypal link to be paid, the customer must follow each link and make a separate payment, so there is no real saving of effort for the customer.

The cart will only function if the front end settings of the papal gateway is set to yes, so why not create 1 link?  - **Issue 1**

If Jomres is not using Booking Enquiries, each of the paypal links created at confirmation work fine and connect the customer with paypal to make their payment.

But if Jomres is using the Booking Enquiries plugin and therefore needing for all bookings to be Approved before the link is sent to the customer, then the paypal links created by the Cart plugin do not work and the customer is unable to pay via the link. - **Issue 2**

Ally

**Comment by alibarthi** [comment]
Cart can`t be used with booking enquiries.
