### ISSUE TITLE
Create user on booking (joomla)

### ISSUE THREAD

**Issue by buttonsbond** [WoollyinWalesIT/jomres#62]
Hi, I have turned on allow new user registration in Joomla as well. When the option is set in JomRes to create a new user on booking it fails. I get an error in the JomRes log as follows:

Do insert failed :: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''{}' )' at line 18 INSERT INTO #__users ( `name`, `username`, `email`, `password`, `registerDate`, `lastvisitDate`, `lastResetTime`, `params` ) VALUES ( 'Mark Andrew VB', 'bellen@hotmail.com', 'bellen@hotmail.com', '11765631902fa9df97105bf42ba0cf05', '2016-11-18 10:57:01', '2016-11-18 10:57:01', '2016-11-18 10:57:01',3 '{}' )

Is there a comma missing in the SQL statement between the number 3 and the string '{}'
[I changed the actual e-mail address in the posting]

Thanks, Mark

**Comment by jomres** [comment]
Should be fixed by #525f2b271631fa5840f75857db59b39242cb8c02

**Comment by jomres** [comment]
https://github.com/WoollyinWalesIT/jomres/commit/525f2b271631fa5840f75857db59b39242cb8c02

**Comment by jomres** [comment]
Mark, that issue should be resolved by the above linked change.

**Comment by buttonsbond** [comment]
Thanks Vince, I assume I just download and replace the file. If I 
install JomRes on a new installation will that change be in the download 
package or will I need to apply the patch manually?

Regards,

Mark

------ Original Message ------

**Comment by jomres** [comment]
It would be better to apply the patch manually, there are a variety of other changes to this version (mostly user role related) and the 9.8.19 functions.php almost certainly will not work on 9.8.18.

**Comment by buttonsbond** [comment]
thankyou.
