### ISSUE TITLE
Override accommodation total on review booking

### ISSUE THREAD

**Issue by buttonsbond** [WoollyinWalesIT/jomres#63]
Apologies if this is intentional.
When you override the total entering 0 reverts to the full price. Maybe I've misunderstood this ability - but I was hoping that if I blocked out dates (say in the case of an owner the price would therefore be free?)
It adjusts the total if you use any other number than 0!

**Comment by jomres** [comment]
If you want to block out dates, just use the Black booking feature Mark.

**Comment by buttonsbond** [comment]
ah right, sorry. I'm just playing around with the system at the moment for a friends villa. I'd need to upgrade from the free core to use that. No problem. Thanks for your help.

**Comment by jomres** [comment]
You don't upgrade from the Core. The Core is freely available to all in both WP and Joomla. To add bells/whistles you can get a license key ( including a trial license key ) to install plugins. Black booking is one of those plugins.
