### ISSUE TITLE
Feature: Improve user management

### ISSUE THREAD

**Issue by Bodge-IT** [WoollyinWalesIT/jomres#64]
Could you add a reference to which Joomla user the Jomres user is linked to?
There's currently no way to tell after creation.

**Comment by allynat** [comment]
I would also suggest that when a joomla / wordpress user is deleted, that the jomres user name is not left as a blank.

**Comment by alibarthi** [comment]
Reference meaning a link to the cms user profile? 
If the user was deleted, the username will be "-" and marked with yellow: https://github.com/WoollyinWalesIT/jomres/commit/fc99f10c0d500f0283d18f43d394ff6da611d7e5

**Comment by Bodge-IT** [comment]
"Reference meaning a link to the cms user profile?"
NIce helpful UI touch.

**Comment by alibarthi** [comment]
Added a link/button next to the username field that points to the edit cms user page: https://github.com/WoollyinWalesIT/jomres/commit/f2f6ee40fbac1a1dc30ea719a67f8c2c561e1359

**Comment by natanzi** [comment]
I suggest that we separate user management from cms (Jomla and wp),
and make it inside in Jomres

**Comment by jomres** [comment]
That's never happen, Natanzi, unless Jomres becomes an entirely Standalone product, which isn't on the horizon right now.

**Comment by natanzi** [comment]
I got it.
Vince
jomres had many powerful features  and User management dependency to joomla is weird. because you separate so many things but keep user management in joomla, 👍 
entirely standalone is strongly suggested to you... jomres can be connected to joomla or every CMS (even custom cms)  in all of world with API !
