### ISSUE TITLE
Boostrap 4 - Regular Grid VS Flexbox Grid

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#65]
Boostrap 4 is slowly but surely moving forward, this is an excellent article http://tutorialzine.com/2016/11/boostrap-4-regular-vs-flex-grid/ discussing the differences between Regular Grid VS Flexbox Grid

Do any of our users have any opinions they'd like to share with us regarding which strategy they'd like us to use once BS4 has been released?

**Comment by Nikos-c** [comment]
Definately Flexbox

**Comment by jomres** [comment]
Thanks for the response Nikos. I know what I think, but I'd like to hear your reasoning on the subject.

**Comment by Nikos-c** [comment]
Aesthetically speaking, you get a better result

**Comment by Nikos-c** [comment]
I forgot to mention that there was already a discussion about flexbox here:
https://jomres.net/forum/How-do-I/25370-equal-height-columns-in-leotian-template-list-photo-view

**Comment by natanzi** [comment]
good

**Comment by jomres** [comment]
For the record, BS4 will be flexbox by default, so it's no longer a question for us. Closing.
