### ISSUE TITLE
Add search by property feature in Joomla menu

### ISSUE THREAD

**Issue by rade039** [WoollyinWalesIT/jomres#66]
Hello,

I have a conversation with Aladar and he tell me to post feature request here. I need to add to menu item search link by property feature (but not as out link), so I can have sef link of search results.

This is what Aladar write:
"I think it will be possible to just add one feature per link, i`m not sure if it`s possible to select more when creating a new jomres menu of type propertyfeature from the joomla menu manager. Please add this to the feature requests forum and as soon as i`ll have some time i`ll try to add this. "

It will be great to add to Jomres ASAP, thank you in advance.

**Comment by pursuit-jp** [comment]
This would be great for us as well. The ability to create a menu item with more than 1 feature selected would be even better.

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Order 66 executed.

**Comment by jomres** [comment]
Issue number 66. Order number sixty....oh, forget it.
