### ISSUE TITLE
Data tables search : Non latin characters will throw up no results

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#67]
j06001listyourproperties_ajax.class.php L41 'last_changed' will cause mysql to throw an error when searching for non-latin strings such as Φυλάω

Illegal mix of collations for operation 'like'

http://stackoverflow.com/questions/18629094/illegal-mix-of-collations-for-operation-like-while-searching-with-ignited-data

Last changed is a date. Removing it from the original array ( $aColumns L41 ) will allow the query to go through, but then we can't sort properties by the last changed column.

**Comment by alibarthi** [comment]
This is not a bug with datatables, but insetad with the mysql tables and columns collation. Try converting the tables and columns to utf8mb4_general_ci
