### ISSUE TITLE
Menus - API Bridge

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#70]
Develop functionality that will allow a Jomres menu item to call the API features. 

Something like : 

1. API bridge receives an endpoint request & params. 
2. API bridge sends request to the API using the jomres_call_api functionality. 
3. On response the API bridge uses "some plugin" to translate the response into content that is displayed in the page.

The advantage of this approach is that we will be able to re-use API features in the core, gradually allowing us to morph Jomres UI into a true UI that's independent of the underlying framework.

Currently, the we've got 

Jomres = Framework + UI all wrapped into one. What we need, for future development is

Jomres UI --> API bridge --> API --> Framework
Jomres UI <-- API bridge <-- API <-- Framework

Then for mobile apps / remote clients of any flavour

App --> API --> Framework
App <-- API <-- Framework

We don't really care what/how the remote service, be it an App or some other client, presents the end results to the user, what do do care about is ensuring that we have an elegant way of facilitating code re-use.

**Comment by natanzi** [comment]
Dear Vince,
As you know nowadays all business use mobile app or connect to remote site for using cloud service.
you better than every person know Api functions not only open the new world to jomres but also help to customers for develop feature and adapted their services to new technology such as Iot ,and also users can freely choose any template or plugin via API connectivity for their jomres, this is big impact for jomres market.
first of all jomres need develop API for booking engine and after that some expert users aslo can be develop new plugin for that and put in jomres library for example.
if you accommodate API engine next steps is easy ..
Much appreciate.
