### ISSUE TITLE
room category images 

### ISSUE THREAD

**Issue by nawangnamgil** [WoollyinWalesIT/jomres#71]
when i have 10 room superior and list the 10 room for booking for each list needs picture means for 10 resources there is same 10 picture which looks nonsense

**Comment by nawangnamgil** [comment]
try to paste the widget html code in HTMl property to show the rating of trip advisor it doesn't work

**Comment by nawangnamgil** [comment]
TripAdvisor become so popular now 99 customers first want to know review of trip advisor booking before take nay booking step it should work in the tab area to show their review

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Whilst I'd like to add this feature there isn't enough support for it therefore closing this feature request.

The trip advisor comments are completely different and if you'd still like to have them as feature requests, please create new issues for them.
