### ISSUE TITLE
Add room type images uploader and a switch to display rooms individually or by room type

### ISSUE THREAD

**Issue by alibarthi** [WoollyinWalesIT/jomres#73]
We need a yes/no switch so managers can decide if they want to display the rooms individually or by room type (with a generic room type image and a counter of how many rooms of each type they have).

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Current version allows listing of rooms by room type, I don't think a switch is necessary, templates can be modified to remove urls to existing "room individual rooms" scripts.
