### ISSUE TITLE
Property list with 'live' map 

### ISSUE THREAD

**Issue by jomres** [WoollyinWalesIT/jomres#8]
https://www.jomres.net/forum/Feature-requests/25361-property-list-with-live-map

Hi,
is it possible to show the property list together with a 'live' map? There is already the mapview plugin, which is great, but I would prefer to show it together with the list (or photo) view. After a search is triggered the map and the list/photo view should be updated of course.
Or can this already be done (without too much coding)?

It would also be great, if the property list updates after the map is dragged, so that only the objects are listed, which you can see on the current map. This functionality is offered by many other portals (eg homeaway).

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Rodrigo Rocco is working on his Valentina template pack for Jomres which includes this feature.

I urge you to contact him and ask him about it.

https://www.jomres.net/blog/83-jomres-plugins-valentina
