### ISSUE TITLE
date in book_guest_in_out plugin

### ISSUE THREAD

**Issue by mreza9** [WoollyinWalesIT/jomres#80]
Dear Vince
I think this plugin has a issue.
date in below query returns server time, not local time...

`$query="UPDATE #__jomres_contracts SET `bookedout`=1, `bookedout_timestamp`='".date( 'Y-m-d H:i:s' )."' WHERE contract_uid = '".(int)$contract_uid."' AND property_uid = '".(int)$defaultProperty."'";`

I used DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s') for local time as follow:

`$query= "UPDATE #__jomres_contracts SET `bookedout` = 1, `bookedout_timestamp` = DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s')  WHERE contract_uid = '".(int)$contract_uid."' AND property_uid = '".(int)$defaultProperty."'";`

Thank you...

**Comment by alibarthi** [comment]
This column/timestamp is not used/displayed anywhere. So basically changing this won`t affect anything, so we won`t make the change for now. If in the future this data will be used somewhere, we`ll make it work ok.

**Comment by mreza9** [comment]
This column/timestamp is used/displayed in "jomcomp_notes" table.

**Comment by alibarthi** [comment]
We`ve made this change for the next version: https://github.com/WoollyinWalesIT/jomres/commit/2e5afe6fdde2f966a21a93dfcac5d52e954cea1c
