### ISSUE TITLE
Ability to turn off automatic email messages

### ISSUE THREAD

**Issue by picturesque** [WoollyinWalesIT/jomres#82]
We would like to have the ability to disable selected automated email messages. For example, guest confirmation. It would be great to have this for all email messages as part of the template edit screen as different properties have separate requirements, however a global setting would also be acceptable.

**Comment by natanzi** [comment]
+1
I agree , better than add one item seems "service status" for show status of any service such as Email sending ,SMS , Twitter and any person can be ON/OFF for each Property Type

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Whilst I'd like to add this feature there isn't enough support for it therefore closing this feature request.
