### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Indivento** [WoollyinWalesIT/jomres#83]
Hi,

I only offer tours at my website. Most of them have the same extra's like an Insurance. It would be great if it is possible to create extra's first and then add them with every tour they are needed. At this moment I have to create the same extra's on and on...

**Comment by natanzi** [comment]
+1

**Comment by aadz1** [comment]
+1

**Comment by jomres** [comment]
Whilst I'd like to add this feature there isn't enough support for it therefore closing this feature request.
