### ISSUE TITLE
Site Wide Coupons Feature Request

### ISSUE THREAD

**Issue by pursuit-jp** [WoollyinWalesIT/jomres#84]
Hi,

I initially asked this as a ticket and Aladar suggested I post it here:

> Is there a way to create site wide coupons or to do a bulk upload of coupons? 

> We use quite a few gift certificates and we also do pre-paid 5-packs that are each valid for an individual tour (setup as regular properties, not Jintour) and the process of adding these to each property can get quite tedious.

> Also, any options to integrate the process with something like HikaSerial to automate the process? 

Found two similar requests in the forum:
https://www.jomres.net/forum/How-do-I/22924-how-do-i-make-a-coupon-valid-for-all-properties#33374 
https://www.jomres.net/forum/Professional-services/24102-help-develop-a-coupon-code-plugin#38419

**Comment by aadz1** [comment]
+1

**Comment by alibarthi** [comment]
This will be available in the next jomres version and will also require a coupons plugin update
