### ISSUE TITLE
markdown in je_fps

### ISSUE THREAD

**Issue by jgtokyo** [WoollyinWalesIT/jomres#86]
Property description markdown in je_fps appears as markdown, not styled.  

<img width="244" alt="screen shot 2016-12-13 at 10 53 59 am" src="https://cloud.githubusercontent.com/assets/23737679/21124594/38afb572-c123-11e6-80ab-40ced00a01d9.png">

**Comment by alibarthi** [comment]
An updated version of the je_fps plugin will be released shortly to solve this,
