### ISSUE TITLE
List properties > 

### ISSUE THREAD

**Issue by jgtokyo** [WoollyinWalesIT/jomres#87]
"List properties" is displaying the Japanese translation of a site's address (this Japanese propagates through to plugins like "top destinations").  The property details pages are shown correctly:

This is the problematic English display containing Japanese:
<img width="908" alt="screen shot 2016-12-13 at 2 41 53 pm" src="https://cloud.githubusercontent.com/assets/23737679/21129044/ab77b9e6-c142-11e6-869c-46911fcc9bc9.png">
Despite correct EN pdetails :
<img width="606" alt="screen shot 2016-12-13 at 2 46 31 pm" src="https://cloud.githubusercontent.com/assets/23737679/21129157/436e80ea-c143-11e6-9828-6ff21d059774.png">

The Japanese display is as expected:
<img width="890" alt="screen shot 2016-12-13 at 2 47 02 pm" src="https://cloud.githubusercontent.com/assets/23737679/21129182/62148a6c-c143-11e6-93ef-6f67d46f9487.png">
and pdetails JA:
<img width="631" alt="screen shot 2016-12-13 at 2 47 24 pm" src="https://cloud.githubusercontent.com/assets/23737679/21129192/6f89b9f6-c143-11e6-8c35-b68de37c6a05.png">

**Comment by alibarthi** [comment]
So address and town fields are not translated?
