### ISSUE TITLE
API Plugin's language file does not change

### ISSUE THREAD

**Issue by mreza9** [WoollyinWalesIT/jomres#88]
hi,
I define a new language file in API Plugins (api_feature_favourites, api_feature_properties, etc) in /api_feature_XXXX/language/xx-XX.php and call it by API such as: /jomres/api/properties/85/details/name/xx-XX, but LANGUAGE does not change and load default (en-GB language)...
Also, I change the code manually, but does not change....

	if (!isset($language))
		$language = "xx-XX";
	$_REQUEST['pbookinglang'] = $language;

thanks,

**Comment by jomres** [comment]
You're mis-using the language file, that file is purely for descriptions of the API features. It would not be incorporated in the API response itself.

**Comment by mreza9** [comment]
Dear Vince, Hi
I used jr_gettext function in API plugins.

`$saveMessage= jr_gettext('_JOMRES_BOOKGUESTINOUT_API_CHECKIN','_JOMRES_BOOKGUESTINOUT_API_CHECKIN',false,false);`

and I define it in language folder
\language\en-GB
`jr_define('_JOMRES_BOOKGUESTINOUT_API_CHECKIN',"Booked guest in");`

\language\xx-XX
`jr_define('_JOMRES_BOOKGUESTINOUT_API_CHECKIN',"Бронирования гость");`

When I call API, Only read en-GB language. 
I think language variable ($language) can not load in framework, or $_REQUEST does not work!!!
`$_REQUEST['jomreslang'] = $language;`

Could you check it, please?
Could you help me, How to call other language, please?

Regards,

**Comment by jomres** [comment]
Please raise a support ticket, Github's not the best place for answering a question like that as we'll need access to your server to look into it.
