### ISSUE TITLE
je_top_destinations  incorrect href in foreign language

### ISSUE THREAD

**Issue by jgtokyo** [WoollyinWalesIT/jomres#89]
In the links created for each panel in je_top_destinations, href links created in EN-GB work properly, and are as follows: 
http://[domain.com]/component/jomres/search/**region**/[regionname]?itemId=0
http://[domain.com]/component/jomres/search/**town**/[townname]?itemId=0

but the href links created in foreign language (in my case JA-JP) are missing the "/region" (or "/town" etc) bit after "/search."  What appears in the foreign language link is the (translated) equivalent of: 
http://[domain.com]/component/jomres/search/[regionname]?itemId=0
http://[domain.com]/component/jomres/search/[townname]?itemId=0

**Comment by alibarthi** [comment]
Is "unicode aliases" set to yes in joomla global configuration?
