### ISSUE TITLE
Custom fields at booking form in Jomres (not only text fields)

### ISSUE THREAD

**Issue by edegarglez** [WoollyinWalesIT/jomres#90]
Hello, 
We need some custom fields at booking form. Simple text field is not enought. There are two cases:

* Dropdown list to select between some predefined values. Also we need this value will be shown in booking list, and it will could be used to filter booking list.

* Editable price field, when the system is using by a receptionist or an admin user. In this case, we need the initial shown price will be like now (the configurated price for the selected rooms), but it could be modified by the user.

Regards,
Edelia.

**Comment by natanzi** [comment]
+1
 useful if save record of modify price per users
for example i am receptionist  and change price manually so after save this booking ,we should be able to see how book this reserve ? and whats is first price and receptionist price.
first price :100$ (configured by system)
receptionist Price 120$
