### ISSUE TITLE
Bug wiht property of Jintour type.

### ISSUE THREAD

**Issue by rrmdp** [WoollyinWalesIT/jomres#97]
When creating a property of type tours is asking for "Create some tariffs" http://take.ms/ypCCL and when clicking on the tariffs link http://take.ms/wvMdA . When trying to book the it shows up the contact form (because no tariffs being set up)

**Comment by alibarthi** [comment]
This can only happen if the Tour property type doesn`t have "what will guests book?" set to Tours. It`s probably set to Both or something else. I can`t replicate this on my site with proper tour property type setup.
