### ISSUE TITLE
I agree with the review gives wrong message

### ISSUE THREAD

**Issue by villykou** [WoollyinWalesIT/jomres#99]
If a nonregistered user clicks on thumb up or down of an existing review gets a message "Thank you, but you have already shared your opinion of this review."

This message is meant for those who have already clicked once on a thumb.

I think that it should be another message, something like "Only registered users can post"

**Comment by alibarthi** [comment]
Can`t replicate this..are you trying to do this from the same ip you`ve already used for testing or adding the review?

**Comment by villykou** [comment]
As I was not sure, I have reset the router (so IP is changed) I use a new browser, clear all history and cookies.
Not logged in I click on a thumb up of a review and I see the same message: Thank you, but you have already shared your opinion of this review.

**Comment by alibarthi** [comment]
I could replicate this now with the new info. This changeset will solve it: https://github.com/WoollyinWalesIT/jomres/commit/43729a0f7f812cc194d433a5ae573cba0a8080bb
